### ISSUE TITLE
Installation issue: dyninst@9.3.2 + boost, setup_dependent_package from pr #20198 breaks boost <= 1.69.0

### ISSUE THREAD

**Issue by jordialcaraz** [LLNL/spack#20424]
I try to install dyninst@9.3.2 but get the following error:

==> dyninst: Executing phase: 'cmake'
==> Error: AttributeError: 'NoneType' object has no attribute 'spec'

/home/jalcaraz/spack/var/spack/repos/builtin/packages/boost/package.py:552, in _cmake_args:
        551            def _cmake_args(self):
  >>    552                return ['-DBoost_NO_BOOST_CMAKE=ON'] + args_fn(self)

### Steps to reproduce the issue

$spack install dyninst@9.3.2

@hainest 

### General information

- [X ] I have run `spack debug report` and reported the version of Spack/Python/Platform
* **Spack:** 0.16.0-219-0924b20
* **Python:** 2.7.5
* **Platform:** linux-centos7-sandybridge
* **Concretizer:** original

Another machine with same error:
* **Spack:** 0.16.0-230-86ae63b64
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

- [X ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X ] I have uploaded the build log and environment files
- 
[spack-build-env.txt](https://github.com/spack/spack/files/5701795/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5701797/spack-build-out.txt)

- [ X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hainest** [comment]
This is a known concretizer bug that was recently addressed (#20341). As an aside, Dyninst 9 is no longer supported. I would strongly encourage you to upgrade to 10+. I'm a Dyninst dev, so I would be happy to help with any upgrade troubles.

**Comment by jordialcaraz** [comment]
I tried to use 10+ but I get a segmentation fault and using gdb i get an error sayind dwarf_error.c does not exist.


I will try to install dyninst manually until the fix is available. Thank you.

**Comment by hainest** [comment]
>I tried to use 10+ but I get a segmentation fault and using gdb i get an error sayind dwarf_error.c does not exist.

Please submit a bug report on https://github.com/dyninst/dyninst. Be sure to include as much information about your environment as possible (e.g., OS, compiler, glibc, etc.) and the exact error messages you were seeing. If you can include a minimum working example to demonstrate the error, that would be great, but not mandatory.

**Comment by jgalarowicz** [comment]
Hi all,
I'm seeing the same thing with dyninst@10.0.0 when trying to build on a Power8 platform.
```
+] /sw/spack/opt/spack/linux-centos7-power8le/gcc-7.4.0/libmng-2.0.3-c43upycvhnjudhplxpmrh2qn7iwklom6
[+] /sw/spack/opt/spack/linux-centos7-power8le/gcc-7.4.0/bdftopcf-1.0.5-kcicih4gfkr4mxsg6r63h3owcjxwvcxk
[+] /sw/spack/opt/spack/linux-centos7-power8le/gcc-7.4.0/mkfontdir-1.0.7-4xuttcxqdkzvws4fehbxpdspeiqc2hzw
==> Installing dyninst-10.0.0-be6ukxlm5fkezn4wsns3nnuynsnqf5lp
==> No binary for dyninst-10.0.0-be6ukxlm5fkezn4wsns3nnuynsnqf5lp found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/git//dyninst/dyninst.git/v10.0.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> dyninst: Executing phase: 'cmake'
==> Error: AttributeError: 'NoneType' object has no attribute 'spec'

/sw/spack/var/spack/repos/builtin/packages/boost/package.py:557, in _cmake_args:
        556            def _cmake_args(self):
  >>    557                return ['-DBoost_NO_BOOST_CMAKE=ON'] + args_fn(self)

See build log for details:
  /sw/builds/spack_stage_files/jgalarowicz/spack-stage-dyninst-10.0.0-be6ukxlm5fkezn4wsns3nnuynsnqf5lp/spack-build-out.txt

==> Warning: Skipping build of cbtf-krell-1.9.4-z6q6um36igjhd7ezkfxblzorizn7a5qs since dyninst-10.0.0-be6ukxlm5fkezn4wsns3nnuynsnqf5lp failed
==> Warning: Skipping build of openspeedshop-2.4.2-w7rhcmcvq4hlkes72nw3nm5dj3bjr6nq since cbtf-krell-1.9.4-z6q6um36igjhd7ezkfxblzorizn7a5qs failed
[+] /sw/spack/opt/spack/linux-centos7-power8le/gcc-7.4.0/libdwarf-20180129-p4nnkutsjcbn2xepkmuufaqhs6q2w542
[+] /sw/spack/opt/spack/linux-centos7-power8le/gcc-7.4.0/libx11-1.7.0-mrlqcxipgoferxh6xpdfaehoar3uibkm```

@jordialcaraz   
@hainest -- did the build work when you used version 10?   Or was there additional steps required?  Thanks for any information.   Jim G

**Comment by mwkrentel** [comment]
I was about to report this as a separate bug, but then a search for boost turned this up.

I believe the real problem is the setup_dependent_package method introduced in PR #20198.
If you delete the setup_dependent_package method, then it works.

I suggest you change the subject to something like:  'setup_dependent_package
from pr #20198 breaks boost <= 1.69.0'

----------

Here is the bug report that I was about to file:

I believe there is something incomplete or missing (ie, broken) from
this patch.  Boost builds Ok, but some cmake packages that depend on
boost fail.  This applies to boost <= 1.69.0.

```
$ spack install dyninst ^boost @1.66.0
...
==> dyninst: Executing phase: 'cmake'
==> Error: AttributeError: 'NoneType' object has no attribute 'spec'

/home/krentel/boost/spack-repo/var/spack/repos/builtin/packages/boost/package.py:557, in _cmake_args:
        556            def _cmake_args(self):
  >>    557                return ['-DBoost_NO_BOOST_CMAKE=ON'] + args_fn(self)

```

If I remove the setup_dependent_package method, then it works.

```
$ spack  debug report
* **Spack:** 0.16.0-916-f7064fa181
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** original
```

ping @alalazo  @haampie

**Comment by mwkrentel** [comment]
Note: the version of dyninst doesn't matter.
Both @jgalarowicz and I report the same failure with current dyninst.

**Comment by jgalarowicz** [comment]
Yes, I agree with Mark.   Doesn't matter what the version of Dyninst is.

**Comment by hainest** [comment]
Dyninst 13.0.0 requires boost@1.71.0 or newer, so I'm going to close this. If you are still experiencing issues, please reopen this issue or submit a new one.
