### ISSUE TITLE
HDF5 does not build with Intel 17.0.2 but is caused by OpenMPI wrapper changes

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/spack#5843]
This used to work fine for me. Now I get:

```
checking whether a simple MPI-IO C program can be linked... yes
checking whether a simple MPI-IO Fortran program can be linked... no
configure: error: unable to link a simple MPI-IO Fortran program
```

In `config.log` this is because:
```
conftest.f90(3): error #7013: This module file was not generated by any release of this compiler.   [MPI]
          USE mpi
--------------^
```

After some research, I looked at a log of my previous OpenMPI that created a working HDF5 with Intel (I shortened paths):
```
*** Fortran compiler
checking whether we are using the GNU Fortran compiler... no      
checking whether ......../spack/lib/spack/env/intel/ifort accepts -g... yes 
```

My most recent OpenMPI build shows:
```
*** Fortran compiler
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
```

Therefore something changed since September 13 at least that is causing OpenMPI to use GCC underneath even though I am using `%intel@17.0.2` and then fail at building HDF5. Currently my OpenMPI wrappers do still show Intel underneath after install though:
```
[user@machine bin]$ ./mpif90 --version
ifort (IFORT) 17.0.2 20170213
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
```

I do not see anything that changed to the OpenMPI package since then. So I am not sure what is causing this.

**Comment by jrood-nrel** [comment]
A little more to this story. I tested OpenMPI 1.10.4 and 2.1.1 with the same results. Also looking at the `build.env` for OpenMPI in both cases:

```
Latest:
[user@machine .spack]$ cat build.env | grep fort
export F77="gfortran"
export F90="gfortran"
export FC="gfortran"
export SPACK_F77="/nopt/intel/psxe2017u2/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort"
export SPACK_FC="/nopt/intel/psxe2017u2/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort"
```
and
```
Previously working:
[user@machine .spack]$ cat build.env | grep fort
export F77="......../spack/lib/spack/env/intel/ifort"
export F90="gfortran"
export FC="......./spack/lib/spack/env/intel/ifort"
export SPACK_F77="/nopt/intel/psxe2017u2/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort"
export SPACK_FC="/nopt/intel/psxe2017u2/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort"
```

**Comment by jrood-nrel** [comment]
Aha, I think I got it back. It's probably just my fault. It looks like I just needed to adapt some changes to my compiler configuration due to some changes in Spack that I don't have time to research. Closing this until I figure out if I have actually solved it.
