### ISSUE TITLE
Installation issue: qt-base@6 fails to build with gcc@7.5

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#34418]
### Steps to reproduce the issue

```console
$ spack install qt-base@6.3.2
...
```
After doing quick research on the internet, the build error shown below is possibly due to the version of gcc. Hence package file needs to improved by adding conflict statements.

### Error message

<details><summary>Error message</summary><pre>
...
/cache/xuser/spack-stage/spack-stage-qt-base-6.3.2-5gzbyvx2z3blriycfrapdrfimetdkjui/spack-src/src/corelib/text/qlocale_tools.cpp:57:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
...
</pre></details>

### Information on your system

```
$ spack debug report
* **Spack:** 0.20.0.dev0 (d29cb87ecca1c9270eefa6e77ec15b0546fa7458)
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo
```

### Additional information

to be provided later. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
Minimum supported gcc version seems to be gcc@9
https://doc.qt.io/qt-6.4/linux.html
https://doc.qt.io/qt-6.2/linux.html

**Comment by Sinan81** [comment]
qt-base@6.3.2 built just fine with gcc@8.5.0

**Comment by sethrj** [comment]
Note that those numbers are the minimum "supported" not necessarily the minimum "working".

Also, don't check `I have uploaded the build log and environment files` if you didn't upload those files. Adding the full concretization like the template asks for additionally makes it more clear what the dependencies are.

**Comment by Sinan81** [comment]
I was in a hurry. Couldn't submit build log etc. What I did was just building `qt-base@6.3.2` with default options.

**Comment by Sinan81** [comment]
in https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html it's mentioned `charconv` headers appeared since 8.1.
