### PR TITLE
PyTorch: patch breakpad dependency

### LINKED ISSUE #40629: Installation issue: py-torch +breakpad fails to build on RHEL@9.2
### Steps to reproduce the issue

```console
$ spack install py-torch@1.10%gcc=7.5.0 arch=x86_64
```

### Error message

<details><summary>Error message</summary>

<pre>
  >> 3433    /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqssa3/spack-src/third_par
             ty/breakpad/src/client/linux/handler/exception_handler.cc:141:65: error: no matching function for call t
             o 'max(int, long int)'
     3434       static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
     3435                                                                     ^
     3436    In file included from /disk/hpcpm/3vg_spack/0171/opt/spack/linux-rhel9-x86_64/gcc-11.3.1/gcc-7.5.0-ldgnc
             vpwbmnr3kjxaxdzarrvecdyl5ov/include/c++/7.5.0/bits/char_traits.h:39:0,
     3437                     from /disk/hpcpm/3vg_spack/0171/opt/spack/linux-rhel9-x86_64/gcc-11.3.1/gcc-7.5.0-ldgnc
             vpwbmnr3kjxaxdzarrvecdyl5ov/include/c++/7.5.0/string:40,
     3438                     from /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqss
             a3/spack-src/third_party/breakpad/src/client/linux/handler/exception_handler.h:38,
     3439                     from /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqss
             a3/spack-src/third_party/breakpad/src/client/linux/handler/exception_handler.cc:66:

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.17.1
* **Python:** 3.9.16
* **Platform:** linux-rhel9-skylake_avx512
* **Concretizer:** clingo

### Additional information

can provide build out later if necessary.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by adamjstewart**
@Sinan81 can you see if this fixes #40629?

### CODE REVIEW

File: var/spack/repos/builtin/packages/py-torch/package.py [hunk 1]
```diff
@@ -103,7 +103,7 @@ class PyTorch(PythonPackage, CudaPackage, ROCmPackage):
         "breakpad",
         default=True,
         description="Enable breakpad crash dump library",
-        when="@1.9:1.11",
+        when="@1.10:1.11",
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-torch/package.py:106]: Seems like 1.9 can build with external breakpad, but 1.10–1.11 can only build with third party breakpad. And 1.9 has no way of controlling whether or not breakpad gets built. I think it's safer to ignore it on 1.9.

**Comment by Sinan81** [comment]
yep. it fixes the issue. Thanks. Please merge.

**Review by manuelakuhn — APPROVED** [review]
I could reproduce the error and can confirm that this fixes it.
