### ISSUE TITLE
Spack -ddd install results in failed builds

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#25595]
### Steps to reproduce

You can no longer use the triple debug option (for seeing detailed lock debug messages) when installing a package.  

```
$ spack -ddd install libsigsegv
```

This issue was mentioned in #24794 and appears to be related to a bug introduced in #18205.

### Error message

```
==> [2021-08-24-14:59:14.820240, 35507] Error: AttributeError: 'Libsigsegv' object has no attribute 'pid'

/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py:1029, in _setup_pkg_and_run:
       1026        tb_string = traceback.format_exc()
       1027
       1028        # build up some context from the offending package so we can
  >>   1029        # show that, too.
       1030        package_context = get_package_context(tb)
       1031
       1032        logfile = None


Traceback (most recent call last):
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py", line 1013, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1886, in build_process
    installer = BuildProcessInstaller(pkg, install_args)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1718, in __init__
    pid = '{0}: '.format(pkg.pid) if tty.show_pid() else ''
AttributeError: 'Libsigsegv' object has no attribute 'pid'
==> [2021-08-24-14:59:14.820730, 35507] Flagging libsigsegv-2.13-zfnnzbn4waysxe65i2zcahkksulrxfif as failed: AttributeError: 'Libsigsegv' object has no attribute 'pid'
```

### Information on your system

* **Spack:** 0.16.2-4019-80713e234c
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
