### PR TITLE
OpenCV: add new version, simplify package

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 10.15.7 with Python 3.8.8 and Apple Clang 12.0.0.

For some reason, when I try to use this package, I see:
```python
>>> import cv2
>>> cv2.imread()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'imread'
```
I have no idea why this is the case or how to fix it. I'm installing `opencv+python+contrib`.

@bvanessen

### CODE REVIEW

**Comment by tldahlgren** [comment]
Hi Adam.  We had a local user needing to be able to set 'OPENCV_ENABLE_NONFREE' last Friday.  Should such a change be made in a separate PR or is it reasonable to add it here?

**Comment by adamjstewart** [comment]
I can add that tomorrow.

**Comment by tldahlgren** [comment]
> I can add that tomorrow.

In this or a separate PR?

**Comment by adamjstewart** [comment]
Doesn't really matter to me.

**Comment by tldahlgren** [comment]
> Doesn't really matter to me.

IMO a separate PR seems more appropriate.

**Comment by tldahlgren** [comment]
@bvanessen Did you want to comment on this PR?

**Review by bvanessen — APPROVED** [review]
LGTM

**Review by tldahlgren — APPROVED** [review]

**Comment by adamjstewart** [comment]
> For some reason, when I try to use this package, I see:
> ```python
> >>> import cv2
> >>> cv2.imread()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'cv2' has no attribute 'imread'
> ```
> I have no idea why this is the case or how to fix it. I'm installing opencv+python+contrib.

P.S. I needed to install `opencv+python+imgcodecs+imgproc` to get `cv2.imread` working.
