### ISSUE TITLE
ior: build error

### ISSUE THREAD

**Issue by fedepad** [LLNL/spack#3268]
Hi,

running on Scientific Linux, in particular: 
1) Kernel version: 2.6.32-504.30.3.el6.x86_64
2) System gcc: 4.4.7
3) System Python: 2.6.6

When I execute:
`spack install ior +hdf5 +ncmpi`
it fails during make() and this is what I get as screen output:

> ==> Installing ior
> ==> openmpi is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/openmpi-2.0.2-tfjhl2ryjtawk3zv2tvcbalhivsnimsw
> ==> Installing netcdf
> ==> m4 is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/m4-1.4.18-aek2urlgwvkl4svnnkmqdkmb5ocuszo7
> ==> zlib is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/zlib-1.2.11-sjoltdlk2wvrjjqi5nc52lxk6lt6cpwx
> ==> Installing hdf5
> ==> zlib is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/zlib-1.2.11-sjoltdlk2wvrjjqi5nc52lxk6lt6cpwx
> ==> openmpi is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/openmpi-2.0.2-tfjhl2ryjtawk3zv2tvcbalhivsnimsw
> ==> Fetching http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/hdf5-1.10.0-patch1.tar.gz
> ######################################################################## 100,0%
> ==> Staging archive: /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/hdf5-1.10.0-patch1-jvhkxscq7ksvfovxv7y5hrmkueyj47yk/hdf5-1.10.0-patch1.tar.gz
> ==> Created stage in /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/hdf5-1.10.0-patch1-jvhkxscq7ksvfovxv7y5hrmkueyj47yk
> ==> Ran patch() for hdf5
> ==> Building hdf5 [AutotoolsPackage]
> ==> Executing phase : 'autoreconf'
> ==> Executing phase : 'configure'
> ==> Executing phase : 'build'
> ==> Executing phase : 'install'
> ==> Successfully installed hdf5
>   Fetch: 26.02s.  Build: 3m 3.62s.  Total: 3m 29.64s.
> [+] /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/hdf5-1.10.0-patch1-jvhkxscq7ksvfovxv7y5hrmkueyj47yk
> ==> Fetching http://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-4.4.1.1.tar.gz
> ######################################################################## 100,0%
> ==> Staging archive: /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/netcdf-4.4.1.1-pq4boqic7qbgwoyvp26ni5arisfhhdmf/netcdf-4.4.1.1.tar.gz
> ==> Created stage in /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/netcdf-4.4.1.1-pq4boqic7qbgwoyvp26ni5arisfhhdmf
> ==> Ran patch() for netcdf
> ==> Building netcdf [AutotoolsPackage]
> ==> Executing phase : 'autoreconf'
> ==> Executing phase : 'configure'
> ==> Executing phase : 'build'
> ==> Executing phase : 'install'
> ==> Successfully installed netcdf
>   Fetch: 4.26s.  Build: 16.56s.  Total: 20.82s.
> [+] /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/netcdf-4.4.1.1-pq4boqic7qbgwoyvp26ni5arisfhhdmf
> ==> hdf5 is already installed in /gpfs/iowraptest/software_manager/spack_manager/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/hdf5-1.10.0-patch1-jvhkxscq7ksvfovxv7y5hrmkueyj47yk
> ==> Fetching https://github.com/LLNL/ior/archive/3.0.1.tar.gz
> ######################################################################## 100,0%
> ==> Staging archive: /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/ior-3.0.1-cc72c33rnazgxe6pmblmhofq7acny5ct/3.0.1.tar.gz
> ==> Created stage in /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/stage/ior-3.0.1-cc72c33rnazgxe6pmblmhofq7acny5ct
> ==> No patches needed for ior
> ==> Building ior [Package]
> ==> Executing phase : 'install'
> ==> Error: ProcessError: Command exited with status 2:
>     'make' '-j8'
> /gpfs/iowraptest/software_manager/spack_manager/spack/var/spack/repos/builtin/packages/ior/package.py:65, in install:
>      45       def install(self, spec, prefix):
>      46           os.system('./bootstrap')
>      47   
>      48           config_args = [
>      49               'MPICC=%s' % spec['mpi'].prefix.bin + '/mpicc',
>      50               '--prefix=%s' % prefix,
>      51           ]
>      52   
>      53           if '+hdf5' in spec:
>      54               config_args.append('--with-hdf5')
>      55           else:
>      56               config_args.append('--without-hdf5')
>      57   
>      58           if '+ncmpi' in spec:
>      59               config_args.append('--with-ncmpi')
>      60           else:
>      61               config_args.append('--without-ncmpi')
>      62   
>      63           configure(*config_args)
>      64   
>   >> 65           make()
>      66           make('install')

I also attach the log. 
[spack-build-ior.txt](https://github.com/LLNL/spack/files/807296/spack-build-ior.txt)
It appears that pnetcdf.h (Parallel NetCDF) is not found. A quick hack would be to include in the ior ncmpi which shouldn't be the case as the variant +ncmpi should build the parallel version of netcdf because it's netcdf+mpi...
After doing that just to check, the errors on NCMPI disappear but these two errors still remain:

```
aiori-HDF5.c:552: error: too few arguments to function ‘H5Dcreate2’
aiori-HDF5.c:555: error: too few arguments to function ‘H5Dopen2’
```
These errors appear to be related to the fact that IOR is using old HDF5 1.6 style so that should be enabled with:
`"-DH5_USE_16_API`
although I think there should be already a define in the IOR sources and solved by:
https://github.com/LLNL/ior/commit/6a7ddfe60c992121fb9389a1724bb7f7b884f3c5

This problem is mentioned in the following:
http://hdf-forum.184993.n3.nabble.com/Compling-Flash-on-hdf5-1-8-4-patch1-td895571.html

Is there something I'm missing here?

**Comment by fedepad** [comment]
@adamjstewart Thanks for the quick feedback. 
I agree it's a bit confusing for the `parallel-netcdf` instead of `netcdf+mpi`, but ok now that you clarified! 
Regarding HDF5, I agree with you that 1.10 might break packages but I'm almost sure I tried to build with 1.8 too, but since I tried few days ago I do not remember exactly. 
I will try to build it with the 1.8 series and let you know!

**Comment by fedepad** [comment]
I can confirm it happens using HDF5 1.8.18 and 1.8.16 too in my system.

I checked and last week I had modified ior using:
```
depends_on('hdf5@1.8:1.8.18+mpi',   when='+hdf5')
depends_on('netcdf+mpi+parallel-netcdf', when='+ncmpi')
```
since I noticed that `+mpi` and `+parallel-netcdf` are two different variants for netcdf from a superficial view at the relative package.py and the build clearly required parallel-netcdf from the config errors regarding missing `pnetcdf.h`.

**Comment by fedepad** [comment]
I created PR #3276 to address those issues. Check that one for some comments.

**Comment by adamjstewart** [comment]
Closed by #3276.
