### ISSUE TITLE
py-cryptography@35: build fails: failed to get `asn1` as a dependency of...

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#29669]
### Steps to reproduce the issue

`py-cryptography@36.0.1` build is failing using:
* `spack@develop` (6760175289e620fb4af6ff61d3a98116315af8e4 from `Tue Mar 22 17:46:39 2022 +0100`)
* Ubuntu 20.04, x86_64
* GCC 9.3.0
* Python 3.8.12 (spack-installed)

**Concrete spec:** [py-crypto.spec.json.txt](https://github.com/spack/spack/files/8327415/py-crypto.spec.json.txt)

**Concretization**
```
py-cryptography@36.0.1%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
    ^openssl@1.1.1n%gcc@9.3.0~docs~shared certs=system arch=linux-ubuntu20.04-x86_64
        ^perl@5.34.0%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-x86_64
            ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-x86_64
            ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-ubuntu20.04-x86_64
                ^diffutils@3.8%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                    ^libiconv@1.16%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-x86_64
            ^gdbm@1.19%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                ^readline@8.1%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                    ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-x86_64
                        ^pkgconf@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
            ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-x86_64
    ^py-cffi@1.15.0%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^libffi@3.4.2%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^py-pip@21.3.1%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
            ^python@3.8.12%gcc@9.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-x86_64
                ^expat@2.4.6%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-x86_64
                    ^libbsd@0.11.5%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                        ^libmd@1.0.4%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-x86_64
                    ^libxml2@2.9.12%gcc@9.3.0~python arch=linux-ubuntu20.04-x86_64
                        ^xz@5.2.5%gcc@9.3.0+pic libs=shared,static arch=linux-ubuntu20.04-x86_64
                    ^tar@1.34%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                ^sqlite@3.37.2%gcc@9.3.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-x86_64
                ^util-linux-uuid@2.37.4%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^py-pycparser@2.20%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
            ^py-setuptools@59.4.0%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                ^py-wheel@0.37.0%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
    ^py-setuptools-rust@0.12.1%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^py-semantic-version@2.8.2%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^py-setuptools-scm@6.3.2%gcc@9.3.0+toml arch=linux-ubuntu20.04-x86_64
            ^py-packaging@21.3%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
                ^py-pyparsing@3.0.6%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
            ^py-tomli@1.2.2%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^py-toml@0.10.2%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
        ^rust@1.58.1%gcc@9.3.0+analysis+clippy~rls+rustfmt+src extra_targets=none arch=linux-ubuntu20.04-x86_64
            ^cmake@3.22.3%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-x86_64
            ^gmake@4.3%gcc@9.3.0~guile+nls arch=linux-ubuntu20.04-x86_64
                ^texinfo@6.5%gcc@9.3.0 patches=12f6edb,1732115 arch=linux-ubuntu20.04-x86_64
            ^libgit2@1.1.1%gcc@9.3.0~curl~ipo+mmap+ssh build_type=RelWithDebInfo https=system arch=linux-ubuntu20.04-x86_64
                ^libssh2@1.10.0%gcc@9.3.0~ipo+shared build_type=RelWithDebInfo crypto=openssl arch=linux-ubuntu20.04-x86_64
            ^ninja@1.10.2%gcc@9.3.0 arch=linux-ubuntu20.04-x86_64
```

Quickly reproduced using cached dependency binaries and Docker container image:
* Docker image = `ecpe4s/ubuntu20.04-runner-x86_64:2022-02-01`
* Spack mirror = `https://cache.e4s.io`

**Error**
```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it
$> spack install --cache-only --include-build-deps --only dependencies -f ./py-crypto.spec.json

$> spack install --no-cache --only package -f ./py-crypto.spec.json
...
==> Installing py-cryptography-36.0.1-n7oacdji4zhvwx3elp244uqynullvzr2
==> Fetching https://mirror.spack.io/_source-cache/archive/53/53e5c1dc3d7a953de055d77bef2ff607ceef7a2aac0353b5d630ab67f7423638.tar.gz
==> No patches needed for py-cryptography
==> py-cryptography: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/python-3.8.12-cmxef4rrvuwunj44ad7lp3mc7ss5uvfu/bin/python3.8' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/py-cryptography-36.0.1-n7oacdji4zhvwx3elp244uqynullvzr2' '.'
See build log for details:
  /tmp/root/spack-stage/spack-stage-py-cryptography-36.0.1-n7oacdji4zhvwx3elp244uqynullvzr2/spack-build-out.txt
```

Excerpt from full `spack-build-out.txt` (full output attached at end of issue)
```
...
  running build_rust
      Updating crates.io index
  error: failed to get `asn1` as a dependency of package `cryptography-rust v0.1.0 (/tmp/root/spack-stage/spack-stage-py-cryptography-36.0.1-n7oacdji4zhvwx3elp244uqynullvzr2/spack-src/src/rust)`

  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`

  Caused by:
    invalid version 0 on git_proxy_options; class=Invalid (3)

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust

      Python: 3.8.12
      platform: Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.2.5
      pip: 21.3.1
      setuptools: 59.4.0
      setuptools_rust: 0.12.1
      =============================DEBUG ASSISTANCE=============================
...
```

### Error message

<details><summary>Error message</summary><pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (6760175289e620fb4af6ff61d3a98116315af8e4)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8327410/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8327411/spack-build-out.txt)

@adamjstewart @manuelakuhn 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I just installed py-cryptography 36.0.1 with Python 3.9.10 and Apple Clang 12.0.0 on macOS 10.15.7 without any issues. Does this system have internet access? Are there any special git proxies or firewalls that could cause this problem?

**Comment by eugeneswalker** [comment]
> I just installed py-cryptography 36.0.1 with Python 3.9.10 and Apple Clang 12.0.0 on macOS 10.15.7 without any issues. Does this system have internet access? Are there any special git proxies or firewalls that could cause this problem?

Yes, internet access is fine, I was able to install hundreds of other packages (both python and non-python with Spack). Also no git proxies and no firewalls that I'm aware of that would impact this. I've installed hundreds of other python packages  just fine in the same container, same system, same Spack instance. Obviously something is not right and it may very well be something on my end that I haven't figured out.

I get a similar error with `py-cryptography@3.4.8`:
```
      Updating crates.io index
  error: failed to get `pyo3` as a dependency of package `cryptography-rust v0.1.0 (/tmp/root/spack-stage/spack-stage-py-cryptography-3.4.8-4ztz25m6gyabzm3axsjlg2gyjo6u2yck/spack-src/src/rust)`

  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`

  Caused by:
    invalid version 0 on git_proxy_options; class=Invalid (3)

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================
```

**Comment by adamjstewart** [comment]
@AndrewGaspar has done a lot of Spack + Rust work and may be able to help

**Comment by srekolam** [comment]
i also observed the above issue when trying to do spack install py-tensorflow. if there is workaround it would help

**Comment by eugeneswalker** [comment]
At least in my case, where I'm working with the latest Ubuntu 20.04 Docker container image, the issue seems to be with Cargo's internal git library. I was able to work around it by setting `CARGO_NET_GIT_FETCH_WITH_CLI=true` in the `py-cryptography` build environment, and then adding an explicit build dependency on `git`.

See https://community.home-assistant.io/t/error-failed-building-wheel-for-cryptography/352020/14
And https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

I'm submitting a WIP PR that resolves the issue for me. The only question I have is whether/how we should restrict this workaround to Ubuntu 20.04?
