### ISSUE TITLE
Installation issue: motif

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#25794]
### Steps to reproduce the issue

```console
spack install motif
```

### Information on your system

Ubuntu 20.04 LTS (x86_64)

* **Spack:** 0.16.2-4144-536121cadf
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

### Additional information

cc main authors of the package: @briedel @awacha 

cc original reporter: @WeiqunZhang 

Linker error in motif build:
```
     3903    libtool: link: /home/axel/src/spack/lib/spack/env/gcc/gcc -g -O2 -Wall -g -fno-strict-a
             liasing -Wno-unused -Wno-comment -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-sky
             lake/gcc-10.2.0/libxft-2.3.2-nuuvhnzngtgz7s2vdf2ixyhenvmiy7qf/include -I/home/axel/src/
             spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/xproto-7.0.31-yyo45uhkk7ch6zvamphv
             5rqwgj26wxbr/include -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.
             2.0/libxrender-0.9.10-imrlx4fnuyzvsn7fx6wvlzm7czkd7uxx/include -I/home/axel/src/spack/o
             pt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/renderproto-0.11.1-djhcvvzwy5zoivcwgr7y62
             erldjk663j/include -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.
             0/libx11-1.7.0-jucmd7qpodrjnctzb6ypsqxoqaps46nl/include -I/home/axel/src/spack/opt/spac
             k/linux-ubuntu20.04-skylake/gcc-10.2.0/kbproto-1.0.7-v6kpza23webuf7rgqfzicdbaetcdgazi/i
             nclude -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/libxcb-1.1
             4-fxydy3ldygwt62nh7fi6rtcvteqfzrgw/include -I/home/axel/src/spack/opt/spack/linux-ubunt
             u20.04-skylake/gcc-10.2.0/libxau-1.0.8-wv2mjdy5lj37m3n5verrvesyooewhwrd/include -I/home
             /axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/libxdmcp-1.1.2-tt6cnuxna
             rpibaa23g3ft7sbu7w5ms3z/include -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skyl
             ake/gcc-10.2.0/fontconfig-2.13.93-kf3f432efaqjpvsjjoi25asd4eyabr3f/include -I/home/axel
             /src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/freetype-2.11.0-bsncivagqvyzg
             ltvlzepwhabocx27gya/include/freetype2 -I/home/axel/src/spack/opt/spack/linux-ubuntu20.0
             4-skylake/gcc-10.2.0/zlib-1.2.11-ic4fxjxrxsg3kfkhv33o7crpwbcrivdx/include -I/home/axel/
             src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/libpng-1.6.37-uo6zzvy3q34yiqbh
             77gzdpqty4dvcziy/include/libpng16 -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-sk
             ylake/gcc-10.2.0/libxml2-2.9.12-bbzpoynrstvz5keau2o5clwjbtb3sjo3/include/libxml2 -I/hom
             e/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/libiconv-1.16-xkkjjzazq
             oxfigndvrk3wgpub3cba2os/include -I/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skyl
             ake/gcc-10.2.0/xbitmaps-1.1.1-2jo4l4uqemkhizqjaq3bqnf5xs7mg5hg/include -o .libs/simpleD
             emo simpleDemo.o  ../../../../lib/Xm/.libs/libXm.so -L/home/axel/src/spack/opt/spack/li
             nux-ubuntu20.04-skylake/gcc-10.2.0/fontconfig-2.13.93-kf3f432efaqjpvsjjoi25asd4eyabr3f/
             lib -L/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/freetype-2.11
             .0-bsncivagqvyzgltvlzepwhabocx27gya/lib -L/home/axel/src/spack/opt/spack/linux-ubuntu20
             .04-skylake/gcc-10.2.0/libxft-2.3.2-nuuvhnzngtgz7s2vdf2ixyhenvmiy7qf/lib -lXt -lXext -l
             X11 ../../../lib/Exm/libExm.a -lfontconfig -lfreetype -lXft -ljpeg -lpng -Wl,-rpath -Wl
             ,/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/motif-2.3.8-wbz3cf
             bbpoa5owyf5imcddbmnyyuwc7i/lib
  >> 3904    /usr/bin/ld: ../../../../lib/Xm/.libs/libXm.so: undefined reference to symbol 'XFillArc
             '
  >> 3905    /usr/bin/ld: /home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.2.0/libx11
             -1.7.0-jucmd7qpodrjnctzb6ypsqxoqaps46nl/lib/libX11.so: error adding symbols: DSO missin
             g from command line
  >> 3906    collect2: error: ld returned 1 exit status
```

* [spack-build-env.txt](https://github.com/spack/spack/files/7109332/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/7109333/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ax3l** [comment]
I found a patch in Debian, seems we need to manually link X11 in or so:
https://bugs.launchpad.net/ubuntu/+source/openmotif/+bug/705294

**Comment by ax3l** [comment]
cannot reproduce anymore on my system, works on Ubuntu 20.04 LTS.
