### ISSUE TITLE
Installation issue: unzip %oneapi

### ISSUE THREAD

**Issue by Thomas-Ulrich** [LLNL/spack#40864]
### Steps to reproduce the issue

```console
(base) ulrich@heisenbug:~$ spack spec -I unzip %oneapi
Input spec
--------------------------------
 -   unzip%oneapi

Concretized
--------------------------------
 -   unzip@6.0%oneapi@2022.2.0 build_system=makefile arch=linux-debian11-zen2
[+]      ^gmake@4.4.1%oneapi@2022.2.0~guile build_system=autotools arch=linux-debian11-zen2

```

### Error message

<details><summary>==> Error: ProcessError: Command exited with status 2:
    'make' '-j40' '-f' 'unix/Makefile' 'LOC="-DLARGE_FILE_SUPPORT"' 'generic'

  >> 1114    error: extern struct tm *gmtime (const time_t *__timer) __THROW;expected ';' after struct

</summary>
(base) ulrich@heisenbug:~$ spack install -j 40 unzip %oneapi
[+] /import/exception-dump/ulrich/myLibs/spack-packages/linux-debian11-zen2/oneapi-2022.2.0/gmake-4.4.1-367t3wirbrvpk2kvss33dye7zqgv3k4r
==> Installing unzip-6.0-awr6in45omidrpubaslbk64ebno22nf4 [2/2]
==> No binary for unzip-6.0-awr6in45omidrpubaslbk64ebno22nf4 found: installing from source
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Using cached archive: /import/exception-dump/ulrich/spack/var/spack/cache/_source-cache/archive/03/036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37.tar.gz
==> No patches needed for unzip
==> unzip: Executing phase: 'edit'
==> unzip: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j40' '-f' 'unix/Makefile' 'LOC="-DLARGE_FILE_SUPPORT"' 'generic'

19 errors found in build log:
     540     extract.c:755crypt.c::44453:: 5warning: :format string is not a string literal (potentially insecure) [-Wformat-security]
     541     warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     542     int decrypt(__G__ passwrd)
     543         ^
     544             Info(slide, 0x401, ((char *)slide, LoadFarString(EndSigMsg)));
     545                                                ^             ~~~~~~~~~
  >> 546     ./unzpriv.h:1009:37: funzip.cnote: :expanded from macro 'LoadFarString'221
     547     :13: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     548     #    define LoadFarString(x)        (char *)(x)
     549                                         ^        ~
     550     ./unzpriv.hstatic void err(n, m):
     551     2708            ^:
     552     61:In file included from  note: globals.cexpanded from macro 'Info':

     ...

     1108    typedef struct __dirstream DIR;
     1109                               ^
     1110    /usr/include/time.h:#    define LoadFarString(x)        (char *)(x)119
     1111    :                                    ^19
     1112    : ./unzpriv.hnote: :conflicting prototype is hereunix/unix.c2708
     1113    ::61136:: 2note: :expanded from macro 'Info'
  >> 1114    error: extern struct tm *gmtime (const time_t *__timer) __THROW;expected ';' after struct
     1115    
     1116                      ^
     1117    } DIR
     1118     ^
     1119           (*G.message)((zvoid *)&G, (uch *)(buf), (ulg)sprintf sprf_arg, (flag))
     1120                                                                ^

     ...

     1131    fileio.c:1571:12: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1132    int UZ_EXP UzpPassword (pG, rcnt, pwbuf, size, zfn, efn)
     1133               ^
     1134    fileio.c:1632:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1135    void handler(signal)   /* upon interrupt, turn on echo and exit cleanly */
     1136         ^
  >> 1137    unix/unix.c:137:4: error: expected ';' after top level declarator
     1138    DIR *opendir OF((ZCONST char *dirspec));
     1139       ^
     1140       ;
  >> 1141    unix/unix.c:138:6: error: conflicting types for 'closedir'
     1142    void closedir OF((DIR *dirp));
     1143         ^
     1144    /usr/include/dirent.h:149:12: note: previous declaration is here
     1145    extern int closedir (DIR *__dirp) __nonnull ((1));
     1146               ^
  >> 1147    unix/unix.c:141:6: error: expected identifier
     1148    DIR *opendir(dirspec)
     1149         ^
     1150    unix/unix.c:130:34: note: expanded from macro 'opendir'
     1151    #define opendir(path) fopen(path,"r")
     1152                                     ^
     1153    unix/unix.c:141:6: warning: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a previous declarat
             ion [-Wdeprecated-non-prototype]
     1154    unix/unix.c:130:23: note: expanded from macro 'opendir'
     1155    #define opendir(path) fopen(path,"r")
     1156                          ^
  >> 1157    unix/unix.c:141:6: error: conflicting types for 'fopen'
     1158    unix/unix.c:130:23: note: expanded from macro 'opendir'
     1159    #define opendir(path) fopen(path,"r")
     1160                          ^
     1161    /usr/include/stdio.h:257:26: note: previous declaration is here
     1162    extern FILE *__REDIRECT (fopen, (const char *__restrict __filename,
     1163                             ^
  >> 1164    unix/unix.c:141:22: error: expected ';' after top level declarator
     1165    DIR *opendir(dirspec)
     1166                         ^
     1167                         ;fileio.c
     1168    :1696:8: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
  >> 1169    unix/unix.c:143:1: error: time_t dos_to_unix_time(dosdatetime)expected identifier or '('
     1170    
     1171           ^{
     1172    
     1173    ^
     1174    unix/unix.c:155:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1175    void closedir(dirp)
     1176         ^
     1177    unix/unix.c:131:23: note: expanded from macro 'closedir'
     1178    #define closedir(dir) fclose(dir)
     1179                          ^
  >> 1180    unix/unix.c:155:6: error: conflicting types for 'fclose'
     1181    unix/unix.c:131:23: note: expanded from macro 'closedir'
     1182    #define closedir(dir) fclose(dir)
     1183                          ^
     1184    /usr/include/stdio.h:213:12: note: previous declaration is here
     1185    extern int fclose (FILE *__stream);
     1186               ^
  >> 1187    unix/unix.c:158:16: error: incomplete definition of type 'struct __dirstream'
     1188        fclose(dirp->dirhandle);
     1189               ~~~~^
     1190    /usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
     1191    typedef struct __dirstream DIR;
     1192                   ^
     1193    unix/unix.c:155:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]

     ...

     1206    /usr/include/dirent.h:166:6: note: declared 'nonnull' here
     1207         __nonnull ((1));
     1208         ^
     1209    /usr/include/x86_64-linux-gnu/sys/cdefs.h:293:44: note: expanded from macro '__nonnull'
     1210    # define __nonnull(params) __attribute__ ((__nonnull__ params))
     1211                                               ^
  >> 1212    unix/unix.c:174:25: error: incomplete definition of type 'struct __dirstream'
     1213            if (fread(&(dirp->entry), sizeof (struct dirent), 1,
     1214                        ~~~~^
     1215    /usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
     1216    typedef struct __dirstream DIR;
     1217                   ^
  >> 1218    unix/unix.c:175:23: error: incomplete definition of type 'struct __dirstream'
     1219                      dirp->dirhandle) == 0)
     1220                      ~~~~^
     1221    /usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
     1222    typedef struct __dirstream DIR;
     1223                   ^
  >> 1224    unix/unix.c:177:23: error: incomplete definition of type 'struct __dirstream'
     1225            else if ((dirp->entry).d_ino)
     1226                      ~~~~^
     1227    /usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
     1228    typedef struct __dirstream DIR;
     1229                   ^
  >> 1230    unix/unix.c:178:26: error: incomplete definition of type 'struct __dirstream'
     1231                return &(dirp->entry);
     1232                         ~~~~^
     1233    /usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
     1234    typedef struct __dirstream DIR;
     1235                   ^
     1236    unix/unix.c:189:7: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]

     ...

     1295    In file included from unix/unix.c:31:
     1296    In file included from ./unzip.h:718:
     1297    In file included from ./unzpriv.h:561:
     1298    ./unix/unxcfg.h:120:15: warning: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a previous dec
             laration [-Wdeprecated-non-prototype]
     1299       struct tm *gmtime(), *localtime();
     1300                  ^
  >> 1301    /usr/include/time.h:119:19: unix/unix.cnote: :conflicting prototype is here1324:
     1302    5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1303    int defer_dir_attribs(__G__ pd)
     1304        ^
     1305    extern struct tm *gmtime (const time_t *__timer) __THROW;
     1306                      ^
     1307    In file included from unix/unix.c:31:

     ...

     1349     error./unzpriv.hs:In file included from 1009 generated./unzip.h:.
     1350    37::718 note: :
     1351    expanded from macro 'LoadFarString'
     1352    In file included from ./unzpriv.h:561fileio.c#    define LoadFarString(x)        (char *)(x):
     1353    
     1354    :                                    ^        ~2718
  >> 1355    ./unix/unxcfg.h:7:./unzpriv.h:120: :warning: 270815:a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]:61
     1356     :warning:  note: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a previous declaration [-Wdep
             recated-non-prototype]char *plastchar(ptr, len)expanded from macro 'Info'
     1357    
     1358    
     1359          ^
     1360           (*G.message)((zvoid *)&G, (uch *)(buf), (ulg)sprintf sprf_arg, (flag))
     1361                                                                ^~~~~~~~

     ...

     1464    process.c:1219:12: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1465    static int find_ecrec64(__G__ searchlen)         /* return PK-class error */
     1466               ^
     1467    inflate.c:932:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1468    int inflate_codes(__G__ tl, td, bl, bd)
     1469        ^
  >> 1470    make[1]: *** [unix/Makefile:403: unix.o] Error 1
     1471    make[1]: *** Waiting for unfinished jobs....
     1472    process.c:1219:12: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1473    process.c:1445:12: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1474    static int find_ecrec(__G__ searchlen)          /* return PK-class error */
     1475               ^
     1476    zipinfo.c:987:12: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]

     ...

     1616    unix/unix.c:1324:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1617    int defer_dir_attribs(__G__ pd)
     1618        ^
     1619    unix/unix.c:1346:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1620    int set_direc_attribs(__G__ d)
     1621        ^
  >> 1622    ttyio.c:306:6: 7warning:  warninga function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]s
     1623     generated.
     1624    void Echoff(__G__ f)
     1625         ^
     1626    4 warnings generated.
     1627    ttyio.c:602:7: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
     1628    char *getp(__G__ m, p, n)

     ...

     1644    20 warnings generated.
     1645    11 warnings generated.
     1646    8 warnings generated.
     1647    8 warnings generated.
     1648    8 warnings generated.
     1649    make[1]: Leaving directory '/tmp/ulrich/spack-stage/spack-stage-unzip-6.0-awr6in45omidrpubaslbk64ebno22nf4/spack-src'
  >> 1650    make: *** [unix/Makefile:544: generic] Error 2

See build log for details:
  /tmp/ulrich/spack-stage/spack-stage-unzip-6.0-awr6in45omidrpubaslbk64ebno22nf4/spack-build-out.txt
</details>

### Information on your system

* **Spack:** 0.21.0.dev0 (f0eda6b64968b8e8356d2d70165335549a92e723)
* **Python:** 3.9.2
* **Platform:** linux-debian11-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/13250760/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/13250761/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by pbisbal1** [comment]
Any progress on this? I'm running into the same issue. No maintainers are listed for this package, so we can't tag them. My spack-build-out.txt file for this is attached. 

[spack-build-out.txt](https://github.com/spack/spack/files/13719187/spack-build-out.txt)

**Comment by pbisbal1** [comment]
My spec for unzip: 

```
# spack spec unzip%oneapi
Input spec
--------------------------------
 -   unzip%oneapi

Concretized
--------------------------------
 -   unzip@6.0%oneapi@2023.2.0 build_system=makefile arch=linux-rhel9-zen2
[e]      ^gmake@4.3%oneapi@2023.2.0~guile build_system=generic patches=599f134 arch=linux-rhel9-zen2
```

**Comment by Chrismarsh** [comment]
I'm seeing this as the error
```
  >> 836     unix/unix.c:132:14: error: typedef redefinition with different types ('FILE' (aka 'struct _IO_FILE') vs 'struct __dirstream')
     837     typedef FILE DIR;
     838                  ^
     839     /usr/include/dirent.h:127:28: note: previous definition is here
     840     typedef struct __dirstream DIR;
```
I've found the spec that has unzip as a dependency and added `^unzip%gcc` however this is not satisfying. I looked at unix.c though and it is not clear to me how to fix this other than renaming throughout the files

**Comment by becker33** [comment]
It looks like the problem is that `NO_DIR` is getting defined even though `DIR` is also defined. Looking at the `#ifdef` block enclosing this code.

**Comment by becker33** [comment]
The issue may well be at line 420 of the configure script, where it determines whether the `DIR` utilities are available through the compiler.

**Comment by Chrismarsh** [comment]
I reproduced the configure test with `icc`:
```
$ cat conftest.c 
int main() { return closedir(opendir(".")); }
``` 
with `icc`
```
$ icc -o out conftest.c 
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
conftest.c(1): warning #266: function "closedir" declared implicitly
  int main() { return closedir(opendir(".")); }
                      ^

conftest.c(1): warning #266: function "opendir" declared implicitly
  int main() { return closedir(opendir(".")); }
                               ^

$ echo $?
0
```

The problem is when using oneapi, `cc` is now defined to be `icx`:
```

[chm003@ppp5login-002 code-tmp]$ icx -o out conftest.c 
conftest.c:1:21: error: call to undeclared function 'closedir'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
int main() { return closedir(opendir(".")); }
                    ^
conftest.c:1:30: error: call to undeclared function 'opendir'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
int main() { return closedir(opendir(".")); }
                             ^
2 errors generated.
```

Suppressing this warning results in a pass

```
 icx -o out conftest.c -Wno-implicit-function-declaration
```

Since `icx` gives a >0 return code, the configure script then tries all those libraries, which don't work on my system. And thus concludes, `NO_DIR`

**Comment by Chrismarsh** [comment]
I have a PR, it works on oneapi@2023.2 and gcc@8.3. Please let me know what you think

**Comment by Chrismarsh** [comment]
The PR was merged it and so this can be closed

**Comment by becker33** [comment]
@Chrismarsh if you put `Fixes #40864` as a line in the PR description, it will close this automatically when the PR is merged.

Closed by #42593
