### PR TITLE
hdf5: add 1.10.8 as preferred version

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Review by byrnHDF — DISMISSED** [review]

**Review by hyoklee — DISMISSED** [review]

**Review by chuckatkins — DISMISSED** [review]

**Comment by scheibelp** [comment]
It looks like our CI, which builds a package that depends on `hdf5`, ends up failing:

```
     H5FD_silo_get_eof,                  /*get_eof  */
1649     ^~~~~~~~~~~~~~~~~
1650H5FDsilo.c:523:5: note: (near initialization for 'H5FD_silo_g.get_eof')
1651H5FDsilo.c: In function 'file_write':
1652H5FDsilo.c:259:1: error: expected ';' before '}' token
1653 }
1654 ^
```

I think if you add a constraint to silo like `depends_on(hdf5@:1.10.7, when=@:4.11+hdf5)` it will fix this issue (if you do that you can also remove `depends_on('hdf5@:1.10', when='@:4.10.2+hdf5')`).

**Comment by bernhardkaindl** [comment]
@lrknox ping: https://github.com/spack/spack/pull/27613#issuecomment-978224582

**Comment by markcmiller86** [comment]
> It looks like our CI, which builds a package that depends on `hdf5`, ends up failing:
> 
> ```
>      H5FD_silo_get_eof,                  /*get_eof  */
> 1649     ^~~~~~~~~~~~~~~~~
> 1650H5FDsilo.c:523:5: note: (near initialization for 'H5FD_silo_g.get_eof')
> 1651H5FDsilo.c: In function 'file_write':
> 1652H5FDsilo.c:259:1: error: expected ';' before '}' token
> 1653 }
> 1654 ^
> ```

I believe this is related to change in semicolon termination requirements for `H5E_PUSH_HELPER` macro in HDF5 between 1.10.7 and 1.10.8. I am working on a patch.

**Comment by markcmiller86** [comment]
> I believe this is related to change in semicolon termination requirements for `H5E_PUSH_HELPER` macro in HDF5 between 1.10.7 and 1.10.8. I am working on a patch.

Apologies, that is `H5Epush_ret` semi-colon termination in HDF5. The `HELPER` macro is a Silo wrapper on top of it.

**Comment by markcmiller86** [comment]
Ok, adding a possible patch for Silo 4.10.3 to fix this. This patch ensures Silo's 4.10 series block-oriented virtual file driver builds correctly with HDF5 1.10 series and 1.8 series of HDF5.

[H5FDsilo.c.patch.gz](https://github.com/spack/spack/files/7665876/H5FDsilo.c.patch.gz)

Silo 4.11 builds fine with HDF5 1.8 and 1.10 and 1.12 series.

**Comment by scheibelp** [comment]
@spackbot re-run pipeline

**Comment by scheibelp** [comment]
Thanks @markcmiller86

@lrknox note that patch will have to be added here, to `silo`, or introduced in a separate PR for this to pass CI. In the meantime, you can also add a constraint to `silo` like `depends_on(hdf5@:1.8, when=@:4.10)`

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by lrknox** [comment]
@markcmiller86 thank you for posting the patch.  I.ve been testing various HDF5 versions with the patch or modified versions as required, along with a suggestion from @chuckatkins to add a conflicts statement, <conflicts('hdf5@1.10.8:', when="@:4.10.2")>, since the 4.11 version is available, thinking that with this statement, spack would switch to the higher silo version, eliminating the need for a patch.

From these testing results, my conclusion is that 3 slightly different patches would be required, reduced to 2 with the conflicts statement:
     Silo 4.10.2 (default) builds with HDF5 versions 1.8 and 1.10 <= 1.10.7 needs patches for 1.10.8 – 1.10.x, 1.12, 1.13
     Silo 4.11 builds with HDF5 versions 1.8 and 1.10 <= 1.10.7, 1.12.0, needs a (subset) patch for 1.10.8 – 1.10.x and 1.12.1-1.12.x, 
     and augmented (subset) patch for 1.13

3 of 8 chunks in your patch file have already been updated in silo 4.11; removing those chunks and patching the other 5 allows silo 4.11 to build with HDF5 1.10.8 and 1.12.1, and should be expected to work for subsequent 1.10.x and 1.12.x versions.

There is an added member of H5FD_class_t, "H5FD_class_value_t value" in HDF5 1.13.0, which will require an addition to H5FD_silo_g.  This may be the only addition, or there may be others.  I'm checking the requirements for this value, and will try again after that.

This last patch would be part of a separate PR to add another version HDF5 1.13.0.  For this PR I will need to add either the conflicts statement and a patch for silo@4.11 with HDF5 1.10 >= 1.10.8 and 1.12 >+ 1.12.1 or without the conflicts statement, that same patch plus the original patch for silo@4.2.10.

Having said all that and reread the comments with the original patch, I'm not sure if you intended to add patch files to spack or update to a new silo version.  If it was the latter, then the updated silo 4.10.3 should work with HDF5 1.8 and 1.10, silo 4.11 with updates for the 1.12 series, and would you create a new version for HDF5 1.13,0?

I haven't tested silo 4.11 updated with the patch changes with HDF5 1.8 and 1.10 < 1.10.8.  I'll do that while waiting for comments on the above.

**Comment by markcmiller86** [comment]
> Silo 4.10.2 (default) builds with HDF5 versions 1.8 and 1.10 <= 1.10.7 needs patches for 1.10.8 – 1.10.x, 1.12, 1.13

Whoops. Sorry, I was working with Silo 4.10.3 though that particular file I am sure didn't change between those two versions.

Hmmm..I posted the patch here in hopes that it might help to address your immediate issue with getting this PR in a working state. No obligation to use anything I've given you here. If easiest to simply pin down the build by adding version constraints, I think that is a fine solution for now.

I expect to get around to updating Spack's Silo package but not until soon after the holidays. And, I will have a made patch release to Silo by then, 4.11.1. So, I think you should opt for path of least resistance to get this PR completed. Does that make sense?

**Comment by lrknox** [comment]
Yes, thank you!

**Comment by lrknox** [comment]
Two of the CI test pipelines failed with http errors:  urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable. 

@spackbot re-run pipeline

**Review by hyoklee — DISMISSED** [review]

**Review by brtnfld — DISMISSED** [review]

File: var/spack/repos/builtin/packages/silo/package.py [hunk 1]
```diff
@@ -55,7 +54,9 @@ class Silo(AutotoolsPackage):
 
     patch('remove-mpiposix.patch', when='@4.8:4.10.2')
     patch('H5FD_class_t-terminate.patch', when='@:4.10.2 ^hdf5@1.10.0:')
+    patch('H5EPR_SEMI_COLON.patch', when='@:4.11 ^hdf5@1.10.8:1.11,1.12.1:1.13')
```
Comment (scheibelp) [inline var/spack/repos/builtin/packages/silo/package.py]: As written, this appears carefully constructed to avoid `@1.12.0`, but I don't see such a version in the `hdf5` package, so if that is OK then this could be simplified to:

`when='@:4.11 ^hdf5@1.10.8:1.13')`

I could be missing something though: this seems related to https://github.com/spack/spack/pull/27613#issuecomment-990364806 but I should say that the `when` statement as of now doesn't specify either of the ranges described there:

> Silo 4.10.2 (default) builds with HDF5 versions 1.8 and 1.10 <= 1.10.7 needs patches for 1.10.8 – 1.10.x, 1.12, 1.13
> Silo 4.11 builds with HDF5 versions 1.8 and 1.10 <= 1.10.7, 1.12.0, needs a (subset) patch for 1.10.8 – 1.10.x and 1.12.1-1.12.x, and augmented (subset) patch for 1.13

For example, `hdf5@1.10.8:1.11` means "any version between 1.10.8 and 1.11.x for any x, inclusively" (so effectively, any version before 1.12.0). If you want to apply one of the bounds exactly as described, I can translate that into a version range for you. IMO it might make sense to constrain what you are willing to build though and create a simpler `when` statement (in other words, you can constrain the when to match what you are building with, and you don't need to run multiple builds to find the exact conditions where the patch needs to be applied).

**Review by scheibelp — CHANGES_REQUESTED** [review]
I'm concerned that the `when=` constraints for `H5EPR_SEMI_COLON.patch` don't match the intended cases where the patch is applied. I think fixing that is a simple matter of adjusting the version ranges in the `patch(` directive.

File: var/spack/repos/builtin/packages/silo/package.py (hunk 1 above)
Comment (lrknox) [reply var/spack/repos/builtin/packages/silo/package.py]: > As written, this appears carefully constructed to avoid `@1.12.0`, but I don't see such a version in the `hdf5` package, so if that is OK then this could be simplified to:
> 

line 40 of hdf5/package.py:
      version('1.12.0', sha256='a62dcb276658cb78e6795dd29bf926ed7a9bc4edf6e77025cd2c689a8f97c17a')

> `when='@:4.11 ^hdf5@1.10.8:1.13')`
> 
> I could be missing something though: this seems related to [#27613 (comment)](https://github.com/spack/spack/pull/27613#issuecomment-990364806) but I should say that the `when` statement as of now doesn't specify either of the ranges described there:
> 
> > Silo 4.10.2 (default) builds with HDF5 versions 1.8 and 1.10 <= 1.10.7 needs patches for 1.10.8 – 1.10.x, 1.12, 1.13
> > Silo 4.11 builds with HDF5 versions 1.8 and 1.10 <= 1.10.7, 1.12.0, needs a (subset) patch for 1.10.8 – 1.10.x and 1.12.1-1.12.x, and augmented (subset) patch for 1.13
> 
> For example, `hdf5@1.10.8:1.11` means "any version between 1.10.8 and 1.11.x for any x, inclusively" (so effectively, any version before 1.12.0). If you want to apply one of the bounds exactly as described, I can translate that into a version range for you. IMO it might make sense to constrain what you are willing to build though and create a simpler `when` statement (in other words, you can constrain the when to match what you are building with, and you don't need to run multiple builds to find the exact conditions where the patch needs to be applied).

I'm not following all of this, but the silo patch is needed for silo@4.11 with current hdf5 versions 1.10.8 and 1.12.1.  The patch is not needed for silo@4.11 with hdf5 1.8, hdf51.10.0 - 1.10.7, or hdf5 1.12.0.  The hdf5 change that necessitates the H5EPR_SEMI_COLON.patch in silo was introduced in versions 1.10.8 and 1.12.1 after version 1.12.0 had been released.  

The statement in silo/package.py "conflicts('hdf5@1.10.8:', when="@:4.10.2") results in spack choosing silo@4.11 instead of 4.10.2 (the default version) for hdf5 versions 1.10.8 and above

Prior to the experimental 1.13.0 release, there were no 1.x.y releases of hdf5 where x was an odd number.  There will not be any 1.11.x releases. The patch will be needed for any future 1.10.x or 1.12.x releases, which are both planned.  hdf5 1.13.0 has changes that will require either a different patch or a new silo release version, which Mark Miller said will wait until after the holidays.

I will happily consider and try any translated or simplified when statement that you propose.  The H5EPR_SEMI_COLON.patch is needed for silo@4.11 hdf5@1.10.x where x >=8 and hdf51.12.x where x >= 1.

Comment (scheibelp) [reply var/spack/repos/builtin/packages/silo/package.py]: > The patch will be needed for any future 1.10.x or 1.12.x releases, which are both planned. hdf5 1.13.0 has changes that will require either a different patch or a new silo release 

Thanks for the explanation! In that case I think the statement will need one minor change, from 

```
when='@:4.11 ^hdf5@1.10.8:1.11,1.12.1:1.13'
```

to

```
when='@:4.11 ^hdf5@1.10.8:1.11,1.12.1:1.12'
```

Only the last character changed, but FYI upper bounds are not exclusive, and in our syntax for a version range, `x.y` matches any `x.y.z` (so currently this applies for all hdf5 1.13.z versions). You might find it more straightforward to write:

```
when='@:4.11 ^hdf5@1.10.8:1.11,1.12.1:1.12.999'
```

Comment (lrknox) [reply var/spack/repos/builtin/packages/silo/package.py]: Thank you! @scheibelp 
I will update the statement with a comment regarding the intent as follows:
    # H5EPR_SEMI_COLON.patch should be applied only to silo@4.11 when building
    # with hdf5@1.10.8 or later 1.10 or with hdf5@1.12.1 or later 1.12
    patch('H5EPR_SEMI_COLON.patch', when='@:4.11 ^hdf5@1.10.8:1.10,1.12.1:1.12')
I'll go with 1.10 and 1.12 for the upper bounds to have an example of how this works for future reference (there are no 1.11.x releases).

**Review by scheibelp — APPROVED** [review]

**Review by hyoklee — APPROVED** [review]

**Comment by scheibelp** [comment]
Thanks!

**Comment by lrknox** [comment]
> Thanks!

Thank you!

**Comment by sethrj** [comment]
I arrived at this PR after wondering why my environment concretized at hdf5@1.10.7 rather than @1.10.8 (which is used by my jupyter/python environment). Because the older version `4.10.2` of Silo is "preferred", that has the consequence of shifting HDF5 back a version...

@markcmiller86 is there a release date for 4.10.3, and will it fix this incompatibility?
