### PR TITLE
package: removed default no-op patch 

### PR DESCRIPTION
**Pull request by alalazo**
Apparently the change was introduced in 221f17971634e43950f90333776589c4d0bf0ce3. The function doesn't seem to be needed at a first glance.

### CODE REVIEW

**Comment by tgamblin** [comment]
That was easy.  Should add that this fixes #4085

**Comment by alalazo** [comment]
This seems to work, but I prefer @tgamblin to merge it (in case I missed something from 221f179)

**Comment by tgamblin** [comment]
@alalazo: thanks for making me double check.  I can't check right now but this might cause a regression of #1490, as fixed in #3411.  I should've added a test in `builtin.mock` for a single-version `@when`'d method.  Can you add a test for it?

I think you can fix it by returning a generic no-op (e.g. `def foo(*kargs, **kwargs): pass`) instead of raising `NoSuchMethodError` [at this spot in `multimethod.py`](https://github.com/LLNL/spack/pull/3411/files#diff-d482ba57a3242a12319d00796e8ff770R138).

**Comment by alalazo** [comment]
I decided to handle this in `do_patch` directly, as the behavior of multimethod seems pythonic already. Testing this manually by adding in `zlib`:
```python
@when('@1.2.11')
def patch(self):
    pass
```
gives:
```console
$ spack install zlib
==> Installing zlib
==> Fetching file:///home/mculpo/production/spack-mirror/zlib/zlib-1.2.11.tar.gz
######################################################################## 100,0%
==> Staging archive: /home/mculpo/PycharmProjects/spack/var/spack/stage/zlib-1.2.11-pgxsxv73i5qtj6x3hnruc54ps5dan5zn/zlib-1.2.11.tar.gz
==> Created stage in /home/mculpo/PycharmProjects/spack/var/spack/stage/zlib-1.2.11-pgxsxv73i5qtj6x3hnruc54ps5dan5zn
==> Ran patch() for zlib
==> Building zlib [Package]
==> Executing phase : 'install'
==> Successfully installed zlib
  Fetch: 0.01s.  Build: 1.78s.  Total: 1.79s.
[+] /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/zlib-1.2.11-pgxsxv73i5qtj6x3hnruc54ps5dan5zn

$ spack  install zlib@1.2.8
==> Installing zlib
==> Fetching file:///home/mculpo/production/spack-mirror/zlib/zlib-1.2.8.tar.gz
######################################################################## 100,0%
==> Staging archive: /home/mculpo/PycharmProjects/spack/var/spack/stage/zlib-1.2.8-duf47uk5afudjdadwjlfupythgoc6mt7/zlib-1.2.8.tar.gz
==> Created stage in /home/mculpo/PycharmProjects/spack/var/spack/stage/zlib-1.2.8-duf47uk5afudjdadwjlfupythgoc6mt7
==> No patches needed for zlib
==> Building zlib [Package]
==> Executing phase : 'install'
==> Successfully installed zlib
  Fetch: 0.01s.  Build: 2.15s.  Total: 2.17s.
[+] /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/zlib-1.2.8-duf47uk5afudjdadwjlfupythgoc6mt7
```

**Comment by alalazo** [comment]
@tgamblin I was thinking about adding a build test similar to `hypre` but faster with a multimethod like the above to hit the new lines in `do_patch`. Otherwise I think we need either to write a lot of mockery, or refactor do_patch into smaller components and just test the one that calls the directive or the method.

**Comment by alalazo** [comment]
ping

**Comment by alalazo** [comment]
ping

**Comment by alalazo** [comment]
> Oops, ignore my previous approval. I found a bug:

No bug at all. `libsigsegv` is an `AutotoolsPackage` and @lee218llnl added a `patch` function in the base class. It's that function that is reported in the message.

**Comment by alalazo** [comment]
@adamjstewart 

```console
$ spack install tar
==> Installing tar
==> Fetching file:///home/mculpo/production/spack-mirror/tar/tar-1.29.tar.gz
######################################################################## 100,0%
==> Staging archive: /home/mculpo/PycharmProjects/spack/var/spack/stage/tar-1.29-wse2assgc5mojkrpslajyllqhjvqtzfb/tar-1.29.tar.gz
==> Created stage in /home/mculpo/PycharmProjects/spack/var/spack/stage/tar-1.29-wse2assgc5mojkrpslajyllqhjvqtzfb
==> Applied patch config-pgi.patch
==> Applied patch se-selinux.patch
==> Applied patch argp-pgi.patch
==> Applied patch tar-pgi.patch
==> Ran patch() for tar
...
```
Patches appearing in the directives are reported as:
```
==> Applied patch se-selinux.patch
```
while patch functions:
```
==> Ran patch() for tar
```
This behavior didn't change in the PR, but maybe we can figure out a clearer way to report information to users.

**Comment by adamjstewart** [comment]
Ah, you're right again. It would be cool if we could get the default Autotools `patch()` to return some kind of no-op signal so that we know nothing ran.

**Comment by adamjstewart** [comment]
Ping @tgamblin

**Comment by alalazo** [comment]
ping
