### PR TITLE
py-pyside: fix build with python3.8

### PR DESCRIPTION
**Pull request by manuelakuhn**
According to [this issue](https://github.com/pyside/PySide/issues/132), `py-pyside` does not work with `python@3.5` and newer. In `py-pyside@1.2.4`  there even is a  check for the python version and the run fails if it does not match with
```
  only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4), (3, 5)]
```
Why the check claims that `python@3.5` is supported I don't know and because this python version is not longer available in spack I cannot test it (and I doubt it would concretize).

But for `py-pyside@1.2.2` this python check is not there, so I managed to fix the build by restricting the `python` and `py-markupsafe` versions (installs fine with `--test=root`).

### CODE REVIEW

**Comment by adamjstewart** [comment]
So if I'm understanding correctly, PySide has never officially supported 3.5+, and 1.2.4 explicitly adds a check to enforce this, but 1.2.2 works fine. I'm guessing the "issue" is the `subprocess.mswindows` thing I patched below. I bet if you remove that version check 1.2.4 will work as well.

It's unfortunate that 3.9+ isn't supported. 3.8 will go away next year, and pyside (like pyqt4) is more or less replaced by pyside2 (pyqt5) and pyside6 (pyqt6). So if you can't get any of these versions working with 3.7–3.8 you can just remove them.

**Comment by manuelakuhn** [comment]
That was easier than expected. Removing the check did the trick also for version 1.2.4

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 1]
```diff
@@ -33,17 +33,23 @@ class PyPyside(PythonPackage):
         preferred=True,
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]: Do we still want this to be preferred or does 1.2.4 work now?

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 2]
```diff
@@ -33,17 +33,23 @@ class PyPyside(PythonPackage):
...
+    depends_on("cmake", type="build")
+
     depends_on("py-sphinx", type=("build", "run"))
     depends_on("py-sphinx@:3.5.0", type=("build", "run"), when="@:1.2.2")
     depends_on("qt@4.5:4.9")
     depends_on("libxml2@2.6.32:")
     depends_on("libxslt@1.1.19:")
 
+    # to prevent ImportError: cannot import name 'soft_unicode' from 'markupsafe'
+    conflicts("^py-markupsafe@2.0.2:")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]: This package doesn't import markupsafe. Does this belong in some other package?

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 3]
```diff
@@ -93,5 +99,8 @@ def patch(self):
             "setup.py",
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]: This can be removed, it doesn't do anything

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 4]
```diff
@@ -93,5 +99,8 @@ def patch(self):
...
         )
 
+        # remove check for python version
+        filter_file(r"^check_allowed_python_version()", "", "setup.py")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]:
```suggestion
        filter_file("^check_allowed_python_version()", "", "setup.py")
```
You're not escaping anything

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 5]
```diff
@@ -33,17 +33,23 @@ class PyPyside(PythonPackage):
...
+    # named 'tp_print'
+    depends_on("python@:3.8", type=("build", "run"))
     depends_on("py-setuptools", type="build")
     # in newer pip versions --install-option does not exist
     depends_on("py-pip@:23.0", type="build")
+    depends_on("cmake", type="build")
+
     depends_on("py-sphinx", type=("build", "run"))
     depends_on("py-sphinx@:3.5.0", type=("build", "run"), when="@:1.2.2")
     depends_on("qt@4.5:4.9")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]:
```suggestion
    depends_on("qt@4.6:4.8")
```
According to setup.py

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 6]
```diff
@@ -33,17 +33,23 @@ class PyPyside(PythonPackage):
...
 
-    depends_on("cmake", type="build")
-
+    # to prevent error: 'PyTypeObject' {aka 'struct _typeobject'} has no member
+    # named 'tp_print'
+    depends_on("python@:3.8", type=("build", "run"))
     depends_on("py-setuptools", type="build")
     # in newer pip versions --install-option does not exist
     depends_on("py-pip@:23.0", type="build")
+    depends_on("cmake", type="build")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]:
```suggestion
    depends_on("cmake@2.6:", type="build")
```

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 3 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Done

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 1 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: I totally overlooked that there is a preference (I was testing with specified versions :-)).
I don't know what problems there where in the past, but 1.2.4 installs fine with `--test=root` for me.
Is there anything else to test? Otherwise I remove the preference.

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 2 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Same as for `py-shiboken`, `py-markupsafe` comes from `py-jinja` which comes from `py-sphinx`

1.2.2 with conflict

```
[+]      ^py-sphinx@3.4.1%gcc@12.3.1 build_system=python_pip arch=linux-fedora37-x86_64
...
[+]          ^py-jinja2@2.11.3%gcc@12.3.1~i18n build_system=python_pip arch=linux-fedora37-x86_64
[+]              ^py-markupsafe@2.0.1%gcc@12.3.1 build_system=python_pip arch=linux-fedora37-x86_64
...
```
1.2.2 without conflict
```
[+]      ^py-sphinx@3.4.1%gcc@12.3.1 build_system=python_pip arch=linux-fedora37-x86_64
...
[+]          ^py-jinja2@2.11.3%gcc@12.3.1~i18n build_system=python_pip arch=linux-fedora37-x86_64
[+]              ^py-markupsafe@2.1.3%gcc@12.3.1 build_system=python_pip arch=linux-fedora37-x86_64
...
```

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 5 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Didn't see that, thanks.

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 6 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Where is this coming from?

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 2 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Ok, I found [this issue for jinja](https://github.com/pallets/jinja/issues/1585), so I think we can add 
```
conflicts("^py-markupsafe@2.0.2:", when="@:2.11.3")
```
to `py-jinja`.
The problem is, that it's hard to test. `py-jinja@2.11.3` installs fine without the conflict even with `--test=root` for me.
I will open a PR for it.

Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Done in #38913 and I have also removed the conflict here.

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 1 above)
Comment (adamjstewart) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: I would also check `spack test run py-pyside` and try to reproduce the above comment. You can also check `ldd -r` (or `otool -L` on macOS) on any .so/.dylib libraries. If there are RPATH issues, we can always set `*LD_LIBRARY_PATH`.

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 6 above)
Comment (adamjstewart) [reply var/spack/repos/builtin/packages/py-pyside/package.py]:
```console
> grep -R cmake_minimum *
sources/pyside-tools/CMakeLists.txt:cmake_minimum_required(VERSION 2.6)
sources/pyside/CMakeLists.txt:cmake_minimum_required(VERSION 2.6)
sources/pyside/tests/pysidetest/CMakeLists.txt:cmake_minimum_required(VERSION 2.6)
sources/shiboken/CMakeLists.txt:cmake_minimum_required(VERSION 2.6)
```

File: var/spack/repos/builtin/packages/py-pyside/package.py [hunk 7]
```diff
@@ -84,14 +87,9 @@ def patch(self):
...
-        # PySide does not provide official support for
-        # Python 3.5, but it should work fine
-        filter_file(
-            "'Programming Language :: Python :: 3.4'",
-            "'Programming Language :: Python :: 3.4',\r\n        "
-            "'Programming Language :: Python :: 3.5'",
-            "setup.py",
-        )
+        # remove check for python version becaus Python 3.5 is not officially
+        # supported, but it should work fine
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-pyside/package.py]:
```suggestion
        # Remove check for python version because the above patch adds support for newer versions
```

Comment (adamjstewart) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: You could even move it below the subprocess patch to make this clear

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 6 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Thanks

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 7 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: Done

File: var/spack/repos/builtin/packages/py-pyside/package.py (hunk 1 above)
Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: There seems to be an issue with `spack test run` because when I test a python package, I get the error
```
'str' object is not callable
```
I tested `py-pyside`. `py-pip`, `py-wheel`, `py-imortlib-metadata`

Comment (manuelakuhn) [reply var/spack/repos/builtin/packages/py-pyside/package.py]: With #38928 the tests for both versions run fine. I am a little confused because it seems that there are two sets of import tests the ones for `spack test run` and the ones for `--test=root`... (the former ran into the error, but the latter not)

**Review by adamjstewart — APPROVED** [review]
