### ISSUE TITLE
Fine-grained control of git submodules is broken

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#45319]
### Steps to reproduce

As per the instructions [here](https://spack.readthedocs.io/en/v0.22.1/packaging_guide.html#git) to implement fine-grained control of git submodules, write the following into the file `spack/var/spack/repos/builtin/packages/pkg/package.py`:
```python
from spack.package import *
import llnl.util.tty as tty


def submodules(package):
    tty.warn(f'pkg.package.submoudles, package: {package}')
    tty.warn(f'pkg.package.submoudles, spec: {package.spec}')
    return []


class Pkg(Package):
    git      = "https://github.com/python-mode/python-mode.git"
    version('develop', branch='develop', submodules=submodules)
```
and then
```console
$ spack clean
$ spack fetch pkg
==> Warning: pkg.package.submoudles, package: None
==> Error: 'NoneType' object has no attribute 'spec'
```
I've tried it with spack v0.21, v0.22 and develop.

### Error message

```console
$ spack clean
$ spack fetch pkg
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.194655] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-07-19-13:26:06.232467] Imported fetch from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-07-19-13:26:06.233199] Imported fetch from built-in commands
lib/spack/spack/database.py:646 ==> [2024-07-19-13:26:06.236064] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-07-19-13:26:06.236267] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.236651] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.248775] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.290736] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.363285] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.502231] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/linux/compilers.yaml
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.540235] '/usr/bin/gcc-10' '-v' '/tmp/spack-implicit-link-infosg0urp23/main.c' '-o' '/tmp/spack-implicit-link-infosg0urp23/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.579812] '/usr/bin/gcc-11' '-v' '/tmp/spack-implicit-link-infowryr2_aj/main.c' '-o' '/tmp/spack-implicit-link-infowryr2_aj/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.616335] '/usr/bin/gcc-12' '-v' '/tmp/spack-implicit-link-info35estibu/main.c' '-o' '/tmp/spack-implicit-link-info35estibu/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.654035] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infoc8fi0p7r/main.c' '-o' '/tmp/spack-implicit-link-infoc8fi0p7r/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.692350] '/usr/bin/gcc-8' '-v' '/tmp/spack-implicit-link-infoxjvt9u76/main.c' '-o' '/tmp/spack-implicit-link-infoxjvt9u76/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:06.730549] '/usr/bin/gcc-9' '-v' '/tmp/spack-implicit-link-infougdvv9yy/main.c' '-o' '/tmp/spack-implicit-link-infougdvv9yy/output'
lib/spack/spack/database.py:646 ==> [2024-07-19-13:26:06.886041] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-07-19-13:26:06.886281] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.887895] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/database.py:646 ==> [2024-07-19-13:26:06.896307] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-07-19-13:26:06.896553] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.896976] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.930010] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.932611] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:06.975455] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/packages.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-07-19-13:26:07.051254] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.051879] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-07-19-13:26:07.059882] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-07-19-13:26:07.060096] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-07-19-13:26:07.060301] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-07-19-13:26:07.060541] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/bootstrap/config/linux
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.062073] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.092536] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:646 ==> [2024-07-19-13:26:07.106093] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-07-19-13:26:07.106308] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.106784] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.149974] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:231 ==> [2024-07-19-13:26:07.195427] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
lib/spack/spack/bootstrap/core.py:355 ==> [2024-07-19-13:26:07.195613] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.196122] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:83 ==> [2024-07-19-13:26:07.321273] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.6/t4yf34cuvquqp5xd66zybmcfyhwbdlsf" provides the "clingo" Python module
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.321933] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:07.965259] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:08.007678] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/packages.yaml
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:08.080388] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack_config_v0.21/linux/compilers.yaml
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.117003] '/usr/bin/gcc-10' '-v' '/tmp/spack-implicit-link-infoujb_8kt9/main.c' '-o' '/tmp/spack-implicit-link-infoujb_8kt9/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.164783] '/usr/bin/gcc-11' '-v' '/tmp/spack-implicit-link-infosze9mkjt/main.c' '-o' '/tmp/spack-implicit-link-infosze9mkjt/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.212209] '/usr/bin/gcc-12' '-v' '/tmp/spack-implicit-link-infonz156phs/main.c' '-o' '/tmp/spack-implicit-link-infonz156phs/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.261747] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infofd3maodr/main.c' '-o' '/tmp/spack-implicit-link-infofd3maodr/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.313912] '/usr/bin/gcc-8' '-v' '/tmp/spack-implicit-link-infozerlxxv2/main.c' '-o' '/tmp/spack-implicit-link-infozerlxxv2/output'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:08.361840] '/usr/bin/gcc-9' '-v' '/tmp/spack-implicit-link-info8vmsi3it/main.c' '-o' '/tmp/spack-implicit-link-info8vmsi3it/output'
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:08.539091] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/config.yaml
lib/spack/spack/solver/asp.py:3545 ==> [2024-07-19-13:26:12.190918] UNKNOWN SYMBOL: attr("language", NodeArgument(id='0', pkg='glibc'), cxx)
lib/spack/spack/solver/asp.py:3545 ==> [2024-07-19-13:26:12.191587] UNKNOWN SYMBOL: attr("language", NodeArgument(id='0', pkg='glibc'), c)
lib/spack/spack/package_base.py:1712 ==> [2024-07-19-13:26:12.345699] Missing a source id for pkg@develop
lib/spack/spack/config.py:1117 ==> [2024-07-19-13:26:12.414799] Reading config from file /scratch/andrew/bugs/spack/fine-grained-submodules/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:434 ==> [2024-07-19-13:26:12.418396] Checking existence of https://mirror.spack.io/_source-cache/git/python-mode/python-mode.git/develop.tar.gz
lib/spack/spack/util/web.py:71 ==> [2024-07-19-13:26:12.419313] certs: relative path not allowed: $SSL_CERT_FILE
lib/spack/spack/util/web.py:462 ==> [2024-07-19-13:26:13.009278] Failure reading URL: HEAD https://mirror.spack.io/_source-cache/git/python-mode/python-mode.git/develop.tar.gz returned 404: Not Found
lib/spack/spack/fetch_strategy.py:307 ==> [2024-07-19-13:26:13.009609] URL does not exist: https://mirror.spack.io/_source-cache/git/python-mode/python-mode.git/develop.tar.gz
lib/spack/spack/stage.py:553 ==> [2024-07-19-13:26:13.009845] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/python-mode/python-mode.git/develop.tar.gz
lib/spack/spack/util/web.py:434 ==> [2024-07-19-13:26:13.010052] Checking existence of https://mirror.spack.io/pkg/pkg-develop.tar.gz
lib/spack/spack/util/web.py:462 ==> [2024-07-19-13:26:13.589649] Failure reading URL: HEAD https://mirror.spack.io/pkg/pkg-develop.tar.gz returned 404: Not Found
lib/spack/spack/fetch_strategy.py:307 ==> [2024-07-19-13:26:13.589974] URL does not exist: https://mirror.spack.io/pkg/pkg-develop.tar.gz
lib/spack/spack/stage.py:553 ==> [2024-07-19-13:26:13.590192] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/pkg/pkg-develop.tar.gz
lib/spack/spack/fetch_strategy.py:829 ==> [2024-07-19-13:26:13.590404] Cloning git repository: https://github.com/python-mode/python-mode.git on branch develop
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:13.591169] '/usr/bin/git' '--version'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:13.598698] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:13.606965] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
lib/spack/spack/util/executable.py:233 ==> [2024-07-19-13:26:13.613373] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/python-mode/python-mode.git'
Cloning into 'python-mode'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 113 (delta 4), reused 79 (delta 4), pack-reused 0
Receiving objects: 100% (113/113), 96.24 KiB | 4.18 MiB/s, done.
Resolving deltas: 100% (4/4), done.
var/spack/repos/builtin/packages/pkg/package.py:7 ==> [2024-07-19-13:26:14.183607] Warning: pkg.package.submoudles, package: None
Traceback (most recent call last):
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/cmd/fetch.py", line 75, in fetch
    pkg.do_fetch()
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/package_base.py", line 1524, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/stage.py", line 546, in fetch
    self.fetcher.fetch()
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/fetch_strategy.py", line 83, in wrapper
    return fun(self, *args, **kwargs)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/fetch_strategy.py", line 810, in fetch
    self.clone(commit=self.commit, branch=self.branch, tag=self.tag)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/lib/spack/spack/fetch_strategy.py", line 932, in clone
    submodules = submodules(self.package)
  File "/scratch/andrew/bugs/spack/fine-grained-submodules/spack/var/spack/repos/builtin/packages/pkg/package.py", line 8, in submodules
    return []
AttributeError: 'NoneType' object has no attribute 'spec'
```

### Information on your system

* **Spack:** 0.23.0.dev0 (d82c9e7f2a2f4a59c4e80e7219f57b82dcb87b5d)
* **Python:** 3.6.15
* **Platform:** linux-opensuse15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by andymwood** [comment]
I can provide a bit more help. I've just run `git bisect`:
```console
$ git bisect start v0.21.2 v0.20.3
$ git bisect run "spack clean ; spack fetch pkg"
...
185bccb70f51566ae23e984b47d8058cf569e4b6 is the first bad commit
commit 185bccb70f51566ae23e984b47d8058cf569e4b6
Author: Harmen Stoppels <harmenstoppels@gmail.com>
Date:   Wed Jul 19 15:06:56 2023 +0200

    Fetch & patch: actually acquire stage lock, and many more issues (#38903)
    
    * Fetching patches wouldn't result in acquiring a stage lock during install
    * The installer would acquire a stage lock *after* fetching instead of
       before, leading to races
    * The name of the stage for patches was random, so on build failure
       (where stage dirs are not removed), these directories would continue
       to exist after a second successful install.
    * There was this redundant "composite fetch" object -- there's already
       a composite stage. Remove this.
    * For some reason we do *double* shasum validation of patches, before
       and after compression -- that's just too much? I removed it.

 lib/spack/spack/cmd/fetch.py                   | 30 ++++++----
 lib/spack/spack/cmd/patch.py                   | 26 ++++++++-
 lib/spack/spack/cmd/stage.py                   | 44 +++++++++-----
 lib/spack/spack/environment/environment.py     |  7 ++-
 lib/spack/spack/fetch_strategy.py              | 70 ++++++++++++----------
 lib/spack/spack/installer.py                   | 32 +++++-----
 lib/spack/spack/mirror.py                      |  5 +-
 lib/spack/spack/package_base.py                | 75 ++++++++----------------
 lib/spack/spack/patch.py                       | 81 ++++++++------------------
 lib/spack/spack/stage.py                       |  3 +-
 lib/spack/spack/test/cmd/stage.py              | 18 +++---
 lib/spack/spack/test/concretize_preferences.py |  4 +-
 lib/spack/spack/test/conftest.py               |  9 ++-
 lib/spack/spack/test/installer.py              |  2 +
 lib/spack/spack/test/mirror.py                 |  2 +-
 lib/spack/spack/test/packaging.py              | 13 ++---
 lib/spack/spack/test/patch.py                  |  8 ++-
 17 files changed, 210 insertions(+), 219 deletions(-)
bisect found first bad commit
```
