### PR TITLE
bugfix: use getattr for variation.prefix/suffix

### PR DESCRIPTION
**Pull request by eugeneswalker**
Replace:
1. Use `getattr(variation, 'prefix', None)` instead of `variation.prefix` 
2. Use `getattr(variation, 'suffix', None)` instead of `variation.suffix` 

Resolves issue preventing `spack compiler find` from working on NERSC Cori.

@becker33 @shahzebsiddiqui

### CODE REVIEW

**Comment by becker33** [comment]
More details: the version args object used for Cray compiler detection doesn't have `prefix` and `suffix` attributes. We access these attributes for sorting compilers on non-cray systems, but we have to do so in a way that doesn't cause errors when the attribute is absent.

**Review by becker33 — APPROVED** [review]

**Review by tgamblin — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
Just to give you context i saw this error today in spack pipeline, it wasn't an issue yesterday.

```
 $ git clone ${SPACK_REPO} --branch ${SPACK_REF} --depth=1
 Cloning into 'spack'...
 Checking out files:  19% (1224/6440)   
 Checking out files:  38% (2498/6440)   
 Checking out files:  58% (3762/6440)   
 Checking out files:  73% (4702/6440)   
 Checking out files:  80% (5152/6440)   
 Checking out files:  94% (6054/6440)   
 Checking out files: 100% (6440/6440), done.
 $ . spack/share/spack/setup-env.sh
 $ hostname
 cori04
 $ spack env activate .
 $ spack concretize -f 2>&1 | tee concretize.log
 ==> Error: 'tuple' object has no attribute 'prefix'
 ERROR: Job failed: slurm job 838970 failed, final state FAILED
```

**Comment by becker33** [comment]
@shahzebsiddiqui that makes sense, this was caused by #17590, which I merged around 6pm last night.
