### PR TITLE
libzmq: Add libbsd as a dependency

### PR DESCRIPTION
**Pull request by a-saitoh-fj**
For example, if you load py-sphinx and then spack install libzmq, you will get the following error:

>> 414    /usr/bin/ld: warning: libbsd.so.0, needed by src/.libs/libzmq.so, not found (try using -rpath or -rpath-link)
>> 415    src/.libs/libzmq.so: undefined reference to `strlcpy@@LIBBSD_0.0'
>> 416    collect2: error: ld returned 1 exit status

It seems that libzmq 4.3.3 started using strlcpy.
In libzmq 4.3.2, this does not happen.

Therefore, add libbsd to the dependency.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by healther** [comment]
This breaks builds on OSX and `libzmq@4.3.3` worked for me (at least on OSX). I'm not sure if this is _required_ on linux, but I think we build it in the lab too and it worked, but I'll have to look up the precise versions used at work
