### ISSUE TITLE
Are module add in compiler.yaml just for Cray's ?

### ISSUE THREAD

**Issue by luigi-calori** [LLNL/spack#2135]
I' m trying to use an externally installed intel compiler on a non cray system.
The system uses Tcl env modules
Modules Release Tcl 3.1.6 ($RCSfile: modulecmd.tcl,v $ $Revision: 1.112 $)

I can load intel by doing 
module load intel/pe-xe-2016--binary

spack  compiler find --scope site
results in adding following  lines to compilers.yaml 
- compiler:
  flags: {}
  modules: []
  operating_system: centos7
  paths:
    cc: /galileo/prod/compilers/intel/pe-xe-2016/binary/bin/icc
    cxx: /galileo/prod/compilers/intel/pe-xe-2016/binary/bin/icpc
    f77: /galileo/prod/compilers/intel/pe-xe-2016/binary/bin/ifort
    fc: /galileo/prod/compilers/intel/pe-xe-2016/binary/bin/ifort
  spec: intel@16.0.3

Nevertheless is impossible to build with  intel@16.0.3 unless explicitly loading 
module load intel/pe-xe-2016--binary
 the environment generated by module is needed

I' ve tried to edit compilers.yaml to add
modules: [intel/pe-xe-2016--binary]

but then
spack  install   cmake%intel@16.0.3

bail out with

==> Installing cmake
==> Installing bzip2
Traceback (most recent call last):
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/bin/spack", line 202, in <module>
    main()
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/bin/spack", line 179, in main
    return_val = command(parser, args)
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/lib/spack/spack/cmd/install.py", line 117, in install
    package.do_install(**kwargs)
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/lib/spack/spack/package.py", line 1183, in do_install
    dirty=dirty)
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/lib/spack/spack/package.py", line 1268, in do_install
    spack.build_environment.fork(self, build_process, dirty=dirty)
  File "/gpfs/scratch/userinternal/lcalori0/spack/p/deploy/spack_clean/lib/spack/spack/build_environment.py", line 542, in fork
    raise exception
AttributeError: 'NoneType' object has no attribute 'add_default_arg'

**Comment by pramodk** [comment]
@luigi-calori : have you installed `environment-modules`? if externally installed, then have you set it properly in `packages.yaml`?

You might need to specify `--dirty` flag. There is long discussion on google group about setting properly intel compilers.

**Comment by davydden** [comment]
@luigi-calori : have you seen https://github.com/LLNL/spack/issues/2056 ?

As for your problem
```
AttributeError: 'NoneType' object has no attribute 'add_default_arg'
```
It looks like it's unrelated. Can try pulling again, there was a bug fixed recently.

@alalazo : any ideas about another `AttributeError`? I hope it's the same one as with `which()`.

**Comment by luigi-calori** [comment]
I have narrowed down the problem: at line [line 123 of build_environment.py](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L123)
which('modulecmefuld') return None in my environment, so the error.
my pre-installed module system does not have any modulecmd 
Would be interesting to know which module system is required for this to work.
Also I would suggest to add required=True to the which call, so the error is more meaningful

**Comment by becker33** [comment]
Closing as fixed by #3250. Reopen if that does not resolve the issue.
