### ISSUE TITLE
slate@2021.05.02 +rocm build fails: cmake failure with rocm>=5

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#30596]
### Steps to reproduce

slate@2021.05.02 +rocm build fails using:

    spack/develop (https://github.com/spack/spack/commit/250d5d2c00ad9d6a747499b1160bc4a460266fae from Wed May 4 13:30:15 2022 -0400)
    Ubuntu 20.04, X86_64
    GCC 9.4.0
    ROCm 5.0.2

Quickly reproducible using cached dependency binaries and Docker container image:

    ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01

### Error message

```$> spack install ...
...
1 error found in build log:
     24
     25    ---------------------------------------- BLAS++
     26    -- Using CMAKE_INSTALL_PREFIX = /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/slate-2021.05.02-ux5yjblnmviifkwfzsmebq6uigcprm6p
     27    -- Skipping CUDA search. gpu_backend = hip
     28    -- Not building CUDA support in BLAS++
     29    -- Looking for HIP/ROCm
  >> 30    CMake Error at /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/cmake-3.23.1-hhpsxesjcfasowyax5ixqgnard2cttc5/share/cmake-3.23/Modules/FindPackageHandle
           StandardArgs.cmake:230 (message):
     31      Could NOT find Threads (missing: Threads_FOUND)
     32    Call Stack (most recent call first):
     33      /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/cmake-3.23.1-hhpsxesjcfasowyax5ixqgnard2cttc5/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.
           cmake:594 (_FPHSA_FAILURE_MESSAGE)
     34      /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/cmake-3.23.1-hhpsxesjcfasowyax5ixqgnard2cttc5/share/cmake-3.23/Modules/FindThreads.cmake:238 (FIND_PA
           CKAGE_HANDLE_STANDARD_ARGS)
     35      /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/cmake-3.23.1-hhpsxesjcfasowyax5ixqgnard2cttc5/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake
           :47 (find_package)
     36      /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hip-5.0.2-zxtdoythrectfv7epw3a3kdeayjsap2g/lib/cmake/hip/hip-config.cmake:204 (find_dependency)
```

### Information on your system

Information on your system

    Spack: 0.18.0.dev0 (https://github.com/spack/spack/commit/250d5d2c00ad9d6a747499b1160bc4a460266fae)
    Python: 3.8.10
    Platform: linux-ubuntu20.04-cascadelake
    Concretizer: clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by G-Ragghianti** [comment]
@eugeneswalker Maybe you can also help with this:  I am currently unable to build rocm packages due to an apparent problem with the mesa package (required by llvm-amdgpu).  How were you able to build mesa for your e4s binary cache?  Here is an example of the problem (hip@4.3.1):
```
     1211    /root/spack/lib/spack/env/gcc/g++ -Isrc/gallium/auxiliary/libgallium.a.p -Isrc/gallium/auxiliary -I../src/galli
             um/auxiliary -Isrc/loader -I../src/loader -I../src/gallium/include -Isrc -I../src -Iinclude -I../include -I../s
             rc/gallium/auxiliary/util -Isrc/compiler/nir -I../src/compiler/nir -Isrc/util -I../src/util -I/root/spack/opt/s
             pack/linux-ubuntu20.04-skylake_avx512/gcc-9.4.0/zlib-1.2.12-qtt2awqc5hxk4fphprqcts5ckfj73mz7/include -fvisibili
             ty=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -st
             d=c++14 -O3 -ffunction-sections -fdata-sections '-DPACKAGE_VERSION="21.3.8"' '-DPACKAGE_BUGREPORT="https://gitl
             ab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DUS
             E_XSHM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BU
             ILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___B
             UILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUN
             C_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE
             _FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUT
             E_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAV
             E_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SY
             SMACROS -DHAS_SCHED_H -DHAS_SCHED_GETAFFINITY -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_SYS_SH
             M_H -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_F
             LOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_QSORT_R -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAV
             E_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_COMPRESSION -DHAVE_PTHR
             EAD -DHAVE_PTHREAD_SETAFFINITY -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="13.0.0git"' -DLLVM_IS_SHARED=0 -DD
             RAW_LLVM_AVAILABLE -DMESA_EXECMEM -DHAVE_LIBUNWIND -DHAVE_OPENMP -DVK_USE_PLATFORM_DISPLAY_KHR -Werror=return-t
             ype -Werror=empty-body -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -fno-math-e
             rrno -fno-trapping-math -flifetime-dse=1 -Werror=format -Wformat-security -fno-rtti -fPIC -pthread -isystem/roo
             t/spack/opt/spack/linux-ubuntu20.04-skylake_avx512/gcc-9.4.0/zlib-1.2.12-qtt2awqc5hxk4fphprqcts5ckfj73mz7/inclu
             de -isystem/root/spack/opt/spack/linux-ubuntu20.04-skylake_avx512/gcc-9.4.0/llvm-amdgpu-4.3.1-rpyy43xrpak6xs3vb
             vydayq7acgafr5d/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -We
             rror=pointer-arith -MD -MQ src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_misc.cpp.o -MF src/gallium/auxil
             iary/libgallium.a.p/gallivm_lp_bld_misc.cpp.o.d -o src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_misc.cpp
             .o -c ../src/gallium/auxiliary/gallivm/lp_bld_misc.cpp
     1212    ../src/gallium/auxiliary/gallivm/lp_bld_misc.cpp: In function 'void lp_set_module_stack_alignment_override(LLVM
             ModuleRef, unsigned int)':
  >> 1213    ../src/gallium/auxiliary/gallivm/lp_bld_misc.cpp:631:6: error: 'class llvm::Module' has no member named 'setOve
             rrideStackAlignment'
     1214      631 |   M->setOverrideStackAlignment(align);
     1215          |      ^~~~~~~~~~~~~~~~~~~~~~~~~
``
[spack-build-out.txt](https://github.com/spack/spack/files/8671673/spack-build-out.txt)
`

**Comment by eugeneswalker** [comment]
We are using mesa 21.3.8 and not the latest version. Does 21.3.8 work for you?

**Comment by G-Ragghianti** [comment]
I was trying with 21.3.8 because I saw that you were using that version.  

Oddly, I'm able to build with `spack install mesa@21.3.8 %gcc@9.4.0`.  This produces the following spec:

```
-- linux-ubuntu20.04-skylake_avx512 / gcc@9.4.0 -----------------
3qlkr43 mesa@21.3.8+glx+llvm+opengl~opengles+osmesa~strip buildtype=release default_library=shared patches=ada85be swr=auto
```

However, if I try to build slate with this full mesa spec, spack tries to build mesa again (even though it is already built) and it fails with the above error.

**Comment by G-Ragghianti** [comment]
I see that the e4s spack.yaml is using `mesa@21.3.8~llvm`.  I'm trying that now, and it appears to work.

**Comment by G-Ragghianti** [comment]
I see now that the cmake process for slate is failing because one of the dependencies (hipify-clang) has an include directory which includes headers that conflict with normal compilation (e.g. stddef.h).  Is there a way for us to depend on a package (hipify-clang) but to only have that dependency expose the binaries in PATH and not affect in include path?

**Comment by G-Ragghianti** [comment]
@luszczek
