### PR TITLE
mpich: add variant to enable per VCI critical sections

### PR DESCRIPTION
**Pull request by hyviquel**
ping @raffenet and @yfguo

### CODE REVIEW

File: var/spack/repos/builtin/packages/mpich/package.py [hunk 1]
```diff
@@ -90,6 +90,9 @@ class Mpich(AutotoolsPackage):
 '-Wl,-flat_namespace'.'''
     )
 
+    variant('max_vcis', values=int, default=1, when='netmod=ucx',
+            description='Select max number of VCIs to configure')
```
Comment (raffenet) [inline var/spack/repos/builtin/packages/mpich/package.py]: VCIs work with both the ofi and ucx netmods in ch4. And VCIs do not work with ch3, so this variant I guess should be limited to `when='device=ch4'`?

Comment (hyviquel) [reply var/spack/repos/builtin/packages/mpich/package.py]: Indeed, it is a bad copy/paste when i refactored my code. Already resolved.

File: var/spack/repos/builtin/packages/mpich/package.py [hunk 2]
```diff
@@ -90,6 +90,9 @@ class Mpich(AutotoolsPackage):
 '-Wl,-flat_namespace'.'''
     )
 
+    variant('max_vcis', values=int, default=1, when='device=ch4',
+            description='Select max number of VCIs to configure')
```
Comment (raffenet) [inline var/spack/repos/builtin/packages/mpich/package.py]: So there's a couple more factors here. First is the thread granularity (`--enable-thread-cs`). Multiple VCIs will only benefit when `--enable-thread-cs=per-vci`. Without this, performance will be limited. Second, in MPICH version >=4.0b1, ch4 now defaults to 64 max VCIs if configured for per-vci critical sections. Prior releases default to 1.

Comment (raffenet) [reply var/spack/repos/builtin/packages/mpich/package.py]: The `--with-max-vcis` option does support `--with-max-vcis=default` so that you can get the right value for whatever version you are building.

Comment (hyviquel) [reply var/spack/repos/builtin/packages/mpich/package.py]: Ok so I set the  `--enable-thread-cs=per-vci` flag when `max_vci` is set and I added a 'default' option that is used by default in case the version is superior of 3.4. 

I also added all possible configurations of `max_vcis` between 1 and 64 for the user. Should I reduce to a subset? For example, `('1', '8', '16', '32', '64')`.

Just for context, my objective here is to use 64 VCIs with MPICH 3.4.2.

Comment (raffenet) [reply var/spack/repos/builtin/packages/mpich/package.py]: There is no restriction on any number of VCIs between 1 and 64, though a power of 2 will likely generate better code when manipulating vci values. I think what you have now should work.

FWIW, you're probably less likely to run into bugs or thread contention issues using 4.0b1 with multiple VCIs. We should be putting out a stable release in the 4.0 series in the next few weeks regardless.

Comment (raffenet) [reply var/spack/repos/builtin/packages/mpich/package.py]: One last note is that the number of VCIs used at *runtime* still defaults to 1. In order to actually use multiple VCIs, you need to set an envvar e.g.
```
    MPIR_CVAR_CH4_NUM_VCIS=<N>
```

**Review by raffenet — DISMISSED** [review]

File: var/spack/repos/builtin/packages/mpich/package.py (hunk 2 above)
Comment (hyviquel) [reply var/spack/repos/builtin/packages/mpich/package.py]: Understood, thanks!! 
We will probably move to 4.0 once the stable is out.

**Comment by hyviquel** [comment]
@raffenet Are you sure about `default`? It seems one of the CI job is failing because of it...
```
In file included from ./src/include/mpiimpl.h:10:0,
                 from src/mpi/coll/allgather/allgather_intra_ring.c:6:
./src/include/mpichconf.h:1319:28: error: expected expression before 'default'
 #define MPIDI_CH4_MAX_VCIS default
                            ^
./src/mpid/ch4/include/../netmod/ofi/ofi_pre.h:243:20: note: in expansion of macro 'MPIDI_CH4_MAX_VCIS'
     fi_addr_t dest[MPIDI_CH4_MAX_VCIS][MPIDI_CH4_MAX_VCIS];     /* [local_vni][remote_vni] */
```
https://gitlab.spack.io/spack/spack/-/jobs/1287292

**Comment by raffenet** [comment]
> @raffenet Are you sure about `default`? It seems one of the CI job is failing because of it...
> 
> ```
> In file included from ./src/include/mpiimpl.h:10:0,
>                  from src/mpi/coll/allgather/allgather_intra_ring.c:6:
> ./src/include/mpichconf.h:1319:28: error: expected expression before 'default'
>  #define MPIDI_CH4_MAX_VCIS default
>                             ^
> ./src/mpid/ch4/include/../netmod/ofi/ofi_pre.h:243:20: note: in expansion of macro 'MPIDI_CH4_MAX_VCIS'
>      fi_addr_t dest[MPIDI_CH4_MAX_VCIS][MPIDI_CH4_MAX_VCIS];     /* [local_vni][remote_vni] */
> ```
> 
> https://gitlab.spack.io/spack/spack/-/jobs/1287292

Oops, sorry about that. The use of "default" only works in the 4.0.x and main branches.

**Comment by hyviquel** [comment]
Ok so it need to have different default according to the version. Unfortunately I did not find how to do this with Spack. Maybe @adamjstewart can share his expertise here?

**Comment by adamjstewart** [comment]
I think you can use `when='@X.Y:'` in a `variant` and write the variant twice with a different default for different versions.

File: var/spack/repos/builtin/packages/mpich/package.py [hunk 3]
```diff
@@ -207,6 +214,7 @@ def url_for_version(self, version):
     conflicts('pmi=pmix', when='device=ch3')
     conflicts('pmi=pmix', when='+hydra')
     conflicts('pmi=cray', when='+hydra')
+    conflicts('vci', when='@:3.99')
```
Comment (raffenet) [inline var/spack/repos/builtin/packages/mpich/package.py]: nitpick: can this just be `when='@:4.0'`?

**Comment by hyviquel** [comment]
@raffenet I changed the way the VCI are enabled: I just set cs per vci  and use the default number of VCIs, I totally excluded v3.x from using VCIs since it is not as stable (so it solves the problem I had with the not existing default number).

File: var/spack/repos/builtin/packages/mpich/package.py (hunk 3 above)
Comment (hyviquel) [reply var/spack/repos/builtin/packages/mpich/package.py]: Updated with a more elegant way: by using `when='@4.0: device=ch4'` directly in the variant.

Comment (haampie) [reply var/spack/repos/builtin/packages/mpich/package.py]: I think you'd just want this variant to exist `when='@4: device=ch4'` all the way at the top. (Note that `@:4.0` means up to and including any `4.0.x` version, which is probably not what you want)

Comment (hyviquel) [reply var/spack/repos/builtin/packages/mpich/package.py]: my bad indeed, just fixed!

**Review by raffenet — DISMISSED** [review]

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@raffenet Can you please double check the latest version before I merge?

**Review by raffenet — APPROVED** [review]
