### ISSUE TITLE
Installation issue: alps

### ISSUE THREAD

**Issue by andredepinhovieira** [LLNL/spack#22252]
### Steps to reproduce the issue
After failing to build alps with ./spack install alps%gcc@6.5.0 due to dependency problems with py-numpy, I tried specifying versions as indicated below:

$ ./spack install alps%gcc@6.5.0 ^py-numpy@:1.19 ^py-scipy@:1.5

However, I get thousands of error messages when installing boost, the first ones being given below:

==> Installing boost-1.63.0-s23bzdjur4fp7rrtsyqhw2m72jonjusn
==> No binary for boost-1.63.0-s23bzdjur4fp7rrtsyqhw2m72jonjusn found: installing from source
==> Using cached archive: /home/apvieira/spack/var/spack/cache/_source-cache/archive/be/beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0.tar.bz2
==> Applied patch /home/apvieira/spack/var/spack/repos/builtin/packages/boost/python_jam.patch
==> Applied patch /home/apvieira/spack/var/spack/repos/builtin/packages/boost/clang-linux_add_option.patch
==> Applied patch /home/apvieira/spack/var/spack/repos/builtin/packages/boost/boost_154.patch
==> Applied patch /home/apvieira/spack/var/spack/repos/builtin/packages/boost/boost_218.patch
==> Ran patch() for boost
==> boost: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './b2' 'install' 'threading=multi' '-j' '8' '--user-config=/tmp/apvieira/spack-stage/spack-stage-boost-1.63.0-s23bzdjur4fp7rrtsyqhw2m72jonjusn/spack-src/user-config.jam' 'variant=release' '-s' 'BZIP2_INCLUDE=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-6.5.0/bzip2-1.0.8-meaycxh4wb5zxpkql5gw7exx3drm2nor/include' '-s' 'BZIP2_LIBPATH=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-6.5.0/bzip2-1.0.8-meaycxh4wb5zxpkql5gw7exx3drm2nor/lib' '-s' 'ZLIB_INCLUDE=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-6.5.0/zlib-1.2.11-3koylc2ckssastcbr64kcsz37qevntm5/include' '-s' 'ZLIB_LIBPATH=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-6.5.0/zlib-1.2.11-3koylc2ckssastcbr64kcsz37qevntm5/lib' '-s' 'NO_LZMA=1' '-s' 'NO_ZSTD=1' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxflags="-std=c++98"'

12424 errors found in build log:
     13903                     from /usr/include/unicode/unistr.h:39,
     13904                     from /usr/include/unicode/strenum.h:20,
     13905                     from /usr/include/unicode/locid.h:40,
     13906                     from /usr/include/unicode/coll.h:64,
     13907                     from ./boost/regex/icu.hpp:24,
     13908                     from libs/regex/build/../src/icu.cpp:23:
  >> 13909    /home/apvieira/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/gcc-6.5.0-higw6lauclxiqjqoov362usjiyx4bag7/include/c++/6.5.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This supp
              ort must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     13910     #error This file requires compiler and library support \
     13911      ^~~~~
     13912    In file included from /usr/include/unicode/utypes.h:38:0,
     13913                     from ./boost/regex/icu.hpp:22,
     13914                     from libs/regex/build/../src/icu.cpp:23:
  >> 13915    /usr/include/unicode/umachine.h:376:13: error: 'char16_t' does not name a type
     13916         typedef char16_t UChar;
     13917                 ^~~~~~~~
     13918    In file included from /usr/include/unicode/utypes.h:39:0,
     13919                     from ./boost/regex/icu.hpp:22,
     13920                     from libs/regex/build/../src/icu.cpp:23:
  >> 13921    /usr/include/unicode/uversion.h:159:55: error: 'UChar' does not name a type
     13922     u_versionFromUString(UVersionInfo versionArray, const UChar *versionString);
     13923                                                           ^~~~~

### Information on your system
Ubuntu 20.04 on an Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 32 GB RAM 
Kernel 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 

* **Spack:** 0.16.1-1674-d0610f7a39
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

### Additional information
[spack-build-env.txt](https://github.com/spack/spack/files/6125749/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6125751/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
@andredepinhovieira alps won't compile with python version higher than 3.6 since boost@1.63 fails to build with brand new python versions. I suggest that you uncomment `depends_on('python@:3.6.99', type=('build', 'link', 'run'))` line and build with python <= 3.6

**Comment by andredepinhovieira** [comment]
Ubuntu 20.04 ships with Python 3.8. I installed 3.6 and pointed /usr/bin/python3 to /usr/bin/python3.6. 
After that, just to be on the safe side, I cloned spack to another folder, installed gcc 6 and ran './spack install alps%gcc@6.5.0 ^py-numpy@:1.19 ^py-scipy@:1.5'.
The same errors were reported, while './spack debug report' outputs
* **Spack:** 0.16.1-1674-d0610f7a39
* **Python:** 3.6.13
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

Thus, it seems that I am using Python 3.6, but building does not go past boost.

**Comment by Sinan81** [comment]
Are you trying to use the system python instead of building it with spack? If not, then there is no need to modify `/usr/bin/python3` . When building packages Spack sanitizes the environment so that spack packages only depend on other spack packages (with a few rare exceptions).

**Comment by Sinan81** [comment]
As you see I've build alps with multiple gcc versions including 6.5:
```
sbulut@mymachine ~ 
$ spack find alps
==> 12 installed packages
-- linux-centos7-broadwell / gcc@5.5.0 --------------------------
alps@2.3.0

-- linux-centos7-haswell / gcc@4.8.5 ----------------------------
alps@2.3.0

-- linux-centos7-skylake / gcc@6.5.0 ----------------------------
alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0  alps@2.3.0

-- linux-centos7-skylake / gcc@8.3.0 ----------------------------
alps@2.3.0
```
So, the build should just work. Is there any reason you're using gcc@6.5? When I first created `alps` package, it wouldn't compile with gcc >= 7 however it seems recently someone added a patch so that the package now compiles with newer gcc inluding versions 7 and 8.

**Comment by andredepinhovieira** [comment]
I was using gcc 6.5 following the instructions in https://lists.phys.ethz.ch/pipermail/comp-phys-alps-users/2020/003520.html
Now I installed gcc 8.3 within Spack, removed the system-wide version of Python 3.6, and the output of './spack find python' is given below

# ./spack find python
==> 3 installed packages
-- linux-ubuntu20.04-skylake / gcc@6.5.0 ------------------------
python@3.6.13

-- linux-ubuntu20.04-skylake / gcc@7.5.0 ------------------------
python@3.6.13

-- linux-ubuntu20.04-skylake / gcc@8.3.0 ------------------------
python@3.6.13

Running './spack install alps%gcc@8.3.0 ^py-numpy@:1.19 ^py-scipy@:1.5 ^python@3.6.13' I still get the same errors as previously reported, i.e. building 'boost' fails. Nevertheless, './spack debug report' outputs 
* **Spack:** 0.16.1-1677-952f76bda3
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

Does that mean that Spack is using the system-wide Python
[spack-build-env.txt](https://github.com/spack/spack/files/6130877/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6130878/spack-build-out.txt)

?

**Comment by Sinan81** [comment]
That's fine. Spack **is** using system python (as it should) however it is building packages with Spack built python. I will look into this issue over the weekend. Overall, this is an issue with building boost as opposed to alps.

**Comment by Sinan81** [comment]
I've managed to build alps on my laptop where the OS is linux mint which is based on ubuntu 20.04 as shown below.
```
sbulut@storm ~ 
$ spack find -l alps
==> 1 installed package
-- linux-linuxmint20-ivybridge / gcc@8.3.0 ----------------------
xvmn2py alps@2.3.0
sbulut@storm ~ 
$ spack spec /xvmn2py | grep -E 'numpy|scipy|python|boost'
    ^boost@1.63.0%gcc@8.3.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math+mpi+multithreaded+numpy~pic+program_options+python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199,7f95f95be9645eb7f10a7222173c8549501aebbe1db12b955442a7554dc59f3e,d1cd178ea5348fafbba797113fc5a92cc822f3606dc2fe65c14cc2275334001b,fb7d84358c36309062fa4aaaa187343eb16871bd95893f0270e0941955c488ab visibility=hidden arch=linux-linuxmint20-ivybridge
                ^libxml2@2.9.10%gcc@8.3.0~python arch=linux-linuxmint20-ivybridge
        ^py-numpy@1.19.5%gcc@8.3.0+blas+lapack patches=8a9d5d1b3f145c043b8b04869e7d46c6ff95c3f486d84f69693017c7e6190c7d arch=linux-linuxmint20-ivybridge
                ^python@3.6.13%gcc@8.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-linuxmint20-ivybridge
        ^py-python-dateutil@2.8.0%gcc@8.3.0 arch=linux-linuxmint20-ivybridge
    ^py-scipy@1.5.4%gcc@8.3.0 arch=linux-linuxmint20-ivybridge
    ^boost@1.63.0%gcc@8.3.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math+mpi+multithreaded+numpy~pic+program_options+python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199,7f95f95be9645eb7f10a7222173c8549501aebbe1db12b955442a7554dc59f3e,d1cd178ea5348fafbba797113fc5a92cc822f3606dc2fe65c14cc2275334001b,fb7d84358c36309062fa4aaaa187343eb16871bd95893f0270e0941955c488ab visibility=hidden arch=linux-linuxmint20-ivybridge
                ^libxml2@2.9.10%gcc@8.3.0~python arch=linux-linuxmint20-ivybridge
        ^py-numpy@1.19.5%gcc@8.3.0+blas+lapack patches=8a9d5d1b3f145c043b8b04869e7d46c6ff95c3f486d84f69693017c7e6190c7d arch=linux-linuxmint20-ivybridge
                ^python@3.6.13%gcc@8.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-linuxmint20-ivybridge
        ^py-python-dateutil@2.8.0%gcc@8.3.0 arch=linux-linuxmint20-ivybridge
    ^py-scipy@1.5.4%gcc@8.3.0 arch=linux-linuxmint20-ivybridge
```

**Comment by Sinan81** [comment]
I feel like something went wrong in your spack setup, and it might be useful for you to start from scratch:

0. remove `~/.spack` folder
1. clone spack
2. build gcc@8.3.0 as the first thing
3. add gcc@8.3.0 to compilers:
```
spack load gcc@8.3.0
spack compiler find
```
4. Build boost first to see if it works: `spack install boost@1.63.0+python+numpy ^py-numpy@1.19.5 ^python@3.6.13`
5. Build alps: `spack install alps%gcc@8.3.0 ^py-numpy@:1.19 ^py-scipy@:1.5`

**Comment by andredepinhovieira** [comment]
Here's the precise sequence I followed.
$ rm -rf spack .spack/
$ git clone https://github.com/spack/spack.git
$ . /home/apvieira/spack/share/spack/setup-env.sh
$ spack install gcc@8.3.0
$ spack load gcc@8.3.0
$ spack compiler find
$ spack install boost@1.63.0+python+numpy ^py-numpy@1.19.5 ^python@3.6.13

I got the same errors as before. Also, I tried the same sequence in another machine with Ubuntu 20.04, with the same result.

**Comment by Sinan81** [comment]
I forgot to mention that I mean to build boost@1.63.0 with gcc@8.3.0 like:
```
spack install boost@1.63.0%gcc@8.3.0 +python+numpy ^py-numpy@1.19.5 ^python@3.6.13
```
I wonder if this will fix the issue since I remember having build issues with boost@1.63 and gcc@9 (default gcc on ubuntu).

**Comment by Sinan81** [comment]
Also, could you provide more details on the compilers by posting the output of: `cat ~/.spack/linux/compilers.yaml`

**Comment by Sinan81** [comment]
Actually, I just managed to build boost with gcc@9.3 so that is not the issue here it seems. I am running out of ideas here. This is a very bizarre build issue that I haven't seen before. May be official Spack developers might be able to help further. It might be useful to create another issue (with a specific title like 'boost build issue') and provide a link there to this issue.

**Comment by andredepinhovieira** [comment]
Done. Created issue #22291.
Thanks!

**Comment by andredepinhovieira** [comment]
Folllowing the discussion in #22291, I managed to install with
````
spack install alps ^boost@1.63.0+python+numpy cxxstd=11 +icu ^icu4c cxxstd=11 ^py-numpy@1.19.5 ^python@3.6.13
````
