### PR TITLE
Close #1683 Apply ADIOS 1.10.0 Patch (HDF5 1.10+)

### LINKED ISSUE #1683: Adios does not build with HDF5 1.10
The `adios` variant `+hdf5` is broken. The error is
```
In file included from /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/hdf5-1.10.0-patch1-ijwvzsvpcbne33bffg6nrefdwgguofji/include/H5public.h:145:0,
                 from /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/hdf5-1.10.0-patch1-ijwvzsvpcbne33bffg6nrefdwgguofji/include/hdf5.h:24,
                 from bp2h5.c:39:
bp2h5.c:46:13: error: two or more data types in declaration specifiers
 typedef int bool;
             ^
bp2h5.c:46:1: warning: useless type name in empty declaration
 typedef int bool;
 ^~~~~~~
bp2h5.c: In function ‘main’:
bp2h5.c:173:17: warning: implicit declaration of function ‘H5LTmake_dataset’ [-Wimplicit-function-declaration]
                 H5LTmake_dataset(HDF5_FILE,h5name,1,count,h5_type_id,v->value);
                 ^~~~~~~~~~~~~~~~
make[3]: *** [bp2h5-bp2h5.o] Error 1
make[3]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0/utils/bp2h5'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0/utils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0'
```

It seems that Adios expects `bool` to be undefined, but it is already defined. It might be that HDF5 1.10 includes `<stdbool.h>`.

### PR DESCRIPTION
**Pull request by ax3l**
Close #1683: Apply the patch https://github.com/ornladios/ADIOS/commit/3b21a8a41509 for all released ADIOS version up to the latest 1.10.0 which will break when used with HDF5 1.10+.

The bug is already fixed upstream in ADIOS.

### Other Changes

- fix doc strings: `--with-hdf5` (and --`with-netcdf`) are not transports but serial file converters
- remove `bp2ncd` tool: depends on netcdf 3 and is not essential
- hdf5:
  - since `spec['hdf5+mpi'].prefix` does not exist, we only add one `+hdf5` variant,  its building
     - the *parallel* transport `--with-phdf5`
     - the *serial* converter `--with-hdf5`, but also build by `--with-phdf5`
     - building the serial converter alone is intentionally not possible this way and reduces confusion
- add: `develop` version as described `spack_workflows.rst` (the ADIOS development branch is `master`)

see: [official manual, section 2.3](http://users.nccs.gov/%7Epnorbert/ADIOS-UsersManual-1.10.0.pdf)

### Tests
- [x] old fail
```bash
# unpatched version
$ spack install adios +hdf5 # implies currently hdf5 1.10.0-patch1
==> No patches needed for adios
==> Building adios
==> Error: Command exited with status 2:
'make' '-j4'
[...]
  >> 132          make()
[...]
```

- [x] new: only apply patch when necessary
```bash
# old HDF5 version, latest (1.10.0) ADIOS version
$ spack install adios +hdf5 ^hdf5@1.8.16
[...]
==> Created stage in [...]/var/spack/stage/hdf5-1.8.16-[...]
==> No patches needed for hdf5
==> Building hdf5
==> Successfully installed hdf5
[...]
No patches needed for adios
==> Building adios
==> Warning: Patched overlong shebang in [...]opt/spack/linux-debian8-x86_64/gcc-4.9.2/adios-1.10.0-[...]/bin/gpp.py
==> Successfully installed adios
```

- [x] new: apply patch to fix
```bash
# latest versions
$ spack install adios +hdf5 # implies currently hdf5 1.10.0-patch1
[...]
==> Created stage in [...]var/spack/stage/hdf5-1.10.0-patch1-[...]
==> No patches needed for hdf5
==> Building hdf5
==> Successfully installed hdf5
[...]
==> Created stage in [...]/var/spack/stage/adios-1.10.0-[...]
==> Applied patch adios_1100.patch
==> Building adios
==> Warning: Patched overlong shebang in [...]opt/spack/linux-debian8-x86_64/gcc-4.9.2/adios-1.10.0-x6woxnqfn2gzu6smq5xgxtqrglpquowd/bin/gpp.py
==> Successfully installed adios
```

### CODE REVIEW

**Comment by eschnett** [comment]
Note that the original issue also mentions that Adios might require `hdf5 +mpi`; if we close this issue, then we should address that dependency as well.

**Comment by ax3l** [comment]
I just checked the [manual](http://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.10.0.pdf) again and realized it's fine so far. Currently we are only installing serial file converter tools, not the parallel transports that would depend on `hdf5+mpi`.

planning the `hdf5+mpi` option as a feature enhancement in a follow-up.

File: var/spack/repos/builtin/packages/adios/package.py [hunk 1]
```diff
@@ -70,8 +72,14 @@ class Adios(Package):
     depends_on('zlib', when='+zlib')
     depends_on('szip', when='+szip')
     # optional transports
-    depends_on('hdf5', when='+hdf5')
-    depends_on('netcdf', when='+netcdf')
+    # optional serial file converters
+    depends_on('hdf5@1.8:', when='+hdf5')
+    depends_on('netcdf@3', when='+netcdf')
```
Comment (ax3l) [inline var/spack/repos/builtin/packages/adios/package.py]: currently not installed. imho, we can remove this converter for now.

**Comment by ax3l** [comment]
can't finish the tests due to #1701

File: var/spack/repos/builtin/packages/adios/package.py (hunk 1 above)
Comment (ax3l) [inline var/spack/repos/builtin/packages/adios/package.py]: removed now

**Comment by ax3l** [comment]
hdf5 install options simplified to be only `hdf5 +mpi`, having two builds is too confusing

File: var/spack/repos/builtin/packages/adios/package.py [hunk 2]
```diff
@@ -69,9 +71,13 @@ class Adios(Package):
     # optional transformations
     depends_on('zlib', when='+zlib')
     depends_on('szip', when='+szip')
-    # optional transports
-    depends_on('hdf5', when='+hdf5')
-    depends_on('netcdf', when='+netcdf')
+    # optional transports & file converters
+    depends_on('hdf5@1.8: +mpi', when='+hdf5')
```
Comment (davydden) [inline var/spack/repos/builtin/packages/adios/package.py]: `+hdf5+mpi`?

Comment (ax3l) [inline var/spack/repos/builtin/packages/adios/package.py]: did not work without the space somehow, can retry

Comment (ax3l) [inline var/spack/repos/builtin/packages/adios/package.py]: works, must be an artifact. will amend :)
(also have to fix flake8)

**Comment by ax3l** [comment]
@davydden @eschnett all problems of #1683 addressed and fixed :)

**Comment by davydden** [comment]
looks good.

**Comment by ax3l** [comment]
rebased against latest `develop`, pls merge me :)

**Comment by tgamblin** [comment]
@ax3l: thanks!
