### ISSUE TITLE
Fenics doesn't install on Fedora 25

### ISSUE THREAD

**Issue by jayjaybillings** [LLNL/spack#3305]
I'm trying to install Fenics with the latest version of Spack (straight git clone) on Fedora 25. Everything builds except Fenics itself:
```
==> Building fenics [Package]
==> Executing phase : 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
/home/jay/programs/spack-20170228/var/spack/repos/builtin/packages/fenics/package.py:198, in install:
     143      def install(self, spec, prefix):
     144          for package in ['ufl', 'ffc', 'fiat', 'instant']:
     145              with working_dir(join_path('depends', package)):
     146                  setup_py('install', '--prefix=%s' % prefix)
     147  
     148          cmake_args = [
     149              '-DCMAKE_BUILD_TYPE:STRING={0}'.format(
     150                  'Debug' if '+debug' in spec else 'RelWithDebInfo'),
     151              '-DBUILD_SHARED_LIBS:BOOL={0}'.format(
     152                  self.cmake_is_on('+shared')),
     153              '-DDOLFIN_SKIP_BUILD_TESTS:BOOL=ON',
     154              '-DDOLFIN_ENABLE_OPENMP:BOOL={0}'.format(
     155                  self.cmake_is_on('+openmp')),
     156              '-DDOLFIN_ENABLE_CHOLMOD:BOOL={0}'.format(
     157                  self.cmake_is_on('suite-sparse')),
     158              '-DDOLFIN_ENABLE_HDF5:BOOL={0}'.format(
     159                  self.cmake_is_on('hdf5')),
     160              '-DDOLFIN_ENABLE_MPI:BOOL={0}'.format(
     161                  self.cmake_is_on('mpi')),
     162              '-DDOLFIN_ENABLE_PARMETIS:BOOL={0}'.format(
     163                  self.cmake_is_on('parmetis')),
     164              '-DDOLFIN_ENABLE_PASTIX:BOOL={0}'.format(
     165                  self.cmake_is_on('pastix')),
     166              '-DDOLFIN_ENABLE_PETSC:BOOL={0}'.format(
     167                  self.cmake_is_on('petsc')),
     168              '-DDOLFIN_ENABLE_PETSC4PY:BOOL={0}'.format(
     169                  self.cmake_is_on('py-petsc4py')),
     170              '-DDOLFIN_ENABLE_PYTHON:BOOL={0}'.format(
     171                  self.cmake_is_on('python')),
     172              '-DDOLFIN_ENABLE_QT:BOOL={0}'.format(
     173                  self.cmake_is_on('qt')),
     174              '-DDOLFIN_ENABLE_SCOTCH:BOOL={0}'.format(
     175                  self.cmake_is_on('scotch')),
     176              '-DDOLFIN_ENABLE_SLEPC:BOOL={0}'.format(
     177                  self.cmake_is_on('slepc')),
     178              '-DDOLFIN_ENABLE_SLEPC4PY:BOOL={0}'.format(
     179                  self.cmake_is_on('py-slepc4py')),
     180              '-DDOLFIN_ENABLE_SPHINX:BOOL={0}'.format(
     181                  self.cmake_is_on('py-sphinx')),
     182              '-DDOLFIN_ENABLE_TRILINOS:BOOL={0}'.format(
     183                  self.cmake_is_on('trilinos')),
     184              '-DDOLFIN_ENABLE_UMFPACK:BOOL={0}'.format(
     185                  self.cmake_is_on('suite-sparse')),
     186              '-DDOLFIN_ENABLE_VTK:BOOL={0}'.format(
     187                  self.cmake_is_on('vtk')),
     188              '-DDOLFIN_ENABLE_ZLIB:BOOL={0}'.format(
     189                  self.cmake_is_on('zlib')),
     190          ]
     191  
     192          cmake_args.extend(std_cmake_args)
     193  
     194          with working_dir('build', create=True):
     195              cmake('..', *cmake_args)
     196  
     197              make()
  >> 198              make('install')

See build log for details:
  /tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/spack-build.out
```
I'll submit the log file if you want.

**Comment by davydden** [comment]
> I'll submit the log file if you want.

unless you do, nobody can even try to help :smile:

**Comment by davydden** [comment]
> I'll submit the log file if you want.

better yet, just look into it yourself and see what's the error message....

**Comment by alalazo** [comment]
@jayjaybillings I changed the title in a try to make it more informative when looking at the over 450 issues we have. Feel free to change it further or revert it if you don't agree.

**Comment by alalazo** [comment]
Hmm, it's also quite strange that it failed on:
```python
make('install')
```
and passed
```python
make()
```
according to the stack-trace you posted.

**Comment by adamjstewart** [comment]
@alalazo It failed during `make`, not `make install`. This part is reliable:
```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
```
This part is unreliable:
```
     197              make()
  >> 198              make('install')
```
See #3117.

**Comment by jayjaybillings** [comment]
@alalazo I thought so too. 

Full log attached. Looks like it might be a problem with changes in Trilinos?
```
/tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:420:16: error: ‘OrdinalTraits’ is not a member of ‘Tpetra’
   if (ncols == Tpetra::OrdinalTraits<std::size_t>::invalid())
                ^~~~~~
/tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:420:16: note: suggested alternatives:
In file included from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_ConfigDefs.hpp:91:0,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_DefaultPlatform.hpp:46,
                 from /tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraVector.h:33,
                 from /tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:29:
/home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Teuchos_OrdinalTraits.hpp:81:8: note:   ‘Teuchos::OrdinalTraits’
 struct OrdinalTraits {
        ^~~~~~~~~~~~~
In file included from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Details_FixedHashTable_decl.hpp:48:0,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Details_FixedHashTable.hpp:1,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Details_LocalMap.hpp:49,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Map_decl.hpp:50,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Map.hpp:1,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_DistObject_decl.hpp:53,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_DistObject.hpp:1,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_MultiVector_decl.hpp:54,
                 from /home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_MultiVector.hpp:1,
                 from /tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraVector.h:34,
                 from /tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:29:
/home/jay/programs/spack-20170228/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/trilinos-12.10.1-akkr4mrose3qknprbtjgqfbkmgsrmjfh/include/Tpetra_Details_OrdinalTraits.hpp:69:8: note:   ‘Tpetra::Details::OrdinalTraits’
 struct OrdinalTraits {
        ^~~~~~~~~~~~~
/tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:420:49: error: expected primary-expression before ‘>’ token
   if (ncols == Tpetra::OrdinalTraits<std::size_t>::invalid())
                                                 ^
/tmp/jay/spack-stage/spack-stage-3GC0cy/dolfin-2016.1.0/dolfin/la/TpetraMatrix.cpp:420:50: error: ‘::invalid’ has not been declared
   if (ncols == Tpetra::OrdinalTraits<std::size_t>::invalid())
                                                  ^~
[ 63%] Building CXX object dolfin/CMakeFiles/dolfin.dir/log/Event.cpp.o
```
[spack-build.txt](https://github.com/LLNL/spack/files/814711/spack-build.txt)

**Comment by davydden** [comment]
Maybe u need to limit it to older versions of Trilinos?

**Comment by jayjaybillings** [comment]
I'm happy to try that out. Is the process for doing that in the documentation? (I'm relatively new to Spack.)

**Comment by adamjstewart** [comment]
To try out an older version:
```
$ spack install fenics+trilinos ^trilinos@12.8.1
```
To make it permanent, run `spack edit fenics` and edit the following line:
```python
depends_on('trilinos', when='+trilinos')                                    
```
Let's say for example that you discover that fenics works with Trilinos 12.9.0 and older. You would edit the line to become:
```python
depends_on('trilinos@:12.9.0', when='+trilinos')
```

**Comment by jayjaybillings** [comment]
Downgrading the Trilinos version using the first command in @adamjstewart's comment fixed it. Thanks!

**Comment by adamjstewart** [comment]
Feel free to contribute a PR!

**Comment by mpilosov** [comment]
I don't know what happened since but none of the fenics installs work for me at all on Ubuntu.

`
[repos]$ spack install fenics @2016.2.0
==> Error: 'doc'
[repos]$ spack install fenics @2016.1.0
==> Error: 'doc'
[repos]$ spack install fenics @2017.1.0
==> Error: 'doc'
[repos]$ spack install fenics @1.6.0
==> Error: 'doc'
`

## What on earth is it complaining about? no amount of googling has helped such an ambiguous error message.
