### ISSUE TITLE
GCC_INSTALL_PREFIX in llvm+clang not set correctly with system GCC on Ubuntu 20.04

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#17932]
### Steps to reproduce the issue

On Ubuntu 20.04 with the system GCC 9.3.0, LLVM gets built with `-DGCC_INSTALL_PREFIX=/` when the compiler paths are `/bin/gcc` -- which was the default in my case (compilers are added with `spack compiler find`). The correct prefix is `/usr` I guess.

```console
$ cat ~/.spack/linux/compilers.yaml | grep -A5 9.3.0
    spec: gcc@9.3.0
    paths:
      cc: /bin/gcc
      cxx: /bin/g++
      f77: /bin/gfortran
      fc: /bin/gfortran
$ spack install llvm+clang
$ spack load llvm
$ cat main.cc 
#include <iostream>

int main() {
    std::cout << "hello\n";
}

$ clang++ main.cc 
main.cc:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```
### Information on your system

```
$ spack debug report
* **Spack:** 0.15.3-455-7628e33f2
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-zen2-->
```

Error was introduced by https://github.com/spack/spack/pull/12381

Pinging @sethrj 

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
@haampie Can you print the output of `clang -print-search-dirs`?

**Comment by haampie** [comment]
Oof.. I've just uninstalled the broken clang version, and I'm now recompiling from source again with the compiler paths in `~/.spack/linux/compilers.yaml` changed from `/bin/{gcc,g++,gfortran}` to `/usr/bin/{gcc,g++,gfortran}`. I don't think I want to recompile llvm again just to run that command :smile:.

For what it's worth, with my updated compiler paths, the cmake variable is `-DGCC_INSTALL_PREFIX=/usr`, and I guess that is correct.

**Comment by sethrj** [comment]
So does `/bin/gcc` not exist, or is it just a symlink to `/usr/bin/gcc`? Do header files exist at `/include`? Should we add a  runtime assertion in the llvm recipe to check for a directory `$GCC/include/c++`?

Maybe the safest change would be to parse `$CC -print-search-dirs` and use that instead ?

**Comment by haampie** [comment]
So, `/bin/gcc` exists and it's a copy of `/usr/bin/gcc` _not_ a symlink. `spack compiler find` has a bug which changes the order of the directories in `$PATH` s.t. `/bin/gcc` ends up in my `compilers.yaml` while `/usr/bin/gcc` should come first. Let me make a PR for that separately.

I've rebuild clang, it seems the actual search paths were correct (I might have accidentally copied the wrong error -- i was working amd's fork of clang...), but now

```
$ /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-10.0.0-576xf5b5mlqxsskl45ucl3xxxmjxssio/bin/clang++ main.cc 
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
```

The other output:

```
$ clang++ -print-search-dirs
programs: =/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-10.0.0-576xf5b5mlqxsskl45ucl3xxxmjxssio/bin
libraries: =/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-10.0.0-576xf5b5mlqxsskl45ucl3xxxmjxssio/lib/clang/10.0.0:/lib/x86_64-linux-gnu:/lib/../lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/../lib64:/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-10.0.0-576xf5b5mlqxsskl45ucl3xxxmjxssio/bin/../lib:/lib:/usr/lib
```

**Comment by haampie** [comment]
This was fixed
