### PR TITLE
[hepmc3] gcc@9.3.0 patch for @3.1.2:3.2.1, conflicts for earlier @:3.1.1

### PR DESCRIPTION
**Pull request by wdconinc**
Patch is from https://gitlab.cern.ch/hepmc/HepMC3/-/commit/ba38f14d8f56c16cc4105d98f6d4540c928c6150, which is included in upstream master and upstream releases as of hepmc3@3.2.2.

This ensure at least one version of hepmc3 compiles with gcc@9.3.0.

### CODE REVIEW

**Comment by alalazo** [comment]
@vvolkl

**Comment by vvolkl** [comment]
Hi @wdconinc, this seems to be a build failure that is specific to `arch`. It builds fine for me on `linux-ubuntu20.04-broadwell/gcc-9.3.0`. I'm fine with including the patch for all architectures, I'm just checking if it doesn't introduce any errors on ubuntu and centos7. But you should definitely add a restriction for arch linux to the `conflict`.

While you are at it could you add the newest version:
```
version('3.2.2', sha256='0e8cb4f78f804e38f7d29875db66f65e4c77896749d723548cc70fb7965e2d41')
```

**Comment by vvolkl** [comment]
Out of curiosity, is it understood, why this compilation error appears only on arch? Some distro-specific compiler flags?

File: var/spack/repos/builtin/packages/hepmc3/package.py [hunk 1]
```diff
@@ -32,6 +32,9 @@ class Hepmc3(CMakePackage):
     depends_on('root', when='+rootio')
     depends_on('python', when="+python")
 
+    conflicts('%gcc@9.3.0', when="@:3.1.1")
```
Comment (vvolkl) [inline var/spack/repos/builtin/packages/hepmc3/package.py:35]:
```suggestion
    conflicts('%gcc@9.3.0', when="@:3.1.1 os=archrolling")
```

**Comment by wdconinc** [comment]
Although the linked bug report references arch, my issue with gcc@9.3.0 occurred on rhel7 with a gcc@9.3.0 built in spack (rhel7 comes with gcc4.7 or so). I don't have the issue either on my local ubuntu with gcc@9.3.0 system-wide. I posted the link to the upstream bug report because it was the only one referencing the issue and justifies the hepmc3@:3.1.1. 

There is also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952628 which was addressed as a debian-specific patch at https://tracker.debian.org/news/1122068/accepted-gcc-9-930-11-source-into-unstable/. That presumably explains why this works with gcc@9.3.0 in ubuntu.

I could add a specific confict for all systems I can verify this actually fails on.
```
    conflicts('%gcc@9.3.0', when="@:3.1.1 os=rhel7")
```
Thoughts?

**Comment by vvolkl** [comment]
I see! No, if the working build on ubuntu is the exceptional case, then I think it is not worth the effort - since it is anyway working from 3.1.2 upward. So disregard my suggestion, looks good to me as is.

**Review by vvolkl — APPROVED** [review]

**Comment by wdconinc** [comment]
Ok, then I'll just add the new version.

**Review by alalazo — APPROVED** [review]
