### PR TITLE
Improve llnl.util.lang.load_module_from_file

### PR DESCRIPTION
**Pull request by alalazo**
This PR improves `llnl.util.lang.load_module_from_file` in the following ways:
- [x] Put a module object in `sys.modules` before the code of the module is executed to avoid unbounded recursion or reloading.
- [x] Exit early if the module to be constructed is already in `sys.modules`
- [x] Improve test by ensuring that multiple calls to the function will not reload the same module multiple times

### CODE REVIEW

**Comment by alalazo** [comment]
@scottwittenburg If you still have a case at hand failing with:
```
AttributeError: module 'spack.hooks' has no attribute 'sbang'
```
Can you check if this PR "solves" it too?

**Comment by scottwittenburg** [comment]
Thanks @alalazo, I'll keep this in mind for the next time it crops up, but at the moment I am not seeing the `sbang` problem anywhere.  The last place it reared it's head, I took your commit that moved the `sbang` imports to the top level of `binary_distribution.py`, and that seem to "solve" the problem in that case.

But just for that future time when I see it again, would you expect this PR should fix the problem by itself?  Or is #20072 needed as well?

**Comment by alalazo** [comment]
@scottwittenburg They are doing more or less the same thing to `spack.hooks` so my hope is that they both work independently.

**Comment by alalazo** [comment]
Converting to draft since I think for these two cases I can even avoid loading Python modules from file, and fallback to the usual import mechanism. Checking if the "trick" I have in mind is portable across all the Python versions we support.

**Comment by alalazo** [comment]
Split the original PR into three pieces, so updated the description.

**Review by haampie — APPROVED** [review]
