### ISSUE TITLE
Installation issue: r-v8, r-affy, r-hdf5r, r-tictoc, r-prettydoc, r-rpostgresql

### ISSUE THREAD

**Issue by jacorvar** [LLNL/spack#27634]
### Steps to reproduce the issue

My ultimate goal is to install all R packages available in Spack (@glennpj ). For this purpose, I follow these steps:
```sh
$ spack env create r-4_1
$ spacktivate -p r-4_1
$ spack add $(spack list r-*)
```
Then, I add the following to the environment config file:
```yaml
  config:
    install_missing_compilers: true
    concretizer: clingo
    use_curl: true
  concretization: together
  packages:
    r:
      version:
      - 4.1.1
      variants: +X+rmath
```

Finally, I concretize and install packages:

```sh
$ spack -d concretize
$ spack -d install
```

When installing, there are certain packages that fail at building step:

- `r-tictoc`: it seems the error is not related to spack but to the original package: 
[spack-build-out.txt](https://github.com/spack/spack/files/7596255/spack-build-out.txt)
- `r-v8`: the error might be related to spack: 
[spack-build-out.txt](https://github.com/spack/spack/files/7596260/spack-build-out.txt)
- `r-prettydoc`: it complains about requiring `rmarkdown` as a dependency, but it is already installed when I check with `$ spack find`: 
[spack-build-out.txt](https://github.com/spack/spack/files/7596269/spack-build-out.txt)
- `r-hdf5r`: it complains about the `hdf5` installed, but it is indeed correct (hdf5@1.10.7): 
[spack-build-out.txt](https://github.com/spack/spack/files/7596283/spack-build-out.txt)
- `r-affy`: 
[spack-build-out.txt](https://github.com/spack/spack/files/7596300/spack-build-out.txt)
- `r-rpostgresql`: it seems it's a dependency issue:
```sh
==> [2021-11-24-15:14:26.793002] r-rpostgresql: Executing phase: 'install'
==> [2021-11-24-15:14:26.835899] Error: AttributeError: 'RRpostgresql' object has no attribute '_require_build_deps'

/usr/local/spack/lib/spack/spack/build_systems/autotools.py:169, in _do_patch_config_files:
        166        if not to_be_patched:
        167            return
        168
  >>    169        # Otherwise, require `gnuconfig` to be a build dependency
        170        self._require_build_deps(
        171            pkgs=['gnuconfig'],
        172            spec=self.spec,

See build log for details:
  /tmp/jacorvar/spack-stage/spack-stage-r-rpostgresql-0.6-2-esyrp4zl6wyqt4xecqtofismpkzat37n/spack-build-out.txt

Traceback (most recent call last):
  File "/usr/local/spack/lib/spack/spack/build_environment.py", line 1035, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/usr/local/spack/lib/spack/spack/installer.py", line 1952, in build_process
    return installer.run()
  File "/usr/local/spack/lib/spack/spack/installer.py", line 1809, in run
    self._real_install()
  File "/usr/local/spack/lib/spack/spack/installer.py", line 1916, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/usr/local/spack/lib/spack/spack/package.py", line 134, in phase_wrapper
    callback(instance)
  File "/usr/local/spack/var/spack/repos/builtin/packages/r-rpostgresql/package.py", line 38, in patch_config_guess
  File "/usr/local/spack/lib/spack/spack/build_systems/autotools.py", line 170, in _do_patch_config_files
    self._require_build_deps(
AttributeError: 'RRpostgresql' object has no attribute '_require_build_deps'
```

### Information on your system

* **Spack:** 0.17.0-252-5eba5dc271
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by glennpj** [comment]
I will take a look at this in the next couple of days. Based on the error message I think this may be due to some recent changes in how autotools packages are handled.

**Comment by drkrynstrng** [comment]
For the r-hdf5r package, I think the issue is that the Spack hdf5 package switched to a CMake build which does not currently include a `h5cc -showconfig` option, so the configure script for this packages fails. See #27000.

**Comment by glennpj** [comment]
That makes sense for the `r-hdf5r` package. I had to deal with that for another package.

**Comment by glennpj** [comment]
The `r-tictoc@1.0` package will build with `r@:4.0` but fails with `r@4.1:` #27715 will address this.

**Comment by glennpj** [comment]
For the `r-v8` package, the 3.4.0 version does not build with gcc-5 and above. #27714 will address this.

**Comment by glennpj** [comment]
The `r-prettydoc` package has the wrong markdown dependency. 
`r-markdown` --> `r-rmarkdown`
Those are two different packages. This will be fixed in #27791.

**Comment by glennpj** [comment]
The `r-affy` package does not build on `r@4.1:`. I set a constraint in #27792. This is a BioConductor package so this will have to be updated as part of an update of  BioConductor packages in Spack.

**Comment by glennpj** [comment]
@jacorvar Can you see if #27793 fixes `r-rpostgresql` for you?

**Comment by jacorvar** [comment]
> @jacorvar Can you see if #27793 fixes `r-rpostgresql` for you?

I confirm you `r-rpostgresql` becomes successfully installed now. Thanks!

**Comment by glennpj** [comment]
@drkrynstrng Can you see if #27847 works for `r-hdf5r`?

**Comment by jacorvar** [comment]
> @drkrynstrng Can you see if #27847 works for `r-hdf5r`?

#27847 does not solve the issue, at least on my system.

**Comment by drkrynstrng** [comment]
That works for me.

**Comment by glennpj** [comment]
@jacorvar What error are you seeing?

**Comment by jacorvar** [comment]
> @jacorvar What error are you seeing?

I get essentially the same error:
```sh
==> [2021-12-13-12:23:39.129838] Installing r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk
==> [2021-12-13-12:23:39.129933] Searching for binary cache of r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk
==> [2021-12-13-12:23:39.130101] Reading config file /usr/local/spack/etc/spack/defaults/mirrors.yaml
==> [2021-12-13-12:23:40.556528] Did not find linux-ubuntu20.04-skylake-gcc-9.3.0-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk.spec.json on https://mirror.spack.io/build_cache/linux-ubuntu20.04-skylake-gcc-9.3.0-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk.spec.json
  Download failed: HTTP Error 404: Not Found
==> [2021-12-13-12:23:40.556813] Did not find linux-ubuntu20.04-skylake-gcc-9.3.0-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk.spec.json on https://mirror.spack.io/build_cache/linux-ubuntu20.04-skylake-gcc-9.3.0-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-12-13-12:23:40.557853] No binary for r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk found: installing from source
==> [2021-12-13-12:23:40.615701] '/usr/local/spack/var/spack/environments/r-4_1/.spack-env/view/bin/git' 'describe' '--tags' '--match' 'v*'
==> [2021-12-13-12:23:40.831320] Reading config file /usr/local/spack/var/spack/environments/r-4_1/spack.yaml
==> [2021-12-13-12:23:41.301741] Using environment 'r-4_1'
==> [2021-12-13-12:23:41.494500] [TOOLCHAIN] MATCH Gcc
==> [2021-12-13-12:23:41.496701] Adding compiler bin/ paths: /usr/local/spack/lib/spack/env /usr/local/spack/lib/spack/env/case-insensitive /usr/local/spack/lib/spack/env/gcc
==> [2021-12-13-12:23:41.543107] No libraries found for numactl
==> [2021-12-13-12:23:41.788878] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-12-13-12:23:41.792442] '/usr/bin/g++' '-v' '/tmp/spack-implicit-link-infovvl88oeg/main.c' '-o' '/tmp/spack-implicit-link-infovvl88oeg/output'
==> [2021-12-13-12:23:42.174952] parsing implicit link info
==> [2021-12-13-12:23:42.175424] linker line:  /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccljDjoq.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /tmp/spack-implicit-link-infovvl88oeg/output /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. /tmp/ccSW9SBp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
==> [2021-12-13-12:23:42.175519] linkdir: /usr/lib/gcc/x86_64-linux-gnu/9
==> [2021-12-13-12:23:42.175626] linkdir: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu
==> [2021-12-13-12:23:42.175685] linkdir: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib
==> [2021-12-13-12:23:42.175753] linkdir: /lib/x86_64-linux-gnu
==> [2021-12-13-12:23:42.175790] linkdir: /lib/../lib
==> [2021-12-13-12:23:42.175840] linkdir: /usr/lib/x86_64-linux-gnu
==> [2021-12-13-12:23:42.175929] linkdir: /usr/lib/../lib
==> [2021-12-13-12:23:42.175977] linkdir: /usr/lib/gcc/x86_64-linux-gnu/9/../../..
==> [2021-12-13-12:23:42.176053] found raw link dirs: /usr/lib/gcc/x86_64-linux-gnu/9, /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu, /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib, /lib/x86_64-linux-gnu, /lib/../lib, /usr/lib/x86_64-linux-gnu, /usr/lib/../lib, /usr/lib/gcc/x86_64-linux-gnu/9/../../..
==> [2021-12-13-12:23:42.176234] found link dirs: /usr/lib/gcc/x86_64-linux-gnu/9, /usr/lib/x86_64-linux-gnu, /usr/lib, /lib/x86_64-linux-gnu, /lib
==> [2021-12-13-12:23:42.192277] Using cached archive: /usr/local/spack/var/spack/cache/_source-cache/archive/a0/a0f83cbf21563e81dbd1a1bd8379623ed0c9c4df4e094c75013abfd7a5271545.tar.gz
==> [2021-12-13-12:23:42.200693] Staging archive: /tmp/jacorvar/spack-stage/spack-stage-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk/hdf5r_1.3.3.tar.gz
==> [2021-12-13-12:23:42.203588] '/usr/local/spack/var/spack/environments/r-4_1/.spack-env/view/bin/tar' '-oxf' '/tmp/jacorvar/spack-stage/spack-stage-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk/hdf5r_1.3.3.tar.gz'
==> [2021-12-13-12:23:42.328233] Created stage in /tmp/jacorvar/spack-stage/spack-stage-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk
==> [2021-12-13-12:23:42.328570] No patches needed for r-hdf5r
==> [2021-12-13-12:23:42.328671] r-hdf5r: Building r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk [RPackage]
==> [2021-12-13-12:23:42.340601] r-hdf5r: Executing phase: 'install'
==> [2021-12-13-12:23:44.692087] Error: ProcessError: Command exited with status 1:
    '/usr/local/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/r-4.1.1-kshjvhsiwsxip644godgespnkp6t65ei/bin/R' '--vanilla' 'CMD' 'INSTALL' '--library=/usr/local/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk/rlib/R/library' '/tmp/jacorvar/spack-stage/spack-stage-r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk/spack-src'

1 error found in build log:
     46    checking for hdf5_hl.h... no
     47    checking for H5LTpath_valid in -lhdf5_hl... no
     48    configure: WARNING: Unable to compile HDF5_HL test program
     49    checking for main in -lhdf5_hl... no
     50    checking for matching HDF5 Fortran wrapper... no
     51    Found hdf5 with version:
  >> 52    configure: error: The version of hdf5 installed on your system is not sufficient. Please ensure that at least version 1.8.13 is installed
     53    ERROR: configuration failed for package 'hdf5r'
     54    * removing '/usr/local/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/r-hdf5r-1.3.3-mbercn77ubjryiiacfquqe4p4vf3rebk/rlib/R/library/hdf5r'
```

**Comment by glennpj** [comment]
@jacorvar Could you post the output of `spack spec r-hdf5r`?

**Comment by jacorvar** [comment]
> @jacorvar What error are you seeing?

It was a mistake, `r-hdf5r` does work.

**Comment by glennpj** [comment]
@jacorvar Glad to hear that.
