### ISSUE TITLE
spack cmd problem:spack load and spack cd 

### ISSUE THREAD

**Issue by fubingting** [LLNL/spack#22892]
After spack update,there is a problem with spack cmd , when I use spack load,  I can't find the path to load include and library.At the same time, spack cd cannot enter the stage directory, it can only  use spack cd-s.

### Steps to reproduce the issue

```
spack install --keep-stage fann
spack load fann
spack cd -s fann
cd examples
make
```
### Error Message
```
gcc -O3 xor_train.c -o xor_train -lfann -lm
xor_train.c:22:10: fatal error: fann.h: No such file or directory
 #include "fann.h"
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:12: xor_train] Error 1
```

### Information on your system
```
spack debug report
```
```
* **Spack:** 0.16.1-2023-3f7c111e29
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original
```

**Comment by adamjstewart** [comment]
The `spack cd` bug was reported in #22738 and fixed in #22755, this fix will be included in Spack 0.16.2 and 0.17.0, and is already merged in develop.

The `spack load` bug was likely caused by #21699 and #14749. We no longer set `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, `INCLUDE`, or `CPATH` by default. You can add these back in your personal `modules.yaml` file to get around this. Maybe @alalazo or @haampie can comment on why this change was made?

**Comment by fubingting** [comment]
If I want to continue to use it, can I only add lib and lib64,include to etc/spack/defaults/modules.yaml? Is there any other way? @adamjstewart

**Comment by adamjstewart** [comment]
You shouldn't modify `etc/spack/defaults/modules.yaml`, these are the defaults that ship with Spack. You should instead override this at a higher level in the settings hierarchy. See https://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes
