### ISSUE TITLE
Installation issue: root and dependent packages

### ISSUE THREAD

**Issue by tmadlener** [LLNL/spack#41531]
### Steps to reproduce the issue

```console
$ spack install root
```
I suppose it happens with all versions & variants of root, as it is an error in the `sanitize_environments` methods. In my case I have run across this with this specific spec: `root@6.30.02%gcc@12.3.0~aqua~arrow~cuda~cudnn+davix~dcache~emacs+examples+fftw~fits~fortran+gdml+gminimal~graphviz+gsl~http~ipo+math+minuit+mlp~mysql+opengl~oracle~postgres~pythia6+pythia8+python+r+roofit+root7+rpath~shadow~spectrum+sqlite+ssl+tbb+threads+tmva+tmva-cpu~tmva-gpu~tmva-pymva~tmva-sofie+unuran+vc+vdt~veccore~webgui+x+xml+xrootd build_system=cmake build_type=RelWithDebInfo cxxstd=17 generator=make patches=22af347 arch=linux-ubuntu22.04-skylake`

### Error message

There are at least two issues that have been introduced with #41463

<details><summary>Error message 1</summary>

<pre>
```
==> Installing root-6.30.02-wmaetdsnv4p7sqq2y36jcqskrq5wxzac [391/468]
==> No binary for root-6.30.02-wmaetdsnv4p7sqq2y36jcqskrq5wxzac found: installing from source
==> Error: TypeError: EnvironmentModifications.deprioritize_system_paths() got an unexpected keyword argument 'target'

/home/tmadlener/work/spack/var/spack/repos/builtin/packages/root/package.py:798, in sanitize_environments:
        795                kwargs["separator"] = special_separators[var]
        796            env.prune_duplicate_paths(var, **kwargs)
        797            if var == "PATH":
  >>    798                env.deprioritize_system_paths(var, target=target, **kwargs)
        799            else:
        800                env.remove_system_paths(var, **kwargs)
```
</pre></details>

This one is because `EnvironmentModifications.deprioritize_system_paths` doesn't take `target` argument. Simply removing that at least let's me progress, before I hit another one:

<details><summary>Error message 2 (after "fixing" the first)</summary>

<pre>
```
==> Installing root-6.30.02-55wssgfeuzn3qbzvhhmb32myhcf4vwft [121/121]
==> No binary for root-6.30.02-55wssgfeuzn3qbzvhhmb32myhcf4vwft found: installing from source
==> Error: AttributeError: 'EnvironmentModifications' object has no attribute 'remove_system_paths'

The 'root' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/home/tmadlener/work/spack/var/spack/repos/builtin/packages/root/package.py:799, in sanitize_environments:
        796            if var == "PATH":
        797                env.deprioritize_system_paths(var, **kwargs)
        798            else:
  >>    799                env.remove_system_paths(var, **kwargs)


==> Error: root-6.30.02-55wssgfeuzn3qbzvhhmb32myhcf4vwft: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```
</pre></details>

This one is because there is no `remove_system_paths` in `EnvironmentModifications`.

### Information on your system

```console
$spack debug report
* **Spack:** 0.22.0.dev0 (08a88e399f2f1169509a016dd1a7aff9c1948d28)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo
````

(Note that this is `develop` from around yesterday with a few other smaller fixes applied)

### Additional information

Since no build is actually started there are no build logs or build environments yet to upload.

@HadrienG2 @greenc-FNAL @drbenmorgan @gartung @marcmengel @vitodb @vvolkl 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tmadlener** [comment]
This also seems to break packages that depend on root

**Comment by greenc-FNAL** [comment]
My apologies @tmadlener @vvolkl @haampie: we've been using these changes in our fork for so long that I'd forgotten that `sanitize_environments()` takes advantage of a change that I have not yet attempted to port upstream. I'd apparently also forgotten that CI tests don't attempt to build the recipes affected by a PR.

Thanks @gartung for [the PR reversing this change](https://github.com/spack/spack/pull/41544); I will streamline and resubmit the changes that don't require the core improvement.

**Comment by greenc-FNAL** [comment]
Fixed by https://github.com/spack/spack/pull/41544
