### ISSUE TITLE
Installation issue: geopm

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#26003]
### Steps to reproduce the issue

On the Cray system Spock geopm@1.1.0 fails to build with gcc@10.3.0 with numerous errors like:
```
>> 931     src/ProfileTable.hpp:79:45: error: 'string' in namespace 'std' does not name a type
>> 948     src/ProfileTable.hpp:169:77: error: template argument 2 is invalid
>> 1037    src/ProfileTable.cpp:234:10: error: no declaration matches 'bool geopm::ProfileTableImp::name_set(size_t, std::set<std::__cxx11::basic_string<char> >&)'
```

### Information on your system

* **Spack:** 0.16.2-4271-c4e26ac7c8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information

@maiterth
[spack-build-env.txt](https://github.com/spack/spack/files/7180437/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7180438/spack-build-out.txt)
[config.log](https://github.com/spack/spack/files/7180439/config.log)
 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cmcantalupo** [comment]
Thanks for the report.  Unfortunately the last release of geopm was tagged almost 2 years ago, before the gcc toolchain emitted these errors on the GEOPM code base.  I believe all these problems have been fixed in our development branch, but there has also been two years worth of other development done on that branch.

We are restricted from tagging a new release based on our development branch until certain internal Intel security requirements have been met.  I could put together a patch that addresses only these specific build problems in the v1.1.0 release.  It may be possible to create a hotfix for version 1.1.0 (say 1.1.1) that contained only these changes, but I'm actually not sure I can get permission to tag 1.1.1.  Would a patch be sufficient?

**Comment by wspear** [comment]
I think a patch would be fine for our purposes. Thanks!

**Comment by cmcantalupo** [comment]
On a fresh fedora 32 VM I was able to run the commands below after adding the include of string to ProfileTable.hpp:

https://github.com/geopm/geopm/pull/1875

I did disable some parts of the build to enable an easier check on a fresh Fedora VM.  Please let me know if this change is sufficient.  Thanks!


```bash
git clone https://github.com/cmcantalupo/geopm.git
cd geopm
git checkout release-v1.1
sudo yum install automake
sudo yum install libtool
./autogen.sh
sudo yum install gcc-c++
 CC=gcc CXX=g++ ./configure --disable-mpi --disable-openmp --enable-debug --prefix=$HOME/build/geopm --disable-doc
make
make checkprogs
```

**Comment by wspear** [comment]
That patch fixes most of the errors.

With that applied I still get this when installing geopm through spack on spock. It looks like something is returning an empty string for a library name (edited, it was a -l not a -I).
```
     819    libtool: link: /gpfs/alpine/csc439/scratch/wspear/spack/lib/spack/env/gcc/gfortran -shared  -fPIC  src/.libs/libgeopmfort_la-geopm.o src/.libs/libgeopmfort_la-geopm_pmpi_fortran.o   -Wl,-rpath
             -Wl,/tmp/wspear/spack-stage/spack-stage-geopm-1.1.0-yt6fuslbajzjdudfccaffct2qcj652nc/spack-src/.libs -Wl,-rpath -Wl,/opt/cray/pe/gcc/10.3.0/snos/lib/../lib64 -Wl,-rpath -Wl,/gpfs/alpine/csc43
            9/scratch/wspear/spack/opt/spack/cray-sles15-x86_64/gcc-10.3.0/geopm-1.1.0-yt6fuslbajzjdudfccaffct2qcj652nc/lib -Wl,-rpath -Wl,/opt/cray/pe/gcc/10.3.0/snos/lib/../lib64 -L/opt/cray/pe/mpich/8.
            1.7/ofi/gnu/9.1/lib -L/opt/cray/pe/dsmml/0.1.5/dsmml//lib ./.libs/libgeopm.so -L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../lib64 -L/opt/cray/pe/gcc/10.3.0/snos/l
            ib/../lib64 /opt/cray/pe/gcc/10.3.0/snos/lib/../lib64/libstdc++.so /opt/cray/pe/gcc/10.3.0/snos/lib/../lib64/libgomp.so -ldl -lrt -l -L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10
            .3.0 -L/lib/../lib64 -L/usr/lib/../lib64 -L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../.. -lmpifort_gnu_91 -lmpi_gnu_91 -ldsmml -lpthread /opt/cray/pe/gcc/10.3.0/snos/l
            ib/../lib64/libgfortran.so /opt/cray/pe/gcc/10.3.0/snos/lib/../lib64/libquadmath.so -lm -lc -lgcc_s  -fopenmp -msse4.2 -fopenmp -Wl,--as-needed -Wl,-lmpi_gnu_91 -Wl,--no-as-needed -Wl,--as-nee
            ded -Wl,-ldsmml -Wl,--no-as-needed   -fopenmp -Wl,-soname -Wl,libgeopmfort.so.0 -o .libs/libgeopmfort.so.0.0.0
  >> 820    /usr/bin/ld: cannot find -l-L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0
  >> 821    collect2: error: ld returned 1 exit status


```

**Comment by bgeltz** [comment]
@wspear Could you post the full build log for the ```-l-L``` issue?  It's not on line 819 so I'm guessing it happened somewhere higher up.

**Comment by wspear** [comment]
These are from an updated spack/e4s environment on spock
[config.log](https://github.com/spack/spack/files/7238610/config.log)
[spack-build-out.txt](https://github.com/spack/spack/files/7238616/spack-build-out.txt)

:

**Comment by bgeltz** [comment]
I just added some additional fixes around building our Fortran codes to the PR @cmcantalupo started.  It's all here:
https://github.com/geopm/geopm/pull/1875
@wspear any chance you'd be willing to try the build again?

I'm also working through it on my end (SLES 15.2, SPACK 0.16.3-5058-890095e876), but I haven't been able to get to the spot where you're seeing the failure yet.

**Comment by eugeneswalker** [comment]
Was this ever resolved with `geopm@1.1.0` in Spack?  I am seeing the error as documented here: https://github.com/spack/spack/issues/38795. Is Issue#38795 a duplicate?

**Comment by bgeltz** [comment]
The v1.1.0 release of GEOPM is no longer supported.

I'm in the process of re-doing the Spack configuration for GEOPM such that it will build our latest release [v2.0.2](https://github.com/geopm/geopm/releases/tag/v2.0.2).  Additionally, starting with the 2.0 release, GEOPM is divided into 2 components: the service and the runtime.  Those components have separate build processes and requirements.

In the coming weeks I should have a Spack recipe together that will build our latest/greatest.  Once I have that together, I'll put up a pull request and update this issue.

**Comment by iskra-anl** [comment]
@bgeltz I just wanted to add a :+1: as another person interested in an up-to-date GEOPM package in spack. As you might be aware, we have GEOPM installed on some systems at Argonne but integrating that system install with spack (via `packages.yaml`) is proving to be a PITA due to dependencies on other packages (e.g., `libgeopmd.so.1` depends on `libze_loader.so.1`, which does not appear to be in spack either, or is it?).
