### PR TITLE
geant4: patch old versions to work on new compiler/ubuntu

### PR DESCRIPTION
**Pull request by sethrj**
Geant4 10.5 fails to build on `%clang@15.0.7 arch=linux-ubuntu22.04-x86_64_v3`:
```
  >> 10180    /tmp/runner/spack-stage/spack-stage-geant4-10.5.1-otqdtschlfwxt2r
              7upxsgj46nrmolmaz/spack-src/source/persistency/ascii/src/G4tgrEva
              luator.cc:79:10: error: functions that differ only in their retur
              n type cannot be overloaded
     10181    G4double fsqrt( G4double arg ){  return std::sqrt(arg); }
     10182    ~~~~~~~~ ^
     10183    /usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h:36:20: note
              : previous declaration is here
     10184    __MATHCALL_NARROW (__MATHCALL_NAME (sqrt), __MATHCALL_REDIR_NAME2
               (sqrt), 1);
     10185    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              ~~~~~~~~~~~
     10186    /usr/include/math.h:565:32: note: expanded from macro '__MATHCALL
              _NAME'

     ...

     10192    /usr/include/math.h:559:29: note: expanded from macro '__MATHCALL
              _NARROW'
     10193      __MATHCALL_NARROW_NORMAL (func, nargs)
     10194      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
     10195    /usr/include/math.h:554:17: note: expanded from macro '__MATHCALL
              _NARROW_NORMAL'
     10196      extern _Mret_ func __MATHCALL_NARROW_ARGS_ ## nargs __THROW
     10197             ~~~~~~ ^
  >> 10198    /tmp/runner/spack-stage/spack-stage-geant4-10.5.1-otqdtschlfwxt2r
              7upxsgj46nrmolmaz/spack-src/source/persistency/ascii/src/G4tgrEva
              luator.cc:102:3: error: no matching member function for call to '
              setFunction'
     10199      setFunction("sqrt", (*fsqrt));
     10200      ^~~~~~~~~~~
     10201    /opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/
              __spack_path_placeholder__/__spack_path_placeholder__/__spack_p/c
              lhep/2.4.7.1/mhezs7h/include/CLHEP/Evaluator/Evaluator.h:126:8: n
              ote: candidate function not viable: no known conversion from 'flo
              at (double) noexcept(true)' to 'double (*)()' for 2nd argument
     10202      void setFunction(const char * name, double (*fun)());
     10203           ^
     10204    /opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/
              __spack_path_placeholder__/__spack_path_placeholder__/__spack_p/c
              lhep/2.4.7.1/mhezs7h/include/CLHEP/Evaluator/Evaluator.h:136:8: n
              ote: candidate function not viable: no known conversion from 'flo
              at (double) noexcept(true)' to 'double (*)(double)' for 2nd argum
              ent

     ...

     10214      void setFunction(const char * name,
     10215           ^
     10216    /opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/
              __spack_path_placeholder__/__spack_path_placeholder__/__spack_p/c
              lhep/2.4.7.1/mhezs7h/include/CLHEP/Evaluator/Evaluator.h:177:8: n
              ote: candidate function not viable: no known conversion from 'flo
              at (double) noexcept(true)' to 'double (*)(double, double, double
              , double, double)' for 2nd argument
     10217      void setFunction(const char * name,
     10218           ^
     10219    2 errors generated.
  >> 10220    make[3]: *** [source/persistency/CMakeFiles/G4persistency.dir/bui
              ld.make:401: source/persistency/CMakeFiles/G4persistency.dir/asci
              i/src/G4tgrEvaluator.cc.o] Error 1
```

This is fixed by `ascii-V10-07-03` in Geant4 10.7, which I have backported into this patch.

I haven't tested any other compiler/os versions, but I have tested with geant4@10.5 and 10.6, so this PR will definitely fix the PR for the failed cases and not break any old versions (in case the patch doesn't apply).

### CODE REVIEW

**Review by drbenmorgan — APPROVED** [review]
Thanks @sethrj, LGTM!

BTW, as I also mentioned to @wdconinc, you've made a lot of contributions to the package so would you like to add yourself as a maintainer? If you want to, can be done here or in a separate PR.

**Review by vvolkl — APPROVED** [review]
