### ISSUE TITLE
Installation issue: hdfview@3.1.1 ^hdf5@1.10.8

### ISSUE THREAD

**Issue by dylex** [LLNL/spack#28236]
### Steps to reproduce the issue

hdfview (3.1.1, the only version available) fails to build against hdf5@1.10.8 or 1.13.0.  It builds fine with 1.10.7.  I suspect the latest hdfview 3.1.3 may fix this problem, but haven't checked.

### Information on your system

* **Spack:** 0.17.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### Additional information

```
==> hdfview: Executing phase: 'install'
@nix {"action": "setPhase", "phase": "install"}
...
     [echo]      HDF4 version:     4.2.15
     [echo]      HDF5 version:     1.10.8
     [echo]      Operating System: Linux 3.10.0-1160.21.1.el7.x86_64 amd64
     [echo]      Debug Build:      false
     [echo]

compileobj:
...
    [javac] /dev/shm/nix-build-hdfview-3.1.1.drv-0/nixbld1/spack-stage-hdfview-3.1.1-z9j87c2kd1gy4wwrml91mcnmzbddh3nb/spack-src/src/hdf/object/h5/H5File.java:3055: error: incompatible types: String cannot be converted to long
    [javac]         H5.H5export_dataset(file_export_name, file_name, object_path, binary_order);
    [javac]                                               ^
...
    [javac] 1 error

BUILD FAILED
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Julius-Plehn** [comment]
As this package is contributed by me I will at least try to help supporting it in the future.
I had no success with building HDFView with a more recent HDF5 version. Maybe this is not supported as of now. This even holds true for the latest HDFView 3.1.3 version:

> HDFView 3.1.3 is a maintenance release that was built with HDF5-1.10.7, HDF 4.2.15, and Open JDK 15.
-> https://portal.hdfgroup.org/display/HDFVIEW/HDFView

However, I had success building the the latest HDFView 3.1.3 version using HDF5 1.10.7. Somehow there were some rather weird changes required and I will try to push those in the next days.

Down below a current version. It uses an alternative download mirror as the HDF Group mirror is unbelievable slow (https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.1.3/src/hdfview-3.1.3.tar.gz)
Hashes have been compared

        # Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
        # Spack Project Developers. See the top-level COPYRIGHT file for details.
        #
        # SPDX-License-Identifier: (Apache-2.0 OR MIT)
        
        import os
        
        from spack import *
        
        
        class Hdfview(Package):
            """HDFView is a visual tool written in Java for browsing
            and editing HDF (HDF5 and HDF4) files."""
        
            homepage = "https://www.hdfgroup.org/downloads/hdfview/"
            url      = "https://s3.amazonaws.com/hdf-wordpress-1/wp-content/uploads/manual/HDFView/hdfview-3.0.tar.gz"
        
            version('3.1.3', sha256='566807495305a32d3da65539a529f268fcfc375e6da32ed07c2b5723b9aa0c66',
                    url='https://sid.ethz.ch/debian/hdfview/hdfview-3.1.3.tar.gz')
            version('3.1.1', sha256='1cfd127ebb4c3b0ab1cfe54649a410fc7a1c2d73f45564697d3729f4aa6b0ba3',
                    url='https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.1.1/src/hdfview-3.1.1.tar.gz')
            version('3.0', sha256='e2a16d3842d8947f3d4f154ee9f48a106c7f445914a9e626a53976d678a0e934')
        
            # unknown flag: --ignore-missing-deps
            patch('fix_build.patch', when='@3.1.1')
        
            depends_on('ant', type='build')
            depends_on('hdf5 +java')
            depends_on('hdf +java -external-xdr +shared')
        
            def install(self, spec, prefix):
                env['HDF5LIBS'] = spec['hdf5'].prefix
                env['HDFLIBS'] = spec['hdf'].prefix
        
                ant = which('ant')
                ant('-Dbuild.debug=false', 'deploy')
        
                dir_version = os.listdir('build/HDF_Group/HDFView/')[0]
                path = 'build/HDF_Group/HDFView/{0}/'.format(dir_version)
                hdfview = '{0}/{1}'.format(path, 'hdfview.sh')
                
                filter_file(
                    r'\$dir',
                    prefix,
                    hdfview
                )
                
                filter_file(
                    r'\$INSTALLDIR/lib/runtime',
                    spec['java'].prefix,
                    hdfview
                )
        
                filter_file(
                    r'lib/app',
                    '',
                    hdfview
                )
        
                mkdirp(prefix.bin)
                install(hdfview, prefix.bin.hdfview)
                chmod = which('chmod')
                chmod('+x', self.prefix.bin.hdfview)
                install_tree(path, prefix)

**Comment by ghost** [comment]
I'm not the maintainer of this package but I use it a lot and managed to get the latest version running.  Note that the executable is now `HDFView` and not `hdfview`.  I didn't submit the changes yet because I'm using the `createJPackage` option in the ant builder.  This option copies over the entire java runtime to the install folder (84M), which isn't really necessary.  I think it would take some fiddling with the build system to avoid that but I don't have time at the moment to fix it.

```
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import os

from spack import *


class Hdfview(Package):
    """HDFView is a visual tool written in Java for browsing
    and editing HDF (HDF5 and HDF4) files."""

    homepage = "https://www.hdfgroup.org/downloads/hdfview/"
    url      = "https://s3.amazonaws.com/hdf-wordpress-1/wp-content/uploads/manual/HDFView/hdfview-3.0.tar.gz"

    version('3.1.3', sha256='566807495305a32d3da65539a529f268fcfc375e6da32ed07c2b5723b9aa0c66',
            url='https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.1.3/src/hdfview-3.1.3.tar.gz')
    version('3.1.1', sha256='1cfd127ebb4c3b0ab1cfe54649a410fc7a1c2d73f45564697d3729f4aa6b0ba3',
            url='https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.1.1/src/hdfview-3.1.1.tar.gz')
    version('3.0', sha256='e2a16d3842d8947f3d4f154ee9f48a106c7f445914a9e626a53976d678a0e934')

    # unknown flag: --ignore-missing-deps
    patch('fix_build.patch', when='@3.1.1')

    depends_on('ant', type='build')
    depends_on('hdf5 +java')
    depends_on('hdf +java -external-xdr +shared')

    def install(self, spec, prefix):
        env['HDF5LIBS'] = spec['hdf5'].prefix
        env['HDFLIBS'] = spec['hdf'].prefix
        env['JAVA_HOME'] = spec['java'].prefix
        env['ANT_HOME'] = spec['ant'].prefix

        ant = which('ant')
        #ant('-Dbuild.debug=false', 'deploy')
        ant('-Dbuild.debug=false', 'createJPackage')
        # Create a binaryAppPackage if you want a tarball, README, and COPYING
        # junit will run some of the tests
        #ant('-Dbuild.debug=false', 'junit')

        install_tree('build/dist/HDFView', prefix)
```
