### PR TITLE
Matplotlib Python package overhaul

### PR DESCRIPTION
**Pull request by adamjstewart**
This is an overhaul of the Matplotlib Python package. I noticed that half of its dependencies were missing and half of the dependencies listed aren't actually dependencies. As a start, I only included dependencies listed in the [Matplotlib installation instructions](http://matplotlib.org/users/installing.html#build-requirements).

For some reason I can't get most of the `+gui` dependencies to build, so someone may need to help me on that. Some of the non-documented dependencies that I removed may actually be important (is py-nose important for testing?) so if you think I removed something that needs to be there just let me know.

### CODE REVIEW

File: var/spack/repos/builtin/packages/py-matplotlib/package.py [hunk 1]
```diff
@@ -23,57 +23,61 @@
...
-    depends_on('py-funcsigs')
+    depends_on('freetype@2.3:')
+    depends_on('py-cycler@0.9:')
+    # depends_on('py-tornado')
+
+    # Optional GUI framework
+    depends_on('tk@8.3:',       when='+gui')
+    depends_on('py-pyqt@4.0:',  when='+gui')
+    depends_on('pygtk@2.4:',    when='+gui')
+    depends_on('wxPython@2.8:', when='+gui')
```
Comment (mathstuf) [inline var/spack/repos/builtin/packages/py-matplotlib/package.py]: Eh. That's a *lot* of code to build if you want just one of these. Is the toolkit used exposed in matplotlib at all or is it just an implementation detail (and therefore we can just "choose one" and not create this massive dependency tree)?

File: var/spack/repos/builtin/packages/wxPython/package.py [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+    homepage = "http://www.wxpython.org/"
+    url = "http://downloads.sourceforge.net/wxpython/wxPython-src-3.0.2.0.tar.bz2"
+
+    version('3.0.2.0', '922b02ff2c0202a7bf1607c98bbbbc04')
+
+    depends_on('python')
+    depends_on('libpng')
+    depends_on('zlib')
+    depends_on('jpeg')
+    depends_on('libtiff')
```
Comment (mathstuf) [inline var/spack/repos/builtin/packages/wxPython/package.py]: This doesn't `depends_on` wx at all?

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/wxPython/package.py]: Not according to the [build instructions](http://www.wxpython.org/builddoc.php)? I'm honestly not sure. I have a million other installations I'm working on right now, but if you want to test the install with and without we could know for certain.

File: var/spack/repos/builtin/packages/py-matplotlib/package.py (hunk 1 above)
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-matplotlib/package.py]: Haha, that's why `+gui` is off by default. But I can see why this makes you cringe. According to the [backend documentation](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend), it looks like you're right. I think you can choose any one of these to use as your backend.

What do you think we should do? We could split each of these into a separate variant. I'm not sure whether they are build dependencies or runtime dependencies, but from the previous file filtering in the package, I have a feeling that they need to be present and be set in that config file. This makes it sound like they are mutually exclusive.

File: var/spack/repos/builtin/packages/wxPython/package.py (hunk 2 above)
Comment (mathstuf) [inline var/spack/repos/builtin/packages/wxPython/package.py]: Those instructions build wxWidgets and Python (like a `+python` variant to the existing `wx` package). It appears (based on [Fedora's build](https://pkgs.fedoraproject.org/cgit/rpms/wxPython.git/tree/wxPython.spec)) that instead, the `wxPython/setup.py` should be used to build the Python bindings. This needs to do `setup.py WX_CONFIG=/usr/bin/wx-config-3.0 WXPORT=gtk3 build` to use the depended-on `wx`.

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/wxPython/package.py]: Can't view the link for some reason, but that seems like a reasonable solution. I'll integrate it at some point. But I have a lot of PRs open right now and this is at the end of my priorities list.

File: var/spack/repos/builtin/packages/py-matplotlib/package.py (hunk 1 above)
Comment (mathstuf) [inline var/spack/repos/builtin/packages/py-matplotlib/package.py]: Hrm. Wasn't there a question about "variants with values" before (e.g., `+gui=tk` or something)? This would be another place that would make sense. Maybe this should just be opinionated and pick one with the others commented out and a comment describing how the others could matter. As for being mutually exclusive, it seems like they are indeed during a single run, but a single build can support multiple backends. Looks like Fedora [makes subpackages](https://pkgs.fedoraproject.org/cgit/rpms/python-matplotlib.git/tree/python-matplotlib.spec) for each backend, but defaults to the Tk backend. Looks like Debian just [throws them all together](https://packages.debian.org/sid/amd64/python-matplotlib/filelist) and uses `Suggests` to deal with the problem. Personally, I'd be fine with Spack just saying "we're going to use Tk" for now. Are there any real differences between the backends?

File: var/spack/repos/builtin/packages/wxPython/package.py (hunk 2 above)
Comment (mathstuf) [inline var/spack/repos/builtin/packages/wxPython/package.py]: There's some SSL cert problem. Here's the relevant bits:

```spec
%global py_setup_args WX_CONFIG=/usr/bin/wx-config-3.0 WXPORT=gtk3

%build
cd wxPython
%py2_build
```

which turns into:

```
/usr/bin/python2 setup.py WX_CONFIG=/usr/bin/wx-config-3.0 WXPORT=gtk3 build '--executable=/usr/bin/python2 -s'
```

File: var/spack/repos/builtin/packages/py-matplotlib/package.py (hunk 1 above)
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-matplotlib/package.py]: > Hrm. Wasn't there a question about "variants with values" before (e.g., +gui=tk or something)? This would be another place that would make sense.

I would **love** for this features to be added. Especially for the MPI packages.

I don't really build the GUI stuff, so it doesn't matter to me. I'm willing to wait on this PR until we come up with an agreed upon solution. I don't want too much churn on important packages like this.

**Comment by citibeth** [comment]
Can we simulate variants-with-values with boolean variants?  For example, we can have variant +gui_wx, +gui_gtk, +gui_tk, etc.  If they are mutually exclusive, the Package can check that no more than one is set.

**Comment by mathstuf** [comment]
That's probably a decent solution as well.

**Comment by adamjstewart** [comment]
@citibeth: Yeah, we could have a variant for each one, but I would really like variants with values in the long run. Especially for something like MPI, where you have several mutually exclusive network types and process managers. It's a lot of work to check that only one variant is activated in the package. Variants with values would be awesome.

But we don't have that available to us right now, and I don't want to incorporate that into this PR. That sounds like a major change. I'll open another Issue about that so others can discuss it. I think @alalazo might have posted something in the Google Group about this awhile back.

**Comment by citibeth** [comment]
I agree, multi-valued variants is the right way in the long run.  My
suggestion was something that can be done now, without changing Spack.

**Comment by tgamblin** [comment]
@adamjstewart: is this ready?

**Comment by adamjstewart** [comment]
@tgamblin not even close :smile:

**Comment by citibeth** [comment]
About the GUI stuff... I install py-matplotlib with the line: `spack install py-basemap ^py-matplotlib+gui+ipython ^py-numpy+blas+lapack ^openblas ^python@3:`.  That gives me the following concretized spec:
```
Concretized
------------------------------
  py-basemap@1.0.7%gcc@4.9.3 arch=linux-x86_64
      ^geos@3.5.0%gcc@4.9.3 arch=linux-x86_64
      ^py-matplotlib@1.4.3%gcc@4.9.3+gui+ipython arch=linux-x86_64
          ^binutils@2.26%gcc@4.9.3+gold~krellpatch~libiberty arch=linux-x86_64
              ^bison@3.0.4%gcc@4.9.3 arch=linux-x86_64
                  ^m4@1.4.17%gcc@4.9.3+sigsegv arch=linux-x86_64
                      ^libsigsegv@2.10%gcc@4.9.3 arch=linux-x86_64
              ^flex@2.6.0%gcc@4.9.3 arch=linux-x86_64
          ^bzip2@1.0.6%gcc@4.9.3 arch=linux-x86_64
          ^freetype@2.5.3%gcc@4.9.3 arch=linux-x86_64
              ^libpng@1.6.16%gcc@4.9.3 arch=linux-x86_64
                  ^zlib@1.2.8%gcc@4.9.3 arch=linux-x86_64
          ^pkg-config@0.28%gcc@4.9.3 arch=linux-x86_64
          ^py-dateutil@2.5.2%gcc@4.9.3 arch=linux-x86_64
              ^py-setuptools@20.7.0%gcc@4.9.3 arch=linux-x86_64
                  ^python@3.5.1%gcc@4.9.3 arch=linux-x86_64
                      ^ncurses@6.0%gcc@4.9.3 arch=linux-x86_64
                      ^openssl@system%gcc@4.9.3 arch=linux-x86_64
                      ^readline@6.3%gcc@4.9.3 arch=linux-x86_64
                      ^sqlite@3.8.5%gcc@4.9.3 arch=linux-x86_64
              ^py-six@1.10.0%gcc@4.9.3 arch=linux-x86_64
          ^py-funcsigs@0.4%gcc@4.9.3 arch=linux-x86_64
          ^py-ipython@3.1.0%gcc@4.9.3 arch=linux-x86_64
              ^py-pygments@2.0.2%gcc@4.9.3 arch=linux-x86_64
          ^py-mock@1.3.0%gcc@4.9.3 arch=linux-x86_64
              ^py-pbr@1.8.1%gcc@4.9.3 arch=linux-x86_64
          ^py-nose@1.3.7%gcc@4.9.3 arch=linux-x86_64
          ^py-numpy@1.11.0%gcc@4.9.3+blas+lapack arch=linux-x86_64
              ^openblas@0.2.18%gcc@4.9.3+fpic~openmp+shared arch=linux-x86_64
          ^py-pyparsing@2.0.3%gcc@4.9.3 arch=linux-x86_64
          ^py-pyside@1.2.4%gcc@4.9.3 arch=linux-x86_64
              ^cmake@3.5.2%gcc@4.9.3~doc+ncurses+openssl~qt arch=linux-x86_64
              ^qt@system%gcc@4.9.3~gtk~krellpatch~mesa arch=linux-x86_64
          ^py-pytz@2016.3%gcc@4.9.3 arch=linux-x86_64
          ^qhull@7.2.0%gcc@4.9.3 arch=linux-x86_64
          ^tcl@8.6.5%gcc@4.9.3 arch=linux-x86_64
          ^tk@8.6.3%gcc@4.9.3 arch=linux-x86_64
      ^py-pillow@3.0.0%gcc@4.9.3~freetype+jpeg~lcms~tiff~tk+zlib arch=linux-x86_64
          ^jpeg@9b%gcc@4.9.3 arch=linux-x86_64
```
I avoid running down the Qt rabbit hole by using system-installed versions of Qt (see `packages.yaml`):
```
    # sudo yum install qt-devel tcl-devel tk-devel
    qt:
        paths:
            qt@system: /usr
        buildable: False
```
I'm willing to view GUI toolkits as part of the provided OS, and not something we really need to build ourselves (unless they're so old they don't work).

**Comment by citibeth** [comment]
@tgamblin How would multi-value variants interact with the PROLOG-like concretizers you are looking at?

**Comment by adamjstewart** [comment]
Sorry this has been put on the back burner. I just got a user who requested a newer version of Matplotlib, so I'm going to revive this PR. I'll probably strip out all of the GUI changes and let someone else handle those. @lee218llnl has already started a separate PR for many of the GUI dependencies in #1379.

File: var/spack/repos/builtin/packages/qhull/package.py [hunk 3]
```diff
@@ -36,16 +37,13 @@ class Qhull(Package):
 
     homepage = "http://www.qhull.org"
 
-    version('7.2.0', 'e6270733a826a6a7c32b796e005ec3dc',
+    version('2015.2', 'e6270733a826a6a7c32b796e005ec3dc',
             url="http://www.qhull.org/download/qhull-2015-src-7.2.0.tgz")
 
-    version('1.0', 'd0f978c0d8dfb2e919caefa56ea2953c',
+    version('2012.1', 'd0f978c0d8dfb2e919caefa56ea2953c',
             url="http://www.qhull.org/download/qhull-2012.1-src.tgz")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/qhull/package.py]: Although each version actually has a build number (1.0 should be 6.3.1.1494), most packages refer to the qhull version by its year. This includes the [qhull downloads page](http://www.qhull.org/download/).

File: var/spack/repos/builtin/packages/qhull/package.py [hunk 4]
```diff
@@ -36,16 +37,13 @@ class Qhull(Package):
...
 
-    # https://github.com/qhull/qhull/pull/5
-    patch('qhull-iterator.patch', when='@1.0')
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/qhull/package.py]: The patch that @mathstuf wrote no longer works for either version of qhull in Spack so I removed it. I have a feeling the developers applied the patch to 2012.1 and re-released it without telling anyone. See discussion in #420.

File: var/spack/repos/builtin/packages/ImageMagick/package.py [hunk 5]
```diff
@@ -26,38 +26,25 @@
...
+    homepage = "http://www.imagemagick.org"
+    url      = "http://www.imagemagick.org/download/ImageMagick-7.0.2-6.tar.gz"
 
-    # -------------------------------------------------------------------------
-    # *-10 versions are archived, so these versions should fetch reliably.
-    # -------------------------------------------------------------------------
-    version(
-        '6.8.9-10',
-        'aa050bf9785e571c956c111377bbf57c',
-        url="http://sourceforge.net/projects/imagemagick/files/old-sources/6.x/6.8/ImageMagick-6.8.9-10.tar.gz/download")
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: The old version no longer exists. Updated to the latest version.

**Comment by adamjstewart** [comment]
I'm still having trouble getting the latest version of qt to build. It crashes with the following error message:
```
qevdevgamepadbackend.cpp: In member function ‘void QEvdevGamepadDevice::resetConfiguration()’:
qevdevgamepadbackend.cpp:265:18: error: ‘BTN_TRIGGER_HAPPY1’ was not declared in this scope
     m_buttonsMap[BTN_TRIGGER_HAPPY1] = QGamepadManager::ButtonLeft;
                  ^~~~~~~~~~~~~~~~~~
qevdevgamepadbackend.cpp:266:18: error: ‘BTN_TRIGGER_HAPPY2’ was not declared in this scope
     m_buttonsMap[BTN_TRIGGER_HAPPY2] = QGamepadManager::ButtonRight;
                  ^~~~~~~~~~~~~~~~~~
qevdevgamepadbackend.cpp:267:18: error: ‘BTN_TRIGGER_HAPPY3’ was not declared in this scope
     m_buttonsMap[BTN_TRIGGER_HAPPY3] = QGamepadManager::ButtonUp;
                  ^~~~~~~~~~~~~~~~~~
qevdevgamepadbackend.cpp:268:18: error: ‘BTN_TRIGGER_HAPPY4’ was not declared in this scope
     m_buttonsMap[BTN_TRIGGER_HAPPY4] = QGamepadManager::ButtonDown;
                  ^~~~~~~~~~~~~~~~~~
```
Maybe we'll have to patch `qtgamepad/src/plugins/gamepads/evdev/qevdevgamepadbackend.cpp`? I don't see a way to skip this particular build, but I don't know much about qt.

**Comment by citibeth** [comment]
Does this help?

https://github.com/xboxdrv/xboxdrv/issues/188

File: var/spack/repos/builtin/packages/pcre/package.py [hunk 6]
```diff
@@ -32,10 +32,10 @@ class Pcre(Package):
     homepage = "http://www.pcre.org"""
     url      = "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.bz2"
 
-    version('8.36', 'b767bc9af0c20bc9c1fe403b0d41ad97')
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/pcre/package.py]: No longer available for download.

File: var/spack/repos/builtin/packages/pcre/package.py [hunk 7]
```diff
@@ -32,10 +32,10 @@ class Pcre(Package):
...
+    version('8.39', 'e3fca7650a0556a2647821679d81f585')
     version('8.38', '00aabbfe56d5a48b270f999b508c5ad2')
 
-    patch("intel.patch")
+    patch("intel.patch", when='@8.38')
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/pcre/package.py]: Must have been patched in source code for latest version.

**Comment by adamjstewart** [comment]
@citibeth The patch you found works, thanks!

Now I have a new bug:
```
In file included from ../3rdparty/javascriptcore/JavaScriptCore/runtime/RegExp.h:30:0,
                 from ../3rdparty/javascriptcore/JavaScriptCore/bytecode/CodeBlock.h:40,
                 from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.cpp:32:
../3rdparty/javascriptcore/JavaScriptCore/yarr/RegexJIT.h: In destructor ‘QTJSC::Yarr::RegexCodeBlock::~RegexCodeBlock()’:
../3rdparty/javascriptcore/JavaScriptCore/yarr/RegexJIT.h:65:36: error: ‘jsRegExpFree’ was not declared in this scope
             jsRegExpFree(m_fallback);
                                    ^
In file included from ../3rdparty/javascriptcore/JavaScriptCore/runtime/RegExp.h:30:0,
                 from ../3rdparty/javascriptcore/JavaScriptCore/bytecode/CodeBlock.h:40,
                 from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.cpp:32:
../3rdparty/javascriptcore/JavaScriptCore/yarr/RegexJIT.h: In function ‘int QTJSC::Yarr::executeRegex(QTJSC::Yarr::RegexCodeBlock&, const UChar*, unsigned int, unsigned int, int*, int)’:
../3rdparty/javascriptcore/JavaScriptCore/yarr/RegexJIT.h:89:88: error: ‘jsRegExpExecute’ was not declared in this scope
         return (jsRegExpExecute(fallback, input, length, start, output, outputArraySize) < 0) ? -1 : output[0];
                                                                                        ^
```
Let me know if anyone has any ideas on this one. In the meantime, I'll see if I can add a JavaScript dependency instead of using the JavaScript that comes with Qt.

**Comment by adamjstewart** [comment]
I think the problem is actually that I'm trying to build WebKit when I shouldn't be. `-skip qtwebkit` no longer works in 5.7.0, so I have to figure out what the correct option flag is.

**Comment by mathstuf** [comment]
Look for `qtwebengine`. It is based on Blink (QtWebKit is an ancient version of WebKit).

**Comment by adamjstewart** [comment]
I tried building Qt 1.5.1 but ran into the same JavaScript problem, so it's not a problem of not skipping qtwebkit (I imagine that qtwebengine is the same).

**Comment by adamjstewart** [comment]
Turned out the problem was with PCRE. I found [this post](https://code.google.com/p/android/issues/detail?id=4597#makechanges) in which the author realized that the problem was incompatible PCRE code that was being linked in. Glib now depends on PCRE, and Qt depended on glib. When I commented out the glib dependency, everything built fine.

**Comment by adamjstewart** [comment]
Well, Qt 5.7.0 builds fine now. The only problem is that py-matplotlib depends on py-pyside, which requires Qt 4.8.6, which I can't get to build with GCC 6.1.0. I'm seeing dozens of error messages like this:
```
../3rdparty/javascriptcore/JavaScriptCore/wtf/TypeTraits.h:173:69: error: ‘std::tr1’ has not been declared
     template<typename T> struct HasTrivialConstructor : public std::tr1::has_trivial_constructor<T> { };
                                                                     ^~~
../3rdparty/javascriptcore/JavaScriptCore/wtf/TypeTraits.h:173:74: error: expected ‘{’ before ‘has_trivial_constructor’
     template<typename T> struct HasTrivialConstructor : public std::tr1::has_trivial_constructor<T> { };
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
```
I'm going to try using an older compiler. Let me know if anyone knows of any solutions to this error message.

**Comment by adamjstewart** [comment]
Found [this useful solution](http://stackoverflow.com/questions/10354371/stdtr1-has-not-been-declared). Going to try it now.

**Comment by citibeth** [comment]
My guess is qt is using pre C++11 stuff that has been deprecated in newer
gcc

**Comment by adamjstewart** [comment]
Alright, all versions of Qt install successfully for me now. I tried installing the latest version of py-pyside, but it's not working. PySide comes with Shiboken and generates libraries for both, but the libpyside library can't find libshiboken (even though it's in the same directory). I tried commenting out the rpath patch we use in py-pyside, but if I do that the libraries does rpath to Shiboken but not to any of the other dependencies like Qt. I also tried telling py-pyside to depend on py-shiboken, but that didn't add it to the rpath either. I think I'm going to comment out the newer version of py-pyside and just use the older version which seems to be working fine.

**Comment by adamjstewart** [comment]
I'm happy to announce that this PR is finally ready for review. I just installed `py-matplotlib@1.5.1+gui` and it passes with flying colors.

**Comment by citibeth** [comment]
Wow, thanks for a big job!  Upon code review, my comments are below.

1. It looks like support for TkAgg backend is being removed?  I currently use that backend with my Spack-built matplotlib, and it's a lot simpler to build than Qt.  Is there a need to remove TkAgg support?

2. If we keep more than one backend option, maybe the variant should be called `+qt`, `+tk`, etc. instead of `+gui`.

3. 
```
+        # TODO: rpath handling for PySide 1.2.4 still doesn't work.
+        # PySide can't find the Shiboken library, even though it comes
+        # bundled with it and is installed in the same directory.
```
It is my belief that Python extensions are rarely/never built with RPATH in Spack.  This is something that could/should be fixed.  In the meantime, I make sure to `spack load` all the Python modules I need, along with their dependencies.

4.
```
+    # Note: Only works if ForwardX11Trusted is enabled, i.e. `ssh -Y`
```
Can you elaborate on this?  Does this mean it doesn't work with `ssh -X`?  Why not?  (My current TkAgg solution works just fine with `ssh -X`).  In any case... the use of `ssh -Y` is highly discouraged / forbidden at many sites.  Requiring it will not work.

5. 
```
Although each version actually has a build number (1.0 should be 6.3.1.1494), most packages refer to the qhull version by its year. This includes the qhull downloads page.
```
Can you put this in the `package.py` file itself?

**Comment by adamjstewart** [comment]
@citibeth What do you see that leads you to believe that support for TkAgg backend is being removed? That was not my intention.

**Comment by adamjstewart** [comment]
>  ```
# Note: Only works if ForwardX11Trusted is enabled, i.e. `ssh -Y`
```
> 
Can you elaborate on this? Does this mean it doesn't work with `ssh -X`? Why not? (My current TkAgg solution works just fine with `ssh -X`). In any case... the use of `ssh -Y` is highly discouraged / forbidden at many sites. Requiring it will not work.

I tried `ssh -X` and it didn't work for me:
```
$ ssh -X blues
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
$ python
Python 2.7.12 (default, Jul 21 2016, 15:23:03) 
[GCC 6.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> import Tkinter
>>> Tkinter._test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-hfkksvc2jgtlvkjagr33k6khrnj7yfqt/lib/python2.7/lib-tk/Tkinter.py", line 3832, in _test
    root = Tk()
  File "/soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-hfkksvc2jgtlvkjagr33k6khrnj7yfqt/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
`ssh -Y` did work. Note that this is only for testing purposes. It isn't actually required to build or run.

**Comment by citibeth** [comment]
On Thu, Aug 11, 2016 at 1:12 PM, Adam J. Stewart <notifications@github.com>
wrote:

> # Note: Only works if ForwardX11Trusted is enabled, i.e. `ssh -Y`
>
> Can you elaborate on this? Does this mean it doesn't work with ssh -X?
> Why not? (My current TkAgg solution works just fine with ssh -X). In any
> case... the use of ssh -Y is highly discouraged / forbidden at many
> sites. Requiring it will not work.
>
> I tried ssh -X and it didn't work for me:
>

It works for me, due to my configuration.  See:

http://stackoverflow.com/questions/27384725/ssh-x-warning-untrusted-x11-forwarding-setup-failed-xauth-key-data-not-gener

I would suggest that the `ssh -Y` advice is removed from the Spack package,
and instead instructions from the above URL are put in its place.

I agree, nothing wrong with the building and runnign here.

**Comment by citibeth** [comment]
OK, my bad, just didn't spend enough time looking at the PR.

The issue I DO see is that now you either get Tk+Qt together, or neither.
What if I want to build with Tk but not be bothered with the more complex
Qt build?

Also, I'm wondering why the patches to the default `matplotlibrc`?

**Comment by adamjstewart** [comment]
@citibeth I use the same configuration. `ForwardX11Trusted yes` == `ssh -Y`...

**Comment by adamjstewart** [comment]
> The issue I DO see is that now you either get Tk+Qt together, or neither.
> What if I want to build with Tk but not be bothered with the more complex Qt build?
> 
> Also, I'm wondering why the patches to the default `matplotlibrc`?

This is how things were before. Trust me, I would love nothing more than to ditch Qt. But trying to muck with GUI support is the reason this PR started to stagnate originally. I honestly don't know how Matplotlib's GUI support works well enough to handle that. I think we should wait until this PR and @lee218llnl's #1379 are merged and then someone else can start a new PR to revamp GUI support.

**Comment by adamjstewart** [comment]
By the way, sorry for reordering matplotlib's dependencies. I know it makes it super confusing to see which dependencies were added and which were removed. They were in a seemingly random order, so I tried organizing them in the same order as the [Matplotlib installation instructions](http://matplotlib.org/users/installing.html#required-dependencies).

File: var/spack/repos/builtin/packages/ImageMagick/package.py [hunk 8]
```diff
@@ -26,38 +26,25 @@
...
-    # fetch a newer version (-6, -7, -8, -9, etc.) or you can stick
-    # wtih the older, stable, archived -10 versions below.
-    #
-    # TODO: would be nice if spack had a way to recommend avoiding a
-    # TODO: bleeding edge version, but not comment it out.
-    # -------------------------------------------------------------------------
-    # version('6.9.0-6', 'c1bce7396c22995b8bdb56b7797b4a1b',
-    # url="http://www.imagemagick.org/download/ImageMagick-6.9.0-6.tar.bz2")
+    homepage = "http://www.imagemagick.org"
+    url      = "http://www.imagemagick.org/download/ImageMagick-7.0.2-6.tar.gz"
```
Comment (lee218llnl) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: Looks like a -7 release was pushed out recently and they removed the link for -6. Perhaps you can point to github instead:

https://github.com/ImageMagick/ImageMagick/archive/7.0.2-6.tar.gz

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: Man, they just don't make it easy, do they. I'll try that git archive out and make sure it works.

Comment (citibeth) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: Is there a reason we need the bleeding edge here?  Can Spack just use the
latest -10 release that is stable?  If we can't for Matplotlib... can we at
have at least one stable version in this package, and set `preferred=True`
on it?

I agree... for non-stable versions, we should fetch from GitHub (either a
`git` download, or a GitHub tar URL).  We will also need to
depends_on('autotools') and do the autoconf() thing at the beginning of
`install()` (other packages do this; search for specifics).

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: Contrary to the comments I removed, I don't think the "stable" -10 releases are kept around either. I don't see them available for download. They only have the bleeding edge of the current release (7.0.2-7) and the previous release (6.9.5-5). There was a [recent security vulnerability discovered](https://imagetragick.com/), so that may also be why. I'm going to use the GitHub repo since that seems to be the only one with old releases. GitLab also has them I think

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: Fixed. Good catch @lee218llnl

File: var/spack/repos/builtin/packages/ImageMagick/package.py [hunk 9]
```diff
@@ -42,6 +43,9 @@ class Imagemagick(Package):
     depends_on('libtiff')
     depends_on('ghostscript')
 
+    def url_for_version(self, version):
+        return "https://github.com/ImageMagick/ImageMagick/archive/{0}.tar.gz".format(version)
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: This should work automatically, but the version was getting mangled. I think it must be due to the dash in the version. Adding the url_for_version solves the problem.

Comment (citibeth) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: >
> They only have the bleeding edge of the current release (7.0.2-7) and the
> previous release (6.9.5-5). There was a recent security vulnerability
> discovered <https://imagetragick.com/>, so that may also be why.


I see:
     http://www.imagemagick.org/download/

Unless someone complains, let's just use the versions they provide there.
Old versions were probably removed for a reason; please do not include
versions with known security vulnerabilities.

They make it clear that the authoritative Git repo for ImageMagick is found
at:
    http://git.imagemagick.org/repos/ImageMagick

If we need to use a git repo, I think we should pull from this one, not
GitHub or GitLab.

-- Elizabeth

Comment (adamjstewart) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: We can't use http://www.imagemagick.org/download/ because as @lee218llnl discovered, it changes at least monthly. GitHub is just a mirror for GitLab. We use mirrors of plenty of packages instead of the primary download repository.

Comment (citibeth) [inline var/spack/repos/builtin/packages/ImageMagick/package.py]: >
> We can't use http://www.imagemagick.org/download/ because as @lee218llnl
> <https://github.com/lee218llnl>discovered, it changes at least monthly.


I see...  so they keep removing old versions?

GitHub is just a mirror for GitLab. We use mirrors of plenty of packages
> instead of the primary download repository.


There are possible security issues here.  @tgamblin what is your take on
this?  Should we "go to the horse's mouth" when possible?  Or do we not
care so much?

Finally... do you think we should download using:
  a) Spack's `git` download method?
  b) Downloading a tarball from the archives/ folder?  (Which I believe was
manually created)
  c) Sending the right URL to GitHub (causing a tarball to be
auto-generated on the fly)
        https://developer.github.com/v3/repos/contents/#get-archive-link

**Comment by adamjstewart** [comment]
I added @citibeth's changes to PySide from #667 to this PR. PySide 1.2.4 is available, but 1.2.2 is still preferred since 1.2.4 has RPATH linking problems.

**Comment by adamjstewart** [comment]
Ping @tgamblin

**Comment by tgamblin** [comment]
@lee218llnl: LGTM -- can you give this a spin and make sure it works for you?

**Comment by lee218llnl** [comment]
@tgamblin it worked OK for me.
