### PR TITLE
cbtf-krell: Update Boost dependency

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.  @jgalarowicz Do you want to comment on this change?

File: var/spack/repos/builtin/packages/cbtf-krell/package.py [hunk 1]
```diff
@@ -66,12 +65,7 @@ class CbtfKrell(CMakePackage):
...
-    depends_on("boost@1.70.0:")
-
-    # TODO: replace this with an explicit list of components of Boost,
-    # for instance depends_on('boost +filesystem')
-    # See https://github.com/spack/spack/pull/22303 for reference
-    depends_on(Boost.with_default_variants)
+    depends_on("boost@1.70.0:+filesystem+graph+program_options+python+test+thread")
 
     # For Dyninst
     depends_on("dyninst@10.1.0", when="@develop")
```
Comment (bernhardkaindl) [inline var/spack/repos/builtin/packages/cbtf-krell/package.py]: @hainest: As you are working on `dyninst` and this depends on `dyninst`:

It looks like when using gcc-12.3.0 and `dyninst` uses `intel-tbb-2020.3`, maybe dyninst (intel-tbb) needs some fixing or conflict? I saw that some other package also has gotten a fix for `tbb:task` vs `task` (for gcc-13):

https://github.com/bambulab/BambuStudio/pull/1882/files#diff-40df5e0a2bcbc0ed23e2af22801fff02e39b9cb7bdefdd7af415d909d00024b0R7-R8
```py
                 from .stage/spack-stage-dyninst-10.1.0-dvcmvyczl7iuoddxin5sqfq4l5zfdq2l/spack-src/symtabAPI/src/dwarfWalker.C:48:
opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/intel-tbb-2020.3-7pmy6kavg6zc343p6owvrwjwzzmbn2m2/include/tbb/task.h:300:20: error: declaration of 'tbb:task& tbb:internal:task_prefix:task()' changes meaning of 'task' [-Wchanges-meaning]
  300 |         tbb:task& task() {return *reinterpret_cast<tbb:task*>(this+1);}
      |                    ^~~~
make: *** [Makefile:139: all] Error 2
==> Error: ProcessError: Command exited with status 2:
    opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/gmake-4.4.1-krhvoy5tc5wo3p2bpim66lm35gbmykuj/bin/make -j64

             PI/src/dwarfWalker.C:48:
  >> 952     opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/intel-tbb-2020.3-7pmy6kavg6zc343p6owvrwjwzzmbn2m2/include/t
             bb/task.h:300:20: error: declaration of 'tbb:task& tbb:internal:task_prefix:task()' changes meaning of 'task' [-Wchanges-mea
             ning]
     1072          |             ^~~~
  >> 1073    make[2]: *** [symtabAPI/CMakeFiles/symtabAPI.dir/build.make:443: symtabAPI/CMakeFiles/symtabAPI.dir/src/dwarfWalker.C.o] Error 1
     1074    make[2]: *** Waiting for unfinished jobs....
     1075    .stage/spack-stage-dyninst-10.1.0-dvcmvyczl7iuoddxin5sqfq4l5zfdq2l/spack-src/symtabAPI/src/parseStab.C: In
             -dvcmvyc'
  >> 1105    make[1]: *** [CMakeFiles/Makefile2:762: symtabAPI/CMakeFiles/symtabAPI.dir/all] Error 2
     1106    make[1]: *** Waiting for unfinished jobs....
     1107    .stage/spack-stage-dyninst-10.1.0-dvcmvyczl7iuoddxin5sqfq4l5zfdq2l/spack-src/instructionAPI/src/Instructio
             -dvcmvyc'
  >> 1128    make: *** [Makefile:139: all] Error 2
```

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]

File: var/spack/repos/builtin/packages/cbtf-krell/package.py (hunk 1 above)
Comment (hainest) [reply var/spack/repos/builtin/packages/cbtf-krell/package.py]: Sorry, I missed this note. I'll do some local testing to see what's going on.

Comment (hainest) [reply var/spack/repos/builtin/packages/cbtf-krell/package.py]: I wasn't able to replicate using the below and applying #47339. That patch is for a missing std include, so I wouldn't think it would affect TBB.

```
docker run --rm -it ubuntu:24.04
apt update -y
apt install -y gcc-12 g++-12 git cmake xz-utils bzip2 python3
git clone --depth=1 https://github.com/spack/spack
alias spack='/spack/bin/spack'
spack compiler find
spack external find --not-buildable python cmake
spack bootstrap now
spack install dyninst@10.1.0 %gcc@12.3.0 ^intel-tbb@2020.3
```

**Review by bernhardkaindl — APPROVED** [review]
@hainest, It was decided that my attempts to try to improve the buildability of merged packages by informing or even requesting to fix build failures competes with GitLab CI and causes confusion and therefore it was decided to shut it down. I therefore have to pull out from further reviews based on this approach, and leave this PR for review by other reviewers.

To allow other reviewers to approve, I've to cancel my change request, which I can only do by setting the approved flag on this review.

**Comment by tldahlgren** [comment]
ping @jgalarowicz

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@hainest: You need to add some form of `depends_on("gotcha")`:
```py
==> Error: KeyError: 'No spec with name gotcha in cbtf-krell@1.9.4.1/zpsmiu47y77dmwy5ihmc5wnan2otkahm'

var/spack/repos/builtin/packages/cbtf-krell/package.py:205, in cmake_args:
        202            "-DMRNET_DIR=%s" % spec["mrnet"].prefix,
        203            "-DDYNINST_DIR=%s" % spec["dyninst"].prefix,
        204            "-DLIBIOMP_DIR=%s" % spec["llvm-openmp-ompt"].prefix,
  >>    205            "-DGOTCHA_DIR=%s" % spec["gotcha"].prefix,
        206            "-DXERCESC_DIR=%s" % spec["xerces-c"].prefix,
        207        ]
        208
```
Maybe the `"gotcha"` was indirectly included, but at least for me, it was not (in a build with `%gcc@12`), and it should get a direct `depends_on` if it relies on getting spec data for `"gotcha"`.

Update: Pushed adding a depends_on for it.

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@hainest After adding a depends on `gotcha`, a build with %gcc@10 to %gcc@13 build using `spack install cbtf-krell@1.9.4.1 %gcc@10:13` fail with:
```py
grep -C1 error: .stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-build-out.txt
/usr/bin/ld: ../../../services/src/papi/libcbtf-services-papi.a(PapiAPI.c.o):
/home/bkaindl/spack.6/.stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-src/services/include/KrellInstitute/Services/PapiAPI.h:45:
multiple definition of `hw_info';
CMakeFiles/hwc-collector-monitor-fileio.dir/collector.c.o:/home/bkaindl/spack.6/.stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-src/services/include/KrellInstitute/Services/PapiAPI.h:45: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [core/collectors/hwc/CMakeFiles/hwc-collector-monitor-fileio.dir/build.make:115: core/collectors/hwc/hwc-collector-monitor-fileio.so]
```

Update: This is likely obsolete as it needs `gcc@:9` to build.
I pushed adding a conflict for the newer `%gcc@10:` versions.

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@hainest: Thanks for referring to #47339: I rebased the PR branch on top of the current `develop` as the merged #47339 is needed as one required component to fix the build of `dyninst@10.0.0:12.2.0` with more recent `gcc` versions (at least since `%gcc@12` or even `%gcc@11`).

Furthermore, pinning the version of `dyninst` to `@10.1.0` only looks like an oversight:
```py
    # For Dyninst
    depends_on("dyninst@10.1.0", when="@develop")
    depends_on("dyninst@10.1.0", when="@1.9.3:9999")
```
For this package to have more chances to be buildable with newer `%gcc` versions, this should be changed to:
```py
    # For Dyninst
    depends_on("dyninst@10.1.0:", when="@develop")
    depends_on("dyninst@10.1.0:", when="@1.9.3:9999")
```

Update: This is likely obsolete as it needs `gcc@:9` to build.
I pushed adding a conflict for the newer `%gcc@10:` versions.

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
`cbtf-krell@=1.9.4 %gcc@11` (after all workarounds/fixes added) fails with:
```py
grep -A2 error: stage/spack-stage-cbtf-krell-1.9.4-.../spack-build-out.txt
stage/spack-stage-cbtf-krell-1.9.4-.../spack-src/services/src/ompt/callbacks-50.c:138:1: error: expected identifier or '(' before '}' token
  138 | }
      | ^
--
stage/spack-stage-cbtf-krell-1.9.4-.../spack-src/services/src/ompt/callbacks-50.c:205:17: error: 'barrier_btime' undeclared (first use in this function)
  205 |                 barrier_btime = ((uint64_t)(now.tv_sec) * (uint64_t)(1000000000)) +
      |                 ^~~~~~~~~~~~~
```
Update: This is likely obsolete as it needs `gcc@:9` to build.
I pushed adding a conflict for the newer `%gcc@10:` versions.

**Review by bernhardkaindl — DISMISSED** [review]
It needs `gcc@:9` to build. I pushed adding a conflict for the newer `%gcc@10:` versions.

@hainest: If you agree with the conflict on `%gcc@10:`, you can set the pr to ready for review to allow the GitLab CI pipeline to be scheduled for running CI at the next opportunity: It's not instant, but starts eventually. If GitLab CI also passes, mention a spack maintainer to merge it.

**Review by bendamasio — COMMENTED** [review]
Hello @jgalarowicz (maintainer), I generated some build results:<br>
:thumbsup::information_source: `spack install` on the changed recipes of this PR was successful[^1] on Ubuntu 22.04.4 LTS!<details><summary>Click here for a summary of the successful builds.</summary>
These changed specs were found using [gh pr diff](https://cli.github.com):
- `cbtf-krell %gcc@9`


<details><summary><b>Click here to show/hide the report on </b><tt>spack find</tt> for <tt>linux-ubuntu22.04-skylake / gcc@9.5.0</tt>.</summary><ol>

<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>cbtf-krell@1.9.4.1~crayfe~ipo~mpich2~mpt~mvapich2~openmpi~runtime build_system=cmake build_type=RelWithDebInfo generator=make
>```
</summary>

>```py
>	binutils@2.32 compress_debug_sections=zlib
>		diffutils@3.10
>		pkgconf@2.2.0
>		zlib-ng@2.2.1compatnew_strategiesopt
>	boost@1.84.0atomicchrono_time_parallelicuiostreams_optionspythonrandomregexserializationsignals_erasure cxxstd=11,b8569d7 visibility=hidden
>		bzip2@1.0.8
>		icu4c@74.2 cxxstd=11
>			autoconf@2.72
>			automake@1.16.5
>			libtool@2.4.7
>		xz@5.4.6
>		zstd@1.5.6programs
>	cbtf@1.9.4.1 build_type=RelWithDebInfo
>		libxml2@2.13.4
>	cmake@3.30.5
>		curl@8.10.1 tls=openssl
>			nghttp2@1.63.0
>		ncurses@6.5
>	dyninst@10.1.0_dysect
>		elfutils@0.191
>			m4@1.4.19sigsegv,bfdffa7
>				libsigsegv@2.14
>		intel-tbb@2020.3tm,ce1fb16,d62cb66
>		libiberty@2.41
>	gcc-runtime@13.1.0
>	glibc@2.35
>	gmake@4.4.1
>	gotcha@1.0.7
>	libmonitor@2013.02.18commrankdlopen,b77e6ff
>	libtirpc@1.3.3
>		krb5@1.21.3
>			bison@3.8.2
>			findutils@4.9.0
>	libunwind@1.2.1_signals_checks_exceptions_framedocs_backtrace
>	llvm-openmp-ompt@tr6_forwards
>		libffi@3.4.6
>		ninja@1.12.1re2c
>			re2c@3.1
>		perl@5.34.0
>	mrnet@5.0.1-3lwthreads
>	papi@7.1.0_smi_tools
>	python@3.13.0bz2ctypesdbm
>		expat@2.6.4libbsd
>			libbsd@0.12.2
>				libmd@1.0.4
>		gdbm@1.24
>		gettext@0.22.5bzip2cursesgit
>			tar@1.34 zip=pigz
>				pigz@2.8
>		openssl@3.4.0 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		readline@8.2
>		sqlite@3.46.0column_metadatadynamic_extensionsfts
>		util-linux-uuid@2.40.2
>	rpcsvc-proto@1.4.4
>	xerces-c@3.3.0 netaccessor=curl transcoder=gnuiconv
>
>==> 1 installed package
>```

</details>



</details>

[^1]: Orchestrated using `spack install` by [github.com/spack/gh-spack-pr](https://github.com/spack/gh-spack-pr) and the [GitHub CLI](https://cli.github.com/)
</details><details><summary>Notes for @jgalarowicz (maintainer)</summary>

This is not official, it is just based on what I know:
- If you like to review but need more time, please add a comment to the PR.
- If you review, you can add 👍, Approve, LGTM or Request in the comment.
- If you have questions (or to be removed as maintainer), please let me know.

You can also join the Spack Slack channel for more information and have a chat:
https://spackpm.slack.com → #pull-requests. Thank you and best regards, @x64-Linux-Builder</details>

File: var/spack/repos/builtin/packages/cbtf-krell/package.py (hunk 1 above)
Comment (hainest) [reply var/spack/repos/builtin/packages/cbtf-krell/package.py]: It's building with the latest Dyninst.

**Comment by hainest** [comment]
> @hainest: You need to add some form of `depends_on("gotcha")`:
> 
> ```python
> ==> Error: KeyError: 'No spec with name gotcha in cbtf-krell@1.9.4.1/zpsmiu47y77dmwy5ihmc5wnan2otkahm'
> 
> var/spack/repos/builtin/packages/cbtf-krell/package.py:205, in cmake_args:
>         202            "-DMRNET_DIR=%s" % spec["mrnet"].prefix,
>         203            "-DDYNINST_DIR=%s" % spec["dyninst"].prefix,
>         204            "-DLIBIOMP_DIR=%s" % spec["llvm-openmp-ompt"].prefix,
>   >>    205            "-DGOTCHA_DIR=%s" % spec["gotcha"].prefix,
>         206            "-DXERCESC_DIR=%s" % spec["xerces-c"].prefix,
>         207        ]
>         208
> ```
> 
> Maybe the `"gotcha"` was indirectly included, but at least for me, it was not (in a build with `%gcc@12`), and it should get a direct `depends_on` if it relies on getting spec data for `"gotcha"`.
> 
> Update: Pushed adding a depends_on for it.

Updated.

**Comment by hainest** [comment]
> @hainest After adding a depends on `gotcha`, a build with %gcc@10 to %gcc@13 build using `spack install cbtf-krell@1.9.4.1 %gcc@10:13` fail with:
> 
> ```python
> grep -C1 error: .stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-build-out.txt
> /usr/bin/ld: ../../../services/src/papi/libcbtf-services-papi.a(PapiAPI.c.o):
> /home/bkaindl/spack.6/.stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-src/services/include/KrellInstitute/Services/PapiAPI.h:45:
> multiple definition of `hw_info';
> CMakeFiles/hwc-collector-monitor-fileio.dir/collector.c.o:/home/bkaindl/spack.6/.stage/spack-stage-cbtf-krell-1.9.4.1-ver6uw27z72lzdvj4jjx45yh24chqmxm/spack-src/services/include/KrellInstitute/Services/PapiAPI.h:45: first defined here
> collect2: error: ld returned 1 exit status
> make[2]: *** [core/collectors/hwc/CMakeFiles/hwc-collector-monitor-fileio.dir/build.make:115: core/collectors/hwc/hwc-collector-monitor-fileio.so]
> ```
> 
> Update: This is likely obsolete as it needs `gcc@:9` to build. I pushed adding a conflict for the newer `%gcc@10:` versions.

These are fixed with https://github.com/OpenSpeedShop/cbtf-krell/commit/7d47761c6cd9110883bff9ca1e694af1475676f5.

**Comment by hainest** [comment]
@tldahlgren I believe Jim has retired, so we're unlikely to get a response from him. I could take over the package maintenance since I'm familiar with the OpenSpeedshop packages.

**Review by alalazo — APPROVED** [review]
@hainest Feel free to update maintainers, either here, or in a following PR.

**Comment by tldahlgren** [comment]
> @hainest Feel free to update maintainers, either here, or in a following PR.

@hainest Are you planning on doing this in this or a separate PR? Bottom line: can I merge this PR?

**Comment by hainest** [comment]
> > @hainest Feel free to update maintainers, either here, or in a following PR.
> 
> @hainest Are you planning on doing this in this or a separate PR? Bottom line: can I merge this PR?

@tldahlgren I'll do that later. This PR can be merged when you have time.
