### ISSUE TITLE
Installation issue: octave

### ISSUE THREAD

**Issue by ReinhardPrix** [LLNL/spack#17677]
Octave (any version) fails to build on Debian stable/buster/10.4 with default-version of readline 8.0, due to a system-library linking problem against libreadline-7.0. It does build when specifying `readline@7.0` as a dependency.

### Steps to reproduce the issue

```console
$ spack install octave 
...
==> Installing octave
==> No binary for octave found: installing from source
==> octave: Executing phase: 'autoreconf'
==> octave: Executing phase: 'configure'
==> octave: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

10 errors found in build log:
     3717      CXXLD    src/octave
     3718      CXXLD    src/mkoctfile
     3719      CXXLD    liboctave/liboctave.la
     3720      CXXLD    libinterp/liboctinterp.la
     3721      CXXLD    src/octave-cli
     3722    /usr/bin/ld: warning: libreadline.so.7, needed by libinterp/.libs/liboctinterp.so, may conflict with libreadline.so.8
  >> 3723    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tgetnum@@NCURSES6_TINFO_5.0.19991023'
  >> 3724    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `PC@@NCURSES6_TINFO_5.0.19991023'
  >> 3725    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tputs@@NCURSES6_TINFO_5.0.19991023'
  >> 3726    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `UP@@NCURSES6_TINFO_5.0.19991023'
  >> 3727    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tgoto@@NCURSES6_TINFO_5.0.19991023'
  >> 3728    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tgetent@@NCURSES6_TINFO_5.0.19991023'
  >> 3729    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tgetstr@@NCURSES6_TINFO_5.0.19991023'
  >> 3730    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `tgetflag@@NCURSES6_TINFO_5.0.19991023'
  >> 3731    /usr/bin/ld: //lib/x86_64-linux-gnu/libreadline.so.7: undefined reference to `BC@@NCURSES6_TINFO_5.0.19991023'
  >> 3732    collect2: error: ld returned 1 exit status
     3733    make[2]: *** [Makefile:14386: src/octave-cli] Error 1
     3734    make[2]: Leaving directory '/tmp/repr/spack-stage/spack-stage-octave-5.2.0-podxbeochekki7wsal5w6iugthqtjd47/spack-src'
     3735    make[1]: *** [Makefile:25976: all-recursive] Error 1
     3736    make[1]: Leaving directory '/tmp/repr/spack-stage/spack-stage-octave-5.2.0-podxbeochekki7wsal5w6iugthqtjd47/spack-src'
     3737    make: *** [Makefile:9769: all] Error 2

See build log for details:
  /tmp/repr/spack-stage/spack-stage-octave-5.2.0-podxbeochekki7wsal5w6iugthqtjd47/spack-build-out.txt
```
Build log: [spack-build-out.txt](https://github.com/spack/spack/files/4965114/spack-build-out.txt)
Build env: [spack-build-env.txt](https://github.com/spack/spack/files/4965465/spack-build-env.txt)

It looks like parts of octave get linked against the spack-dependency readline-8.0, while other parts (libinterp?) link against the system lib, so probably a bug/weakness in the octave build system (not using pkg-config to figure out -L path to readline?!)

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.1
* **Python:** 3.7.3
* **Platform:** linux-debian10-skylake
```
mh, not sure why it says '0.15.1' there, this is actually on the `develop` branch (605c1a76e08). But the same problem also shows up on the release-0.15 branch.

### Additional information

This problem shows up identically with octave versions back to 4.x, so a fix should ideally work for all of them.

Curiously, the build succeeds when using readline-7.0, i.e.
`$ spack install octave ^readline@7.0`

which actually has none of the resulting `octave-cli` nor `liboctave.so` nor `liboctinterp.so` linked against the system readline, they all seem to link against spack-readline as expected (even with LD_LIBRARY_PATH unset), so something weird seems to happen during build.

Octave package mentions @mtmiller as a maintainer.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Ping @mtmiller

**Comment by mtmiller** [comment]
Yeah, seems likely that this is due to missing references to the readline include and lib directories in the octave build spec.

**Comment by mtmiller** [comment]
Octave builds for me on Debian testing, with readline 8 installed as both a system library and a spack build dependency. From what I know about spack so far, it looks like octave always links directly against the system library, but possibly some other dependency module links against spack readline 8 on your system, hence the conflict.

I can't promise to work on a fix for this soon, but I would gladly review and test a PR. Please note that Octave doesn't use pkgconfig for readline because readline hasn't traditionally used pkgconfig, so the `-I` and `-L` options should be stuffed into `CPPFLAGS` and `LDFLAGS` instead.

**Comment by alalazo** [comment]
For the record, I am on `develop` and situation is similar but worse on my system:
* **Spack:** 0.15.4-773-f4a37b2dc
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

and this is what I see:
```console
$ spack install octave
[ ... ]
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/octave-5.2.0-tabdxwehwzxptw42q5b4tkpuvoi2jaen

$ ldd /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/octave-5.2.0-tabdxwehwzxptw42q5b4tkpuvoi2jaen/bin/octave-cli | grep readline
	libreadline.so.8 => /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/readline-8.0-nsh6fwmmx4qgn3erzmejxavdmwdeds5z/lib/libreadline.so.8 (0x00007f3db6329000)
	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007f3db3e36000)
```
Will try to work on a fix asap.

**Comment by davidedelvento** [comment]
Is this still an issue with v0.18 or is it solved?
