### ISSUE TITLE
Error building tar

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/spack#1446]
I'm really trying to install the `git` package (working on creating a `git-lfs` package), but as part of that, the build dies on building tar:

```
==> Building tar
==> Error: Command exited with status 2:
'make' '-j8'

See build log for details:
  /private/var/folders/vr/7lfgcgzd0wb4brywdhg86ygw00157w/T/lee1001/spack-stage/spack-stage-awGs8J/tar-1.28/spack-build.out

/Users/lee1001/projs/llnl/spack/var/spack/repos/builtin/packages/tar/package.py:36, in install:
     34       def install(self, spec, prefix):
     35           configure("--prefix=%s" % prefix)
  >> 36           make()
     37           make('install')
==> Error: Installation process had nonzero exit code : 256
```

Digging into the `spack-build.out` output, gives the following context:

```
Making all in lib
  GEN      rmt-command.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       paxerror.o
  CC       paxexit-status.o
  CC       paxnames.o
  CC       prepargs.o
  CC       rtapelib.o
  CC       stdopen.o
  CC       wordsplit.o
  CC       xattr-at.o
In file included from xattr-at.c:40:
../gnu/at-func.c:77:12: error: too few arguments to function call, expected 6, have 5
    return CALL_FUNC (file);
           ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:65:1: note: 'setxattr' declared here
int setxattr(const char *path, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:40:
../gnu/at-func.c:95:35: error: too few arguments to function call, expected 6, have 5
        FUNC_RESULT proc_result = CALL_FUNC (proc_file);
                                  ^~~~~~~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:65:1: note: 'setxattr' declared here
int setxattr(const char *path, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:40:
../gnu/at-func.c:132:9: error: too few arguments to function call, expected 6, have 5
  err = CALL_FUNC (file);
        ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:65:1: note: 'setxattr' declared here
int setxattr(const char *path, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:52:
../gnu/at-func.c:77:12: warning: implicit declaration of function 'lsetxattr' is invalid in C99 [-Wimplicit-function-declaration]
    return CALL_FUNC (file);
           ^
../gnu/at-func.c:46:24: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ^
xattr-at.c:48:20: note: expanded from macro 'AT_FUNC_F1'
#define AT_FUNC_F1 lsetxattr
                   ^
In file included from xattr-at.c:65:
../gnu/at-func.c:77:12: error: too few arguments to function call, expected 6, have 4
    return CALL_FUNC (file);
           ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:65:
../gnu/at-func.c:95:35: error: too few arguments to function call, expected 6, have 4
        FUNC_RESULT proc_result = CALL_FUNC (proc_file);
                                  ^~~~~~~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:65:
../gnu/at-func.c:132:9: error: too few arguments to function call, expected 6, have 4
  err = CALL_FUNC (file);
        ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
^
In file included from xattr-at.c:79:
../gnu/at-func.c:77:12: warning: implicit declaration of function 'lgetxattr' is invalid in C99 [-Wimplicit-function-declaration]
    return CALL_FUNC (file);
           ^
../gnu/at-func.c:46:24: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ^
xattr-at.c:75:20: note: expanded from macro 'AT_FUNC_F1'
#define AT_FUNC_F1 lgetxattr
                   ^
In file included from xattr-at.c:92:
../gnu/at-func.c:77:12: error: too few arguments to function call, expected 4, have 3
    return CALL_FUNC (file);
           ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:73:1: note: 'listxattr' declared here
ssize_t listxattr(const char *path, char *namebuff, size_t size, int options);
^
In file included from xattr-at.c:92:
../gnu/at-func.c:95:35: error: too few arguments to function call, expected 4, have 3
        FUNC_RESULT proc_result = CALL_FUNC (proc_file);
                                  ^~~~~~~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:73:1: note: 'listxattr' declared here
ssize_t listxattr(const char *path, char *namebuff, size_t size, int options);
^
In file included from xattr-at.c:92:
../gnu/at-func.c:132:9: error: too few arguments to function call, expected 4, have 3
  err = CALL_FUNC (file);
        ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:73:1: note: 'listxattr' declared here
ssize_t listxattr(const char *path, char *namebuff, size_t size, int options);
^
In file included from xattr-at.c:105:
../gnu/at-func.c:77:12: warning: implicit declaration of function 'llistxattr' is invalid in C99 [-Wimplicit-function-declaration]
    return CALL_FUNC (file);
           ^
../gnu/at-func.c:46:24: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ^
xattr-at.c:102:20: note: expanded from macro 'AT_FUNC_F1'
#define AT_FUNC_F1 llistxattr
                   ^
3 warnings and 9 errors generated.
make[3]: *** [xattr-at.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

## System Information

This is on OS X 10.11.6, clean clone of spack:

```
commit 369b2ef01f1566f96901fe94b00a6e3eaecf2d25
Merge: 1ac1cc3 2bd1a51
Author: becker33 <becker33@llnl.gov>
Date:   Thu Aug 4 09:37:24 2016 -0700
```

**Comment by adamjstewart** [comment]
Let me take a closer look at this. There have been other problems with the new gettext dependency (#1436). 
As a quick workaround, you can run:
```
spack install git ^gettext~tar
```

**Comment by tgamblin** [comment]
@adamjstewart: is `gettext` providing some headers that conflict with the package being built?  Do we need #1380?

**Comment by adamjstewart** [comment]
Not sure. It built on Linux for me but I can try to recreate the problem on macOS on Monday. @IanLee1521 what compiler were you using? Does it have both C and Fortran components? We might just want to remove the gettext dependency as it seems to be causing a lot of headaches.

**Comment by davydden** [comment]
it does not work on macOS 10.11.6 with clang either:
```
n file included from xattr-at.c:40:
../gnu/at-func.c:77:12: error: too few arguments to function call, expected 6, have 5
    return CALL_FUNC (file);
           ^~~~~~~~~~~~~~~~
../gnu/at-func.c:46:60: note: expanded from macro 'CALL_FUNC'
# define CALL_FUNC(F) (AT_FUNC_F1 (F AT_FUNC_POST_FILE_ARGS))
                       ~~~~~~~~~~                          ^
/usr/include/sys/xattr.h:65:1: note: 'setxattr' declared here
int setxattr(const char *path, const char *name, const void *value, size_t size, u_int32_t position, int options);
^
```
I have a feeling that it is a conflict between `tar` headers and those provided by system's tar.

**Comment by davydden** [comment]
i think `tar` should be a virtual dependency with `gnu-tar` being a particular implementation, here's Homebrew's [gnu-tar](https://github.com/Homebrew/homebrew-core/blob/03650f0cff79515bee258a854395947a43f3c41f/Formula/gnu-tar.rb).

**Comment by davydden** [comment]
here's the same issue on gnu-tar bugtracker: http://bug-tar.gnu.narkive.com/nLNzl1th/os-x-build-errors
