### ISSUE TITLE
Spack repo command gives an error

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#931]

**Comment by gartung** [comment]
git checkout llnl/develop
Note: checking out 'llnl/develop'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 98faee1... Minor tweaks to `flock` docs.
[gartung@gartung spack]$ spack repo rm hsf
Traceback (most recent call last):
  File "/home/gartung/spack/bin/spack", line 176, in <module>
    main()
  File "/home/gartung/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/home/gartung/spack/lib/spack/spack/cmd/repo.py", line 174, in repo
    action[args.repo_command](args)
  File "/home/gartung/spack/lib/spack/spack/cmd/repo.py", line 134, in repo_remove
    spack.config.update_config('repos', repos, args.scope)
  File "/home/gartung/spack/lib/spack/spack/config.py", line 548, in update_config
    configuration.update(update_data)
AttributeError: 'syaml_list' object has no attribute 'update'

**Comment by gartung** [comment]
The above error in on RHEL7. On RHEL6 I get
[gartung@woof spack]$ git branch
* (HEAD detached at llnl/develop)
  develop
  features-merged
[gartung@woof spack]$ spack repo add /scratch/gartung/spack/var/spack/repos/hep-spack
Traceback (most recent call last):
  File "/home/gartung/scratch/spack/bin/spack", line 176, in <module>
    main()
  File "/home/gartung/scratch/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/scratch/gartung/spack/lib/spack/spack/cmd/repo.py", line 174, in repo
    action[args.repo_command](args)
  File "/scratch/gartung/spack/lib/spack/spack/cmd/repo.py", line 109, in repo_add
    spack.config.update_config('repos', repos, args.scope)
  File "/scratch/gartung/spack/lib/spack/spack/config.py", line 548, in update_config
    configuration.update(update_data)
AttributeError: 'syaml_list' object has no attribute 'update'

**Comment by alalazo** [comment]
Hmm, this may be related to my PR #775 which solved #774 ... I'll try to have a look at that tomorrow if the issue won't be solved overnight

**Comment by gartung** [comment]
[gartung@woof repos]$ spack repo create
usage: spack repo create [-h] directory [namespace]
spack repo create: error: too few arguments
[gartung@woof repos]$ spack repo create test test
==> Created repo with namespace 'test'.
==> To register it with spack, run this command:
  spack repo add /scratch/gartung/spack/var/spack/repos/test
[gartung@woof repos]$ cd test/
[gartung@woof test]$ ls
packages  repo.yaml
[gartung@woof test]$ cat repo.yaml 
repo:
  namespace: 'test'
[gartung@woof test]$  spack repo add /scratch/gartung/spack/var/spack/repos/test
Traceback (most recent call last):
  File "/home/gartung/scratch/spack/bin/spack", line 176, in <module>
    main()
  File "/home/gartung/scratch/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/scratch/gartung/spack/lib/spack/spack/cmd/repo.py", line 174, in repo
    action[args.repo_command](args)
  File "/scratch/gartung/spack/lib/spack/spack/cmd/repo.py", line 109, in repo_add
    spack.config.update_config('repos', repos, args.scope)
  File "/scratch/gartung/spack/lib/spack/spack/config.py", line 548, in update_config
    configuration.update(update_data)
AttributeError: 'syaml_list' object has no attribute 'update'

**Comment by alalazo** [comment]
@gartung #934 Should solve the problem. Can you confirm this?

**Comment by gartung** [comment]
#934 fixes the problem.

**Comment by gartung** [comment]
#934 appears equivalent

**Comment by alalazo** [comment]
@gartung My bad. I missed #933 
@hegner If you want to add a regression test in #933 I'll close #934

**Comment by hegner** [comment]
@alalazo - no prob. Forces me to learn that part. Give me some time for that.

**Comment by alalazo** [comment]
@hegner no worries. Thanks for taking care of the bug :+1:

**Comment by alalazo** [comment]
@gartung The bug should be solved now, see #933 discussion
