### ISSUE TITLE
Installation issue: 'flex' build failures on mac M1

### ISSUE THREAD

**Issue by kuberry** [LLNL/spack#41197]
### Steps to reproduce the issue

```console
$ spack spec -I flex@2.6.3%apple-clang@14.0.0+lex~nls build_system=autotools arch=darwin-monterey-m1
Input spec
--------------------------------
 -   flex@2.6.3%apple-clang@14.0.0+lex~nls build_system=autotools arch=darwin-monterey-m1

Concretized
--------------------------------
 -   flex@2.6.3%apple-clang@14.0.0+lex~nls build_system=autotools arch=darwin-monterey-m1
 -       ^bison@3.8.2%apple-clang@14.0.0 build_system=autotools arch=darwin-monterey-m1
 -           ^gettext@0.22.3%apple-clang@14.0.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=darwin-monterey-m1
 -               ^bzip2@1.0.8%apple-clang@14.0.0~debug~pic+shared build_system=generic arch=darwin-monterey-m1
 -               ^libxml2@2.10.3%apple-clang@14.0.0+pic~python+shared build_system=autotools arch=darwin-monterey-m1
 -                   ^pkgconf@1.9.5%apple-clang@14.0.0 build_system=autotools arch=darwin-monterey-m1
 -               ^ncurses@6.4%apple-clang@14.0.0~symlinks+termlib abi=none build_system=autotools arch=darwin-monterey-m1
 -               ^tar@1.34%apple-clang@14.0.0 build_system=autotools zip=pigz arch=darwin-monterey-m1
 -                   ^pigz@2.7%apple-clang@14.0.0 build_system=makefile arch=darwin-monterey-m1
 -                   ^zstd@1.5.5%apple-clang@14.0.0+programs build_system=makefile compression=none libs=shared,static arch=darwin-monterey-m1
 -               ^xz@5.4.1%apple-clang@14.0.0~pic build_system=autotools libs=shared,static arch=darwin-monterey-m1
 -           ^perl@5.38.0%apple-clang@14.0.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=darwin-monterey-m1
 -               ^berkeley-db@18.1.40%apple-clang@14.0.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-monterey-m1
 -               ^gdbm@1.23%apple-clang@14.0.0 build_system=autotools arch=darwin-monterey-m1
 -                   ^readline@8.2%apple-clang@14.0.0 build_system=autotools patches=bbf97f1 arch=darwin-monterey-m1
 -               ^zlib-ng@2.1.4%apple-clang@14.0.0+compat+opt build_system=autotools arch=darwin-monterey-m1
 -       ^diffutils@3.9%apple-clang@14.0.0 build_system=autotools arch=darwin-monterey-m1
 -           ^libiconv@1.17%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-monterey-m1
 -       ^findutils@4.9.0%apple-clang@14.0.0 build_system=autotools patches=440b954 arch=darwin-monterey-m1
 -       ^gmake@4.4.1%apple-clang@14.0.0~guile build_system=generic arch=darwin-monterey-m1
 -       ^gnuconfig@2022-09-17%apple-clang@14.0.0 build_system=generic arch=darwin-monterey-m1
 -       ^m4@1.4.19%apple-clang@14.0.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=darwin-monterey-m1
 -           ^libsigsegv@2.14%apple-clang@14.0.0 build_system=autotools arch=darwin-monterey-m1
```

### Error message

<details><summary>Error message</summary>

<pre>
==> [2023-11-17-10:29:54.254307] Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

5 errors found in build log:
     319    mv -f .deps/stage1flex-scanopt.Tpo .deps/stage1flex-scanopt.Po
     320    mv -f .deps/stage1flex-tables_shared.Tpo .deps/stage1flex-tables_shared.Po
     321    mv -f .deps/stage1flex-yylex.Tpo .deps/stage1flex-yylex.Po
     322    libtool: link: /Users/pakuber/spack/lib/spack/env/clang/clang -dynamiclib  -o .libs/libfl.2.dylib  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -install_name  /Users/pakuber/spack/opt/spack/darw
            in-monterey-m1/apple-clang-14.0.0/flex-2.6.3-cyvtxbshqikrgtrhrcxeka5j4dv7h2am/lib/libfl.2.dylib -compatibility_version 3 -current_version 3.0 -Wl,-single_module
     323    mv -f .deps/stage1flex-gen.Tpo .deps/stage1flex-gen.Po
     324    mv -f .deps/stage1flex-tblcmp.Tpo .deps/stage1flex-tblcmp.Po
  >> 325    Undefined symbols for architecture arm64:
     326      "_yylex", referenced from:
     327          _main in libmain.o
     328    ld: symbol(s) not found for architecture arm64
  >> 329    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 330    make[2]: *** [Makefile:609: libfl.la] Error 1
     331    make[2]: *** Waiting for unfinished jobs....
     332    mv -f .deps/flex-main.Tpo .deps/flex-main.Po
     333    mv -f .deps/stage1flex-main.Tpo .deps/stage1flex-main.Po
     334    make[2]: Leaving directory '/private/var/folders/zk/1zr9bdg53s3_d7qxmv2m5f80002l2h/T/pakuber/spack-stage/spack-stage-flex-2.6.3-cyvtxbshqikrgtrhrcxeka5j4dv7h2am/spack-src/src'
  >> 335    make[1]: *** [Makefile:524: all] Error 2
     336    make[1]: Leaving directory '/private/var/folders/zk/1zr9bdg53s3_d7qxmv2m5f80002l2h/T/pakuber/spack-stage/spack-stage-flex-2.6.3-cyvtxbshqikrgtrhrcxeka5j4dv7h2am/spack-src/src'
  >> 337    make: *** [Makefile:527: all-recursive] Error 1

See build log for details:
  /var/folders/zk/1zr9bdg53s3_d7qxmv2m5f80002l2h/T/pakuber/spack-stage/spack-stage-flex-2.6.3-cyvtxbshqikrgtrhrcxeka5j4dv7h2am/spack-build-out.txt
</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.22.0.dev0 (53c7edb0adea3e7f91b80a68e09ef130b5dc85db)
* **Python:** 3.9.12
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

I'm getting the above mentioned linking error. I've tracked this down with git bisect to:
```
first bad commit: [e5f3ffc04fb7a1fea237226210b0cafc9246d0f2] `SetupContext.get_env_modifications` fixes and documentation (#40683)
e5f3ffc04fb7a1fea237226210b0cafc9246d0f2 is the first bad commit
commit e5f3ffc04fb7a1fea237226210b0cafc9246d0f2
Author: Harmen Stoppels <me@harmenstoppels.nl>
Date:   Wed Nov 1 08:47:15 2023 +0100

    `SetupContext.get_env_modifications` fixes and documentation (#40683)
    
    Call setup_dependent_run_environment on both link and run edges,
    instead of only run edges, which restores old behavior.
    
    Move setup_build_environment into get_env_modifications
    
    Also call setup_run_environment on direct build deps, since their run
    environment has to be set up.
```

I'm on an M1 mac (Monterey 12.7.1) w/ apple-clang 14.0.0
```
$ g++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
[spack-build-env.txt](https://github.com/spack/spack/files/13426250/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13426252/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

@haampie

**Comment by haampie** [comment]
Edit: got it the wrong way around.

The build env used to have

```
MACOSX_DEPLOYMENT_TARGET=10.16
```

but since the "bad commit" it is

```
MACOSX_DEPLOYMENT_TARGET=13.0
```

The 10.16 value is coming from a generic `setup_build_environment` from `AutotoolsPackage`, introduced in https://github.com/spack/spack/pull/28797.

I think it's an order of operations issue.

@tgymnich I think your patch would not be necessary if I restore the old behavior, otherwise we have to patch many more configure scripts, cause tons of them have:

```sh
    darwin*) # darwin 5.x on
      # if running on 10.5 or later, the deployment target defaults
      # to the OS version, if on x86, and 10.4, the deployment
      # target defaults to 10.4. Don't you love it?
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
	10.0,*86*-darwin8*|10.0,*-darwin[91]*)
	  _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
	10.[012][,.]*)
	  _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
	10.*)
	  _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac
```

**Comment by sethrj** [comment]
I think it depends on how old the `configure` script is. There's a longstanding bug in `libtool` that hardcodes thie `10.*`. If that's still there, I suspect it does require the compatibility target `10.16`.

Looks like this same issue was present in macports: https://trac.macports.org/ticket/60937

The change to `MACOSX_DEPLOYMENT_TARGET=10.16` should fix it, not break it, so I'm very confused.

**Comment by haampie** [comment]
Sorry yes, I messed up branches when diffing build-env output :) your fix is still valid, there's an order of operations issue.

**Comment by haampie** [comment]
See https://github.com/spack/spack/pull/41205

**Comment by kuberry** [comment]
Thank you @haampie, https://github.com/spack/spack/pull/41205 fixed it.
