### PR TITLE
gaudi: Add version 39.0 and adapt dependencies and variants accordingly

### PR DESCRIPTION
**Pull request by tmadlener**
- The `py-pytest-cov` dependency has been introduced in: This has been introduced with https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1551
- GaudiAlg has been completely removed in https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1628 and is no longer available for version 39

### CODE REVIEW

**Review by bernhardkaindl — COMMENTED** [review]
@tmadlener: My build on Ubuntu 22.04 using gcc-11.4.0 failed with:
```py
stage-gaudi-39.0/spack-src/GaudiKernel/src/Util/genconf.cpp: In function 'int main(int, char**)':
Util/genconf.cpp:341:13: error: 'class boost::program_options::variables_map' has no member named 'contains'
     560      341 |     if ( vm.contains( "input-cfg" ) ) {
     561          |             ^~~~~~~~
```

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@tmadlener The boost build used was:
`^boost@1.86.0%gcc@11.4.0~atomic~charconv~chrono~clanglibcpp~cobalt~container+context~contract~coroutine~date_time~debug~exception+fiber+filesystem+graph~graph_parallel~icu~iostreams~json~locale+log~math~mpi+multithreaded~nowide~numpy~pic+program_options+python~random+regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout+test+thread~timer~type_erasure~url~versionedlayout~wave build_system=generic context-impl=fcontext cxxstd=11 patches=a440f96,b8569d7 visibility=hidden arch=linux-ubuntu22.04-skylake`
I guess you may have to make some restrictions on which versions of boost are supported.

**Comment by jmcarcell** [comment]
It's in the release notes: https://gitlab.cern.ch/gaudi/Gaudi/-/releases/v39r0

> compilation requires gcc >= 13, C++ >= 20, CMake >= 3.19

The GCC requirement is not true, it builds with GCC 11 (but C++20).

EDIT: Actually I haven't tested this version with GCC 11, only the previous one.

**Comment by bernhardkaindl** [comment]
Thanks, Gaudi needs to be compiled with it, but by default, CMake passes -std=c++17 to gcc-11, so we need to force CMake to enable C++ 20 in this case:

This appears to do the trick:
```py
      conflicts("%gcc@:10", when="@39:")

      # Gaudi @39: needs C++ >= 20, and we need to force CMake to use 20 with old gcc:
      if self.spec.version >= Version("39.0") and self.compiler.version < Version("13.0.0"):
          args.append(self.define("GAUDI_CXX_STANDARD", "20"))
 ```

**Review by bernhardkaindl — DISMISSED** [review]
@tmadlener / @jmcarcell

It should look better with gcc-11 with this change to force CMake to set `gcc` < 13 to use the needed C++ 20.

And, this adds a conflict to not attempt to build `gaudi@39:` with even older `gcc` versions.

This fixed the build for me on Ubuntu 22.04 with `gcc-11.4.0`

File: var/spack/repos/builtin/packages/gaudi/package.py [hunk 1]
```diff
@@ -42,13 +43,15 @@ class Gaudi(CMakePackage):
 
     depends_on("cxx", type="build")  # generated
 
+    conflicts("%gcc@:10", when="@39:")
```
Comment (tmadlener) [inline var/spack/repos/builtin/packages/gaudi/package.py]:
```suggestion
    conflicts("%gcc@:10", when="@39:", msg="Gaudi needs a c++20 capable compiler for this version")
```
Just to give users a bit more information about what is going on.

File: var/spack/repos/builtin/packages/gaudi/package.py [hunk 2]
```diff
@@ -146,6 +150,10 @@ def cmake_args(self):
             # todo:
             self.define("GAUDI_USE_INTELAMPLIFIER", False),
         ]
+        # Release notes for v39.0: https://gitlab.cern.ch/gaudi/Gaudi/-/releases/v39r0
+        # Gaudi@39: needs C++ >= 20, and we need to force CMake to use C++ 20 with old gcc:
+        if self.spec.version >= Version("39.0") and self.compiler.version < Version("13.0.0"):
```
Comment (tmadlener) [inline var/spack/repos/builtin/packages/gaudi/package.py]:
```suggestion
        if self.spec.satisfies("@39: %gcc@:13"):
```
I think this should work (and at least at some point was recommended to me over using Version comparisons directly). Technically, we might even lower this to `@gcc:12`, because I could build it without specifying a c++ version with `gcc@12.3`. However, it also doesn't really hurt explicitly specifying it in that case.

**Review by tmadlener — COMMENTED** [review]
Thanks for checking @bernhardkaindl, I have added the minimum cmake requirements as well, and left a few suggestions inline.

**Review by bernhardkaindl — APPROVED** [review]
@tmadlener Thanks for the further improvements!

I enabled auto-merge after CI pass.

File: var/spack/repos/builtin/packages/gaudi/package.py [hunk 3]
```diff
@@ -146,6 +151,10 @@ def cmake_args(self):
             # todo:
             self.define("GAUDI_USE_INTELAMPLIFIER", False),
         ]
+        # Release notes for v39.0: https://gitlab.cern.ch/gaudi/Gaudi/-/releases/v39r0
+        # Gaudi@39: needs C++ >= 20, and we need to force CMake to use C++ 20 with old gcc:
+        if self.spec.satisfies("@39: %gcc@:13"):
```
Comment (jmcarcell) [inline var/spack/repos/builtin/packages/gaudi/package.py:156]: This I didn't understand, when compiling with GCC 14 C++20 will also be needed, right? And also with Clang.

Comment (tmadlener) [reply var/spack/repos/builtin/packages/gaudi/package.py:156]: I think starting with gcc13 the default would be c++20. However, I am not sure if `GAUDI_CXX_STANDARD` interferes with that(?).

Comment (bernhardkaindl) [reply var/spack/repos/builtin/packages/gaudi/package.py:156]: As far as my little, older experience with cmake goes, cmake is eager to tell g++ which C++ standard to use (I think this depends on which compiler version it detects also). At least in my case, it did already pass -std=c++17, and I did not find where that would have been set in Gaudi.

Take this with a grain of salt as what I saw is not defintive.

But yes, I think it's safer to pin the C++ standard choice from spack than to leave it to the cmake defaults algorithm is or whatever the compiler's default is because we know that in this case, Gaudi-39+ needs C++20.
