### PR TITLE
gplates: add v2.3.0

### PR DESCRIPTION
**Pull request by adamjstewart**
@michaelkuhn can you help test this? You're the only one who's ever contributed to this package. I especially want to see if the boost variants are sufficient and if the package can be built with the latest version of GDAL.

I'm deprecating GDAL 1 and 2 in #30668 and am trying to see if the latest version of gplates works with GDAL 3 yet. I tried compiling on macOS but QWT is built as a framework so gplates' cmake can't find it. I don't know enough about QMake to build a non-framework version of QWT.

P.S. Are you okay with removing the old gplates versions? The only disadvantage of the latest version is that it requires manual download now. But GDAL 1 and Python 2 are long since dead so modern version support is probably more important.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Ping @michaelkuhn

File: var/spack/repos/builtin/packages/gplates/package.py [hunk 1]
```diff
@@ -3,54 +3,62 @@
...
     depends_on('glew')
-    # GDAL's OGRSFDriverRegistrar is not compatible anymore starting with 2.0.
-    depends_on('gdal@1.3.2:1')
-    depends_on('cgal@3.5:')
-    # The latest release of gplates came out before PROJ.6 was released,
-    # so I'm assuming it's not supported.
-    depends_on('proj@4.6.0:5')
+    depends_on('python@2:3', when='@2.3:')
+    depends_on('python@2', when='@:2.1')
+    depends_on('boost@1.35:+program_options+python+system+thread', when='@2.3:')
```
Comment (michaelkuhn) [inline var/spack/repos/builtin/packages/gplates/package.py]: The build fails for me with the following error when using `boost@1.77.0` (see https://discourse.gplates.org/t/compilation-error-with-boost-1-77/452):
```
$STAGE/spack-src/src/gui/TopologyTools.cc:3470:92: error: '_1' was not declared in this scope
```
Using `boost@1.76.0` also results in various errors with `%gcc@12.1.0` but not with `%gcc@11.3.0`. `boost@1.75.0` seems to work, though.

**Comment by michaelkuhn** [comment]
I also wanted to test the older versions but couldn't find the respective source tarballs. Are they still available somewhere or is this why you marked them as deprecated?

**Comment by adamjstewart** [comment]
I marked them as deprecated because they depend on GDAL 1 and 2, which I'm deprecating in #30668 and will remove shortly after the 0.18 release. But the fact that they are no longer available for download is another good reason to deprecate them. I didn't look too hard to figure out where they could be downloaded from, but given that newer versions require manual download I wouldn't be surprised if older versions do now too.

**Review by michaelkuhn — APPROVED** [review]
LGTM and builds on CentOS 8 with GCC 12.1, 11.3 and 8.5.
