### PR TITLE
Make multimethods work with inheritance.

### LINKED ISSUE #3412: pkg-config is broken on a fresh Ubuntu
subj
```
==> Error: NoSuchMethodError: Package PkgConfig does not support setup_dependent_environment called with pkg-config arch=cray-None-None.  Options are: pkg-config arch=cray-None-None
/home/denis/spack/lib/spack/spack/build_environment.py:567, in child_execution:
     547      def child_execution(child_connection, input_stream):
     548          try:
     549              setup_package(pkg, dirty=dirty)
     550              function(input_stream)
     551              child_connection.send(None)
     552          except StopIteration as e:
     553              # StopIteration is used to stop installations
     554              # before the final stage, mainly for debug purposes
     555              tty.msg(e.message)
     556              child_connection.send(None)
     557          except:
     558              # catch ANYTHING that goes wrong in the child process
     559              exc_type, exc, tb = sys.exc_info()
     560  
     561              # Need to unwind the traceback in the child because traceback
     562              # objects can't be sent to the parent.
     563              tb_string = traceback.format_exc()
     564  
     565              # build up some context from the offending package so we can
     566              # show that, too.
  >> 567              package_context = get_package_context(tb)
     568  
     569              build_log = None
     570              if hasattr(pkg, 'log_path'):
     571                  build_log = pkg.log_path
     572  
     573              # make a pickleable exception to send to parent.
     574              msg = "%s: %s" % (str(exc_type.__name__), str(exc))
     575  
     576              ce = ChildError(msg, tb_string, build_log, package_context)
     577              child_connection.send(ce)
     578  
     579          finally:
     580              child_connection.close()

```

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #3412. Was introduced by #3378.

Previously, this would fail with a NoSuchMethodError:

```python
    class Package(object):
        # this is the default implementation
        def some_method(self):
            ...

    class Foo(Package):
        @when('platform=cray')
        def some_method(self):
            ...

        @when('platform=linux')
        def some_method(self):
            ...
```

@mamelara @becker33: This error would happen after #3378 was merged when installing dependents of `pkg-config`.

This fixes the implementation of `@when` so that the superclass method
will be invoked when no subclass method matches.

Adds tests to ensure this works, as well.

### CODE REVIEW

**Comment by tgamblin** [comment]
@kisaacs: does this fix your issue?

**Comment by davydden** [comment]
@tgamblin i can confirm that this fixes my problem here https://github.com/LLNL/spack/issues/3412

**Comment by adamjstewart** [comment]
Does this also fix #1490?

**Comment by adamjstewart** [comment]
Confirmed that it does fix #1490, yay!
