### PR TITLE
XL compiler fix for Paraview v5.6.2

### PR DESCRIPTION
**Pull request by qwofford**
Build errors related to the eigen library for XL compilers.

First Spack PR, feel free to detail any related contribution errors.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
@qwofford I assume this has been fixed in newer releases?

@chuckatkins @danlipsa can you review?

**Comment by danlipsa** [comment]
Why is applied only for paraview 5.6.2? Do we use later eigen, which does not have this problem, for later paraview?

**Comment by chuckatkins** [comment]
ParaView's vendored Eigen shouldn't even be getting used since the package is pulling in the spack eigen package.  Is the eigen part even necessary when building paraview via spack?

**Comment by EthanS94** [comment]
@danlipsa 
> Why is applied only for paraview 5.6.2? Do we use later eigen, which does not have this problem, for later paraview?

Looks to me like Eigen was updated, along with the problematic line in xl-compilation.patch, in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/5020 . ParaView 5.7.0 and up has the newer eigen.

**Comment by chuckatkins** [comment]
> @danlipsa
> 
> > Why is applied only for paraview 5.6.2? Do we use later eigen, which does not have this problem, for later paraview?
> 
> Looks to me like Eigen was updated, along with the problematic line in xl-compilation.patch, in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/5020 . ParaView 5.7.0 and up has the newer eigen.

Regardless of the copy of Eigen in the VTK and ParaView source tree, the spack build should be setup to always use an externally provided spack version so whatever version is in VTK shouldn't ever be getting used here.

**Comment by EthanS94** [comment]
@chuckatkins Oh! I see now. This patch was needed for a spack frozen at a commit before the `depends_on('eigen@3:')` line was added. We need to test with spack master and update the patch file.

**Comment by EthanS94** [comment]
@chuckatkins I tried with spack master, building `paraview@5.6.2 ^eigen@3.3.4` which should get an error with the problematic line in the patch. As expected, it does, so for sure paraview is using the spack-built eigen dependency.
```console
  >> 6435    /home/stam/projects/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/eigen-3.3.4-ixnjiazjb6jkj2sc3aitac4zspcajqok/include/eigen3/Eigen/src/Core/arch/AltiVec/PacketMath.h:1025:13: error: cannot
              initialize a variable of type 'Packet2bl' (aka 'Packet2ul') with an rvalue of type '__vector __bool unsigned long long' (vector of 2 'unsigned long long' values)
```

@qwofford Can you remove the eigen portion from the patch file?

**Comment by chuckatkins** [comment]
> @chuckatkins I tried with spack master, building `paraview@5.6.2 ^eigen@3.3.4` which should get an error with the problematic line in the patch. As expected, it does, so for sure paraview is using the spack-built eigen dependency.
> 
> ```
>   >> 6435    /home/stam/projects/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/eigen-3.3.4-ixnjiazjb6jkj2sc3aitac4zspcajqok/include/eigen3/Eigen/src/Core/arch/AltiVec/PacketMath.h:1025:13: error: cannot
>               initialize a variable of type 'Packet2bl' (aka 'Packet2ul') with an rvalue of type '__vector __bool unsigned long long' (vector of 2 'unsigned long long' values)
> ```
> 
> @qwofford Can you remove the eigen portion from the patch file?

It looks like the eigen package itself needs to be patched then.

**Comment by EthanS94** [comment]
@chuckatkins 
> It looks like the eigen package itself needs to be patched then.

Eigen builds fine on its own. This error happens during the paraview build. I don't know how to address this.

**Comment by chuckatkins** [comment]
> @chuckatkins
> 
> > It looks like the eigen package itself needs to be patched then.
> 
> Eigen builds fine on its own. This error happens during the paraview build. I don't know how to address this.

@EthanS94 Looking at the Eigen source code, it looks like this issue was introduced in the 3.3 beta:
https://gitlab.com/libeigen/eigen/-/commit/8ed26120c81feb7c15544013e30010bda8fc5a80

and patched in the 3.3.5 release:
https://gitlab.com/libeigen/eigen/-/commit/1641a6cdd5a4dcff807a6fa118a83828bcf154cf

```sh
$ git describe --tags 8ed26120c
3.3-beta1-714-g8ed26120c

$ git describe --tags 1641a6cdd
3.3.4-111-g1641a6cdd
```
It also looks like the problem is architecture specific and not compiler specific.  Given that, it should be sufficient to simply add a conflict in the eigen package:
```python
conflicts('target=ppc64le', when='@3.3.0:3.3.4')
```

**Comment by qwofford** [comment]
@chuckatkins I believe I removed the eigen hacks in the patch. 

However, I'm concerned that the patch file references 5.6.2 in the path. The fix, as I understand it, is only relevant for pv5.6.2. Does patch support wildcards? If we want this to be more general than 5.6.2 @danlipsa, how can we achieve this?

**Comment by EthanS94** [comment]
@qwofford Looking at the other paraview patches, it seems Spack knows to patch the paraview source code. It should work to remove `ParaView-v5.6.2` from the patch and start with `/Coprocessing/...` etc.

But, this patch is specifically for 5.6.2. If we want to make this more general (which is a good idea in my opinion), we would need to make sure the patch works for the other versions. In 5.8.0 as an example, we would need to patch `/Clients/Catalyst/CMakeLists.txt` instead of `/Coprocessing/Catalyst/CMakeLists.txt`.

**Comment by adamjstewart** [comment]
`patch` doesn't support wildcards. If you want to make it more general, you'll need separate patches for different version ranges. See `bazel` for a good example of this.

File: var/spack/repos/builtin/packages/paraview/package.py [hunk 1]
```diff
@@ -105,6 +105,8 @@ class Paraview(CMakePackage, CudaPackage):
     depends_on('double-conversion')
     depends_on('expat')
     depends_on('eigen@3:')
+    conflicts('target=ppc64le', when='@3.3.0:3.3.4')
```
Comment (alalazo) [inline var/spack/repos/builtin/packages/paraview/package.py]: I think you mean:
```suggestion
    conflicts('target=ppc64le:', when='@3.3.0:3.3.4')
```
Otherwise what is written here will rule out the generic architecture but allow more specific ones e.g. `power9le`.

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you please check the conflict directive?

**Review by alalazo — DISMISSED** [review]

File: var/spack/repos/builtin/packages/paraview/package.py (hunk 1 above)
Comment (qwofford) [reply var/spack/repos/builtin/packages/paraview/package.py]: Thanks for catching this, I updated the PR. Can you explain this "`:`" mechanism a little? I read the docs on `conflicts` but didn't see explicit reference to the `:`.

Comment (alalazo) [reply var/spack/repos/builtin/packages/paraview/package.py]: @qwofford Sure. There are two parts to it:

1. Spack can distinguish microarchitectures at a finer level than just the base ISA (like `ppc64le`, or `x86_64` etc.). We rely on an external Python package that originated from Spack (https://github.com/archspec/archspec) for that part. Each architecture family defines a graph.
2. In directives you can use the same range semantic as with versions to specify an open or closed range of targets. For instance `ppc64le:` means anything from the base architecture up, so it covers `ppc64le`, `power8le` and `power9le`. You can also do more exotic things like `haswell:skylake`, which would cover `haswell`, `broadwell` and `skylake`...  but I never saw anything like this used in real packages.

Let me know if I was clear enough in the explanation :slightly_smiling_face:

Comment (qwofford) [reply var/spack/repos/builtin/packages/paraview/package.py]: Yes! This is clear. In fact, I think I saw this presented at CANOPIE and I'm just now connecting the dots. Thanks!

**Comment by alalazo** [comment]
@chuckatkins @danlipsa Can you please give a final look before I merge?

File: var/spack/repos/builtin/packages/paraview/package.py [hunk 2]
```diff
@@ -105,6 +105,8 @@ class Paraview(CMakePackage, CudaPackage):
     depends_on('double-conversion')
     depends_on('expat')
     depends_on('eigen@3:')
+    conflicts('target=ppc64le:', when='@3.3.0:3.3.4')
+
```
Comment (chuckatkins) [inline var/spack/repos/builtin/packages/paraview/package.py:112]: The conflict is not in paraview but in the eigen package itself so needs to be moved into `/var/spack/repos/builtin/packages/eigen/package.py`

**Review by chuckatkins — CHANGES_REQUESTED** [review]

File: var/spack/repos/builtin/packages/paraview/package.py (hunk 2 above)
Comment (qwofford) [reply var/spack/repos/builtin/packages/paraview/package.py:112]: Ok, would I just add line 108, above, directly somewhere in here then?

https://github.com/qwofford/spack/blob/7e34c28333c46349d54be1d511030f324f637ceb/var/spack/repos/builtin/packages/eigen/package.py#L7-L44

Maybe around line 30? Something else?

**Comment by qwofford** [comment]
Thanks for that comment @chuckatkins. Sorry I missed this suggestion earlier in the thread. Let me know if this is what you had in mind...

**Comment by qwofford** [comment]
Post-holiday ping. @chuckatkins can you take a look to see if I resolved your concern in the most recent branch update?

**Comment by alalazo** [comment]
@chuckatkins

**Comment by EthanS94** [comment]
@chuckatkins @qwofford This probably needs to be reworked. I personally wouldn't merge this yet

- `paraview@5.9.0` has the fix in the patch (https://github.com/spack/spack/pull/19630/files#diff-eeeb6d69f1a7f8bef26f61ae4a788c056e9974a114a21f5a11b31c378592eaef) since https://gitlab.kitware.com/paraview/paraview/-/merge_requests/4433 . 
  - We could add `conflict('@:5.8.99', when='%xl_r')` to force using `paraview@5.9.0` for the fix
- Newer versions of eigen (at least `eigen@3.3.8`) will not compile with XL due to https://gitlab.kitware.com/paraview/paraview/-/issues/20468
  - `paraview@5.9.0` uses eigen 3.3.8 even if `depends_on(eigen3:)` is removed
  - if `depends_on(eigen@3:)` is not removed, the default version is 3.3.8, so that will need to change until the issue above is fixed 
  - I've only had success with `eigen@3.3.4`, but that also needs a patch to build

**Comment by EthanS94** [comment]
I opened #22050 with changes mentioned above.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.
