### ISSUE TITLE
Update to latest of all NetCDF Libraries

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#976]
There are some requirements about which versions of the interfaces are compatible with which versions of NetCDF.  So a little thought will have to go into updating the Spack packages.  See note below, from the NetCDF mailing list:
```
On 05/13/2016 09:12 PM, Ward Fisher wrote:
> Hello all,
>
> We’re happy to announce the availability of the following netCDF libraries
>
>   * netcdf-c 4.4.1-rc2
>   * netcdf-fortran 4.4.4
>   * netcdf-cxx4 4.3.0
>
>
>     netCDF-C 4.4.1-rc2

Looks good here, thanks.

>     netCDF-Fortran 4.4.4

Since this fails to compile with netcdf-4.3.3.1 with:

libtool: link: gfortran -I../../fortran -I../fortran -O2 -g -pipe -Wall
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic
-I/usr/lib64/gfortran/modules -Wl,-z -Wl,relro -o .libs/nf_test
f03lib_f_interfaces.o test_get.o test_put.o nf_error.o nf_test.o test_read.o
test_write.o util.o f03lib.o  ../fortran/.libs/libnetcdff.so -lnetcdf
-Wl,-rpath -Wl,/usr/lib64
../fortran/.libs/libnetcdff.so: undefined reference to `nc_open_mem'
collect2: error: ld returned 1 exit status

It's worth adding a check for the version of netcdf-c needed.

Compiles fine against 4.4.0 here. Still seeing
https://github.com/Unidata/netcdf-fortran/issues/42 though, although I believe
that's expected.


>
>     netCDF-Cxx4 4.3.0

Compiles fine here.


--
Orion Poplawski
Technical Manager                     303-415-9701 x222
NWRA, Boulder/CoRA Office             FAX: 303-415-9702
3380 Mitchell Lane                       orion@nwra.com
Boulder, CO 80301                   http://www.nwra.com
```
