### PR TITLE
py-mpi4py: add v4.0.0

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

File: var/spack/repos/builtin/packages/py-mpi4py/package.py [hunk 1]
```diff
@@ -37,6 +38,7 @@ class PyMpi4py(PythonPackage):
     depends_on("fortran", type="build")  # generated
```
Comment (dalcinl) [inline var/spack/repos/builtin/packages/py-mpi4py/package.py]: I'm not sure what this is about, but just in case: mpi4py does not depend on C++ or Fortran, the C compiler is enough.

Comment (dalcinl) [reply var/spack/repos/builtin/packages/py-mpi4py/package.py]: Maybe this line was autogenerated simply because the mpi4py tarball contains some C++ and Fortran code in the demo/ directory to showcase interoperability with other languages.

File: var/spack/repos/builtin/packages/py-mpi4py/package.py [hunk 2]
```diff
@@ -19,6 +19,7 @@ class PyMpi4py(PythonPackage):
     license("BSD-2-Clause")
```
Comment (dalcinl) [inline var/spack/repos/builtin/packages/py-mpi4py/package.py]: In mpi4py-4.0.0, the license was changed to BSD-3-Clause

```suggestion
    license("BSD-3-Clause")
```

**Comment by dalcinl** [comment]
@balay Maybe you should update the "pypi" class attribute to point to the 4.0.0 tarball?

File: var/spack/repos/builtin/packages/py-mpi4py/package.py (hunk 1 above)
Comment (balay) [reply var/spack/repos/builtin/packages/py-mpi4py/package.py]: Ok removed the C++, Fortran lines

File: var/spack/repos/builtin/packages/py-mpi4py/package.py (hunk 2 above)
Comment (balay) [reply var/spack/repos/builtin/packages/py-mpi4py/package.py]: Added now

**Comment by balay** [comment]
> @balay Maybe you should update the "pypi" class attribute to point to the 4.0.0 tarball?

The URL is used as a template - so it doesn't need updating each time there is a new release.

File: var/spack/repos/builtin/packages/py-mpi4py/package.py [hunk 3]
```diff
@@ -15,10 +15,13 @@ class PyMpi4py(PythonPackage):
 
     pypi = "mpi4py/mpi4py-3.0.3.tar.gz"
     git = "https://github.com/mpi4py/mpi4py.git"
+    maintainers("dalcinl", "balay")
```
Comment (balay) [inline var/spack/repos/builtin/packages/py-mpi4py/package.py]: @dalcinl Is it ok to add you to maintainers?

Comment (dalcinl) [reply var/spack/repos/builtin/packages/py-mpi4py/package.py]: No, I cannot take such responsibility, sorry. conda-forge maintenance already takes more bandwidth than the one I have available.

Comment (balay) [reply var/spack/repos/builtin/packages/py-mpi4py/package.py]: ok reverted

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256, rest LGTM.

**Comment by tldahlgren** [comment]
@kwryankrattiger @sshudler Any objections to the change to `sensei`?

**Review by kwryankrattiger — APPROVED** [review]
I am assuming there was some build issue here, I don't have an issue adding this.

**Comment by balay** [comment]
> I am assuming there was some build issue here, I don't have an issue adding this.

The failures are at:
- https://gitlab.spack.io/spack/spack/-/jobs/12710865
- https://gitlab.spack.io/spack/spack/-/jobs/12711008

I have the following in the commit message:
```
build with py-mpi4py@4.0.0 gives:

In file included from /tmp/root/spack-stage/spack-stage-sensei-5.0.0-ljvl2tuclcjb2lclg6v4dwyaubi6d35a/spack-build-ljvl2tu/sensei/PythonAnalysisPYTHON_wrap.cxx:3326:
/tmp/root/spack-stage/spack-stage-sensei-5.0.0-ljvl2tuclcjb2lclg6v4dwyaubi6d35a/spack-src/sensei/PythonAnalysis.cxx:6:10: fatal error: mpi4py/mpi4py.MPI_api.h: No such file or directory

```
Presumably mpi4py@4.0.0 is not exposing this file anymore..

**Comment by dalcinl** [comment]
> Presumably mpi4py@4.0.0 is not exposing this file anymore..

That file was never intended to be included directly (although mpi4py did not enforce it).
The correct include line should be `#include <mpi4py/mpi4py.h>`

**Comment by kwryankrattiger** [comment]
I am not going to patch for fix that in the immediate future, so feel free to merge anyway. I can make an issue in the SENSEI project to fix this.

**Comment by bernhardkaindl** [comment]
@spackbot re-run pipeline

**Review by bernhardkaindl — APPROVED** [review]
Build passed on Ubuntu 22.04.4 LTS:
```py
Passed: py-mpi4py@4.0.0 sensei
spack find -v:
[+]  py-mpi4py@4.0.0
[+]  sensei@5.0.0~adios2~ascent~catalyst~hdf5~ipo~libsim~miniapps~python+shared~vtkio build_system=cmake build_type=Release generator=make
```
Generated by:
https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py

**Comment by balay** [comment]
This CI timeout failure is reported/discussed at https://spackpm.slack.com/archives/C02N33GM28H/p1727578201540449 - so will have to restart the pipeline after its resolved.

**Comment by balay** [comment]
Ah - didn't realize #46712 is merged - so rebased this MR now (hopefully this pipeline completes before timeout)

**Comment by balay** [comment]
Hm - I see different failures now - don't know if they will flag the pipeline as "failed"

https://gitlab.spack.io/spack/spack/-/jobs/12780471
```
$ spack buildcache update-index --keys s3://spack-binaries-prs/pr46652_balay/mpi4py-4.0.0/ml-linux-x86_64-cpu
==> Warning: Failed to use aws s3 sync to retrieve specs, falling back to parallel fetch
==> Error: Error reading specfile: s3://spack-binaries-prs/pr46652_balay/mpi4py-4.0.0/ml-linux-x86_64-cpu/build_cache/linux-ubuntu24.04-x86_64_v3-gcc-13.2.0-py-h5py-3.11.0-dbg2vrhr3li5yugvvvu5t5yzeuu5pzj7.spec.json: Download of s3://spack-binaries-prs/pr46652_balay/mpi4py-4.0.0/ml-linux-x86_64-cpu/build_cache/linux-ubuntu24.04-x86_64_v3-gcc-13.2.0-py-h5py-3.11.0-dbg2vrhr3li5yugvvvu5t5yzeuu5pzj7.spec.json failed: URLError: <urlopen error An error occurred (AccessDenied) when calling the GetObject operation: User: arn:aws:sts::588562868276:assumed-role/GitLabRunnerPRBinaryMirror-blue/GitLabRunner-12780471-f6daedf7 is not authorized to perform: s3:GetObject on resource: "arn:aws:s3:::spack-binaries-prs/pr46652_balay/mpi4py-4.0.0/ml-linux-x86_64-cpu/build_cache/linux-ubuntu24.04-x86_64_v3-gcc-13.2.0-py-h5py-3.11.0-dbg2vrhr3li5yugvvvu5t5yzeuu5pzj7.spec.json" because no identity-based policy allows the s3:GetObject action>
==> Error: Encountered problem pushing package index to s3://spack-binaries-prs/pr46652_balay/mpi4py-4.0.0/ml-linux-x86_64-cpu/build_cache: error parsing JSON spec:
    'NoneType' object has no attribute 'read'
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: command terminated with exit code 1
```
cc: @eugeneswalker

**Comment by balay** [comment]
@spackbot run pipeline
