### ISSUE TITLE
Python error in m4 package file for OS X 10.11

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/spack#2829]
Receiving an error on OS X 10.11.6 (using Homebrew installed gcc@6.2.0):

```
==> Already patched m4
==> Building m4 [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: AttributeError: 'str' object has no attribute 'version'
```

It looks like the `.version` of `platform_os` does not exist as referenced in m4 package.py:
```
(spec.architecture.platform_os.version == '10.12')
```

This appears to have been introduced in commit 6ef6428331db023cc8f7af2ca5ff86ab488ad777 .

**Comment by adamjstewart** [comment]
@davydden

**Comment by davydden** [comment]
something must have changed since September and now `spec.architecture.platform_os` mis-behaves.  @tgamblin  @alalazo any ideas?

**Comment by alalazo** [comment]
@davydden Here's [the history](https://github.com/LLNL/spack/commits/develop/lib/spack/spack/architecture.py) for `architecture.py`. I don't have an OSX machine to do it myself, but I would try checking out 193f68083f71f43027e8c89e11319b9e64a70bce and see if it works. Then go on with the other commits in the history and check which one breaks the package.

**Comment by davydden** [comment]
i think `platform_os` used to contain an object of type `OperatingSystem` but now it is a string. I will try to dig more...

**Comment by davydden** [comment]
ok, this behaviour is due to 552b4eae9e633e380e9ebe323222dc6a805aaaa2 . @xjrc how can one get `os` version after your patch?
