### PR TITLE
Bugfix for spec objects modified by flag handlers

### LINKED ISSUE #33680: Installation issue: ncurses
### Steps to reproduce the issue

```console
$ spack spec -I ncurses

Input spec
--------------------------------
 -   ncurses

Concretized
--------------------------------
 -   ncurses@6.3%gcc@9.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-broadwell
[+]      ^pkgconf@1.8.0%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-broadwell

...
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: AttributeError: 'str' object has no attribute 'propagate'

The 'ncurses' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (d4ea74bf80bde99a5d96ec0bbe9e872961f4679b)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** clingo

### Additional information

_No response_

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by becker33**
Fixes #33680

This issue was introduced in #29761:

```
==> Installing ncurses-6.3-22hz6q6cvo3ep2uhrs3erpp2kogxncbn
==> No binary for ncurses-6.3-22hz6q6cvo3ep2uhrs3erpp2kogxncbn found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/97/97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059.tar.gz
==> No patches needed for ncurses
==> ncurses: Executing phase: 'autoreconf'
==> ncurses: Executing phase: 'configure'
==> ncurses: Executing phase: 'build'
==> ncurses: Executing phase: 'install'
==> Error: AttributeError: 'str' object has no attribute 'propagate'

The 'ncurses' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/spack/lib/spack/spack/build_environment.py:1075, in _setup_pkg_and_run:
       1072        tb_string = traceback.format_exc()
       1073
       1074        # build up some context from the offending package so we can
  >>   1075        # show that, too.
       1076        package_context = get_package_context(tb)
       1077
       1078        logfile = None
```

It turns out this was caused by a bug that had been around much longer, in which the flags were passed by reference to the flag_handler, and the flag_handler was modifying the spec object, not just the flags given to the build system. The scope of this bug was limited by the forking model in Spack, which is how it went under the radar for so long.

PR includes regression test.

@tgamblin @lee218llnl

### CODE REVIEW

**Review by tgamblin — DISMISSED** [review]

**Comment by tgamblin** [comment]
@spackbot fix style

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
CI failures here were unrelated to this PR, so I merged b/c a lot of people are hitting this one on `develop`.

**Comment by migueldiascosta** [comment]
I'm still getting ` Error: AttributeError: 'str' object has no attribute 'propagate'`, on a fresh instance `0.20.0.dev0` (e47beceb8a665aba360813fb55aa08cc8bd86dbe)

This at the `install` step of the `berkeleygw` package - does it need to be modified in some way?

(`make install` does seem to run, but Spack then exits with this error)
