### ISSUE TITLE
Installation issue: py-torch +breakpad fails to build on RHEL@9.2

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#40629]
### Steps to reproduce the issue

```console
$ spack install py-torch@1.10%gcc=7.5.0 arch=x86_64
```

### Error message

<details><summary>Error message</summary>

<pre>
  >> 3433    /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqssa3/spack-src/third_par
             ty/breakpad/src/client/linux/handler/exception_handler.cc:141:65: error: no matching function for call t
             o 'max(int, long int)'
     3434       static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
     3435                                                                     ^
     3436    In file included from /disk/hpcpm/3vg_spack/0171/opt/spack/linux-rhel9-x86_64/gcc-11.3.1/gcc-7.5.0-ldgnc
             vpwbmnr3kjxaxdzarrvecdyl5ov/include/c++/7.5.0/bits/char_traits.h:39:0,
     3437                     from /disk/hpcpm/3vg_spack/0171/opt/spack/linux-rhel9-x86_64/gcc-11.3.1/gcc-7.5.0-ldgnc
             vpwbmnr3kjxaxdzarrvecdyl5ov/include/c++/7.5.0/string:40,
     3438                     from /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqss
             a3/spack-src/third_party/breakpad/src/client/linux/handler/exception_handler.h:38,
     3439                     from /tmp/sbulut/spack-stage/spack-stage-py-torch-1.10.0-56lrpr454rywkayd2smjuvrtjuvqss
             a3/spack-src/third_party/breakpad/src/client/linux/handler/exception_handler.cc:66:

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.17.1
* **Python:** 3.9.16
* **Platform:** linux-rhel9-skylake_avx512
* **Concretizer:** clingo

### Additional information

can provide build out later if necessary.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
my spack env with py-torch was building fine on centos7. It seems `+breakpad` is enabled by default. Not sure, if it's useful for me, so I'll disable it. However, it would be nice to be able build the same spack env without any modifications on RHEL9.2.

**Comment by Sinan81** [comment]
The issue was also reported to py-torch:
https://github.com/pytorch/pytorch/issues/70297

**Comment by Sinan81** [comment]
a fix was proposed at: https://github.com/pytorch/pytorch/pull/70298

**Comment by Sinan81** [comment]
if i understand correctly, breakpad was removed in later versions of py-torch:
https://github.com/pytorch/pytorch/pull/75394

**Comment by Sinan81** [comment]
@adamjstewart should breakpad be disabled by default?

**Comment by adamjstewart** [comment]
I would rather match the defaults used by [CMakeLists.txt](https://github.com/pytorch/pytorch/blob/v1.11.0/CMakeLists.txt#L212) as I also don't know what they're for or whether or not they're important.

Out of curiosity, why do you need PyTorch 1.10? If you use a modern version, this should no longer be an issue. If you really need 1.10, I'll work on patching the submodule.

**Comment by Sinan81** [comment]
We're using version 1.10 since that's the latest version that came with spack@0.17.1 Also, If I remember correctly, before we switched to Spack to build our computational environment,  this version enabled a smooth transition from cuda@10 to cuda@11, and hence we continued with it. It's essential that version 1.10 builds since it's used in our production environment, currently running on centos7, and it's useful to replicate this environment in our next distro, RHEL9.2. That being said, we'll probably upgrade spack and a lot packages in our spack env within the next year.

It would be great if you could patch it. Thanks @adamjstewart
