### PR TITLE
Fix issue with Mac OS version detection in m4 package.

### LINKED ISSUE #2829: Python error in m4 package file for OS X 10.11
Receiving an error on OS X 10.11.6 (using Homebrew installed gcc@6.2.0):

```
==> Already patched m4
==> Building m4 [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: AttributeError: 'str' object has no attribute 'version'
```

It looks like the `.version` of `platform_os` does not exist as referenced in m4 package.py:
```
(spec.architecture.platform_os.version == '10.12')
```

This appears to have been introduced in commit 6ef6428331db023cc8f7af2ca5ff86ab488ad777 .

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #2829.

Updates version check in m4 package to reflect current state of `ArchSpec`.  I think there is still more simplifying that can be done with the platform support, but this should at least work.

### CODE REVIEW

**Comment by tgamblin** [comment]
@davydden: does this fix it for you?

File: var/spack/repos/builtin/packages/m4/package.py [hunk 1]
```diff
@@ -52,8 +52,9 @@ def configure_args(self):
             args.append('--without-libsigsegv-prefix')
 
         # http://lists.gnu.org/archive/html/bug-m4/2016-09/msg00002.html
-        if (sys.platform == 'darwin') and (spec.satisfies('%gcc')) and \
-           (spec.architecture.platform_os.version == '10.12'):
+        arch = spec.architecture
+        if (arch.platform == 'darwin' and arch.platform_os == 'sierra' and
```
Comment (davydden) [inline var/spack/repos/builtin/packages/m4/package.py]: you can remove `import sys` then. Will test this soon...

Comment (tgamblin) [inline var/spack/repos/builtin/packages/m4/package.py]: oops good catch

**Comment by davydden** [comment]
@tgamblin i also checked if there is any other package which use the old code, nothing but `m4`. So it should be good to merge.
