### PR TITLE
Fix unexpected keyword error in Python 2.6

### PR DESCRIPTION
**Pull request by adamjstewart**
When running `spack --profile` in Python 2.6, it would crash with the following error:
```
TypeError: runctx() got an unexpected keyword argument 'sort'
```
@alalazo It looks like this was introduced in [#2502](https://github.com/LLNL/spack/commit/7ea10e768ee1a7deab98ae538d916bbeeb0346b8#diff-2ab958d4c46d792e62ac6ba4f9146173R211). According to the [documentation](https://docs.python.org/2/library/profile.html#profile.runctx), `run` takes this parameter but `runctx` does not. Interestingly enough, it actually works in Python 2.7 even though it isn't in the documentation. But it makes the profiler crash in Python 2.6.

### CODE REVIEW

**Comment by adamjstewart** [comment]
P.S. This isn't the first time `spack --profile` support has been broken for Python 2.6 (see #1639 and #1656). If someone wants to add unit tests for this, we can prevent it from breaking again.

**Comment by adamjstewart** [comment]
Ping @tgamblin

**Comment by adamjstewart** [comment]
Ping ping @tgamblin. This doesn't really affect me, but I figured I should close out old PRs.

**Comment by adamjstewart** [comment]
This prevents the documentation tests from passing locally in Python 2.6, so I'm going to merge it.
