### ISSUE TITLE
llvm@main fails: expected primary-expression before '>' token

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#25617]
### Steps to reproduce the issue

`llvm@main +clang +compiler-rt +libcxx +lld +lldb +llvm_dylib ~cuda` fails to build using:
* `spack@develop` (e4e4bf75ca1f640901621e18bfa0d69e4f5474c6 from `Wed Aug 25 16:35:49 2021 -0600`)
* Ubuntu 20.04, GCC 9.3.0

Concrete spec: [llvm.spec.yaml.txt](https://github.com/spack/spack/files/7050471/llvm.spec.yaml.txt)

Reproduced below using Docker container image `ecpe4s/ubuntu20.04-runner-x86_64:2021-07-01`

```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./llvm.spec.yaml
OK

$> spack install --no-cache -f ./llvm.spec.yaml
...
==> Installing llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax
==> No patches needed for llvm
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'

48 errors found in build log:
     8166    In file included from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/compare:130,
     8167                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/utility:226,
     8168                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__functional_base:26,
     8169                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/memory:671,
     8170                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/libcxxabi/src/include/atomic_support.h:17,
     8171                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/libcxxabi/src/cxa_default_handlers.cpp:18:
  >> 8172    /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__compare/compare_three_way_result.h:28:45: error: expected
             primary-expression before '>' token
     8173       28 |   declval<__make_const_lvalue_ref<_Tp>>() <=> declval<__make_const_lvalue_ref<_Up>>(), void()
     8174          |                                             ^
  >> 8175    /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__compare/compare_three_way_result.h:30:69: error: expected
             primary-expression before '>' token
     8176       30 |     using type = decltype(declval<__make_const_lvalue_ref<_Tp>>() <=> declval<__make_const_lvalue_ref<_Up>>());
     8177          |                                                                     ^
     8178    [ 20%] Building CXX object utils/benchmark/src/CMakeFiles/benchmark.dir/reporter.cc.o
     8179    cd /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/utils/benchmark/src && /spack/lib/spack/env/gcc/g++ -DHAVE_POSIX_REGEX -
             DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7
             pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/utils/benchmark/src -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/bench
             mark/src -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnji
             xcy5dk523it3seaosznlax/spack-src/llvm/include -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/include -I/tmp/r
             oot/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/src/../include -std=c++11 -fPIC -fno-semantic-interposition -fvisibili
             ty-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fall
             through -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment
              -Wmisleading-indentation -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exc
             eptions  -Wno-suggest-override  -Wstrict-aliasing -O3 -DNDEBUG -std=c++14 -MD -MT utils/benchmark/src/CMakeFiles/benchmark.dir/reporter.cc.o -MF CMakeFiles/benchmark.dir/re
             porter.cc.o.d -o CMakeFiles/benchmark.dir/reporter.cc.o -c /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/src/r
             eporter.cc
     8180    [ 20%] Building CXX object utils/benchmark/src/CMakeFiles/benchmark.dir/sleep.cc.o
     8181    cd /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/utils/benchmark/src && /spack/lib/spack/env/gcc/g++ -DHAVE_POSIX_REGEX -
             DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7
             pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/utils/benchmark/src -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/bench
             mark/src -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnji
             xcy5dk523it3seaosznlax/spack-src/llvm/include -I/tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/include -I/tmp/r
             oot/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/src/../include -std=c++11 -fPIC -fno-semantic-interposition -fvisibili
             ty-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fall
             through -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment
              -Wmisleading-indentation -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exc
             eptions  -Wno-suggest-override  -Wstrict-aliasing -O3 -DNDEBUG -std=c++14 -MD -MT utils/benchmark/src/CMakeFiles/benchmark.dir/sleep.cc.o -MF CMakeFiles/benchmark.dir/sleep
             .cc.o.d -o CMakeFiles/benchmark.dir/sleep.cc.o -c /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/llvm/utils/benchmark/src/sleep.cc

     ...

     8184                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__algorithm/search.h:16,
     8185                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/functional:490,
     8186                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/algorithm:653,
     8187                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/libcxxabi/src/demangle/StringView.h:17,
     8188                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/libcxxabi/src/demangle/ItaniumDemangle.h:22,
     8189                     from /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-src/libcxxabi/src/cxa_demangle.cpp:13:
  >> 8190    /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__compare/compare_three_way_result.h:28:45: error: expected
             primary-expression before '>' token
     8191       28 |   declval<__make_const_lvalue_ref<_Tp>>() <=> declval<__make_const_lvalue_ref<_Up>>(), void()
     8192          |                                             ^
  >> 8193    /tmp/root/spack-stage/spack-stage-llvm-main-mbzkg7pnjixcy5dk523it3seaosznlax/spack-build-mbzkg7p/include/c++/v1/__compare/compare_three_way_result.h:30:69: error: expected
             primary-expression before '>' token
     8194       30 |     using type = decltype(declval<__make_const_lvalue_ref<_Tp>>() <=> declval<__make_const_lvalue_ref<_Up>>());
     8195          |
...
```

### Information on your system

* **Spack:** 0.16.2-4031-e4e4bf75ca
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** original

### Additional information

Build log: [llvm-build-out.txt](https://github.com/spack/spack/files/7050474/llvm-build-out.txt)

@trws @naromero77

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by eugeneswalker** [comment]
This problem does not occur when I use `gcc@11.2.0`, all else being the same.

**Comment by trws** [comment]
Main is often fragile this way, does main build outside of spack with gcc 9.3?

**Comment by eugeneswalker** [comment]
> Main is often fragile this way, does main build outside of spack with gcc 9.3?

I don't know about outside of Spack. But I do know that, the exact same commit of llvm@main:
* builds with GCC 11.2.0
* doesn't build with GCC 9.3.0

Because I added a custom `version()` call to the package.py for llvm. Exact same concretized spec, exact same commit of llvm main, but gcc 9.3.0 doesn't work, gcc 11.2.0 works.

```
   version('main-2021-08-27-9dd74ee3', commit='9dd74ee3f08e029bac00257cfc8ab8412cbcea6c')
```

**Comment by trws** [comment]
Ok.  When and if that becomes a tagged version we'll want to have a conflict with that gcc version, and possibly lower.  It sounds like this isn't a package issue though since using a higher gcc works, so I'm going to close this pending something to be fixed in the packaging.
