### ISSUE TITLE
Adios does not build with HDF5 1.10

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1683]
The `adios` variant `+hdf5` is broken. The error is
```
In file included from /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/hdf5-1.10.0-patch1-ijwvzsvpcbne33bffg6nrefdwgguofji/include/H5public.h:145:0,
                 from /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/hdf5-1.10.0-patch1-ijwvzsvpcbne33bffg6nrefdwgguofji/include/hdf5.h:24,
                 from bp2h5.c:39:
bp2h5.c:46:13: error: two or more data types in declaration specifiers
 typedef int bool;
             ^
bp2h5.c:46:1: warning: useless type name in empty declaration
 typedef int bool;
 ^~~~~~~
bp2h5.c: In function ‘main’:
bp2h5.c:173:17: warning: implicit declaration of function ‘H5LTmake_dataset’ [-Wimplicit-function-declaration]
                 H5LTmake_dataset(HDF5_FILE,h5name,1,count,h5_type_id,v->value);
                 ^~~~~~~~~~~~~~~~
make[3]: *** [bp2h5-bp2h5.o] Error 1
make[3]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0/utils/bp2h5'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0/utils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/eschnetter/spack-stage/spack-stage-0LLmsR/ADIOS-1.10.0'
```

It seems that Adios expects `bool` to be undefined, but it is already defined. It might be that HDF5 1.10 includes `<stdbool.h>`.

**Comment by tgamblin** [comment]
@ax3l @robertdfrench do you know if adios supports HDF5 1.10?

**Comment by ax3l** [comment]
Good question, have to ask @pnorbert upstream on that.

**Comment by ax3l** [comment]
Just realized: maybe the correct dependency is actually parallel hdf5 aka "hdf5+mpi" in spack.

**Comment by pnorbert** [comment]
You are right, the new hdf5.h breaks the adios compile in bp2h5.c. Fixed in commit 3b21a8a41509 of ADIOS.

**Comment by eschnett** [comment]
I guess this means that Spack should add the respective version constraint to its HDF5 dependency, in addition to potentially requiring the `+mpi` variant.

**Comment by citibeth** [comment]
I would suggest the following to resolve this issue:

1. Add a note to the adios/package.py explaining the following:
> It seems that Adios expects bool to be undefined, but it is already defined. It might be that HDF5 1.10 includes <stdbool.h>.
>
> You are right, the new hdf5.h breaks the adios compile in bp2h5.c. Fixed in commit 3b21a8a41509 of ADIOS. 

2. Unless there's some big reason not to, make adios depends_on('hdf5:1.10').  Problem solved.

3. If (2) is not possible, then create a Spack-defined "bogus" version of adios that's linked to commit 3b21a8a41509.  Call that version 1.10.0.1

4. Once the upstream fix gets released, remove the "interim" version of adios from Spack, and just go with version 1.10.1 (or whatever they call it).

**Comment by pnorbert** [comment]
ADIOS does not require or depend on the hdf5 or parallel-hdf5 packages. Nor
the netcdf packages. I would just skip configuring adios with these. I have
not built adios on any machine with them for years. Practically no one uses
them through adios and they cause most of the build troubles.

**Comment by citibeth** [comment]
I'm interested in feedback on the commit referenced above.  I used Adios as an example, even if it's not the best example (for reasons unrelated to point made in the text).

**Comment by ax3l** [comment]
Let us not make it too complicated.
We can simply apply [the patch](https://github.com/ornladios/ADIOS/commit/3b21a8a41509) to ADIOS <= 1.10 when compiled with HDF 1.10+ (version coincidence! :D) via the spack patch system.

Or @pnorbert releases a backport 1.10.1 ;) 

Let me try the spack patch system for a fix, will report back.

**Comment by ax3l** [comment]
@citibeth thank you for updating the docs! btw, is there a way to express "any version but X.Y.Z" as a dependency? (e.g., I can build a project against any version in boost but not 1.60.0)

**Comment by citibeth** [comment]
Good point, I added the following to the docs section on buggy software:
```
^^^^^^^
Patches
^^^^^^^

Spack's source patching mechanism provides another way to fix bugs in
upstream projects.  This has the advantage that it can fix bugs in
existing released versions.  However, it has some disadvantages:

1. Although patches of a few lines work OK, large patch files can be
   hard to create and maintain.

2. The user loses the automation provided by Git or similar.
```

**Comment by citibeth** [comment]
@tgamblin do you know the answer to this question?  If there is a way, I'll
document it.

> @citibeth <https://github.com/citibeth> thank you for updating the docs!
> btw, is there a way to express "any version but X.Y.Z" as a dependency?
> (e.g., I can build a project against any version in boost but not 1.60.0)
>
