### PR TITLE
Patch to add hsa prefix/include path

### PR DESCRIPTION
**Pull request by renjithravindrankannath**

### CODE REVIEW

**Comment by mwkrentel** [comment]
@renjithravindrankannath I was working on essentially the same patch myself, and I spent most of yesterday inventoring the different possibilities.

I agree the `define-hip-platform` patch should be removed.
It refers to files that don't exist.

Do you know an example where the extra path for `ROCM_HSA_IFLAGS` is
necessary?  For me, 2024.01.1 builds cleanly on RH 8.x with `/opt/rocm-6.0.0`.
Does it depend on a spack-built ROCM vs downloaded?

I'd like to add the following conflict.  The API in hip/rocm
frequently changes and the previous rev, `2023.08.1` doesn't
understand rocm 6.x.
```
  conflicts(
      "^hip@6:", when="@:2023", msg="rocm 6.x requires hpctoolkit 2024.01.1 or later"
  )
```
Put it right after the conflict for `hip 5.3`.
With that, then I'll approve.

Btw, for package PRs, we normally write the subject with the name of
the package first followed by colon, as in `hpctoolkit: ...`.

Thanks for looking at this!

**Comment by renjithravindrankannath** [comment]
> @renjithravindrankannath I was working on essentially the same patch myself, and I spent most of yesterday inventoring the different possibilities.
> 
> I agree the `define-hip-platform` patch should be removed. It refers to files that don't exist.
> 
> Do you know an example where the extra path for `ROCM_HSA_IFLAGS` is necessary? For me, 2024.01.1 builds cleanly on RH 8.x with `/opt/rocm-6.0.0`. Does it depend on a spack-built ROCM vs downloaded?
> 
> I'd like to add the following conflict. The API in hip/rocm frequently changes and the previous rev, `2023.08.1` doesn't understand rocm 6.x.
> 
> ```
>   conflicts(
>       "^hip@6:", when="@:2023", msg="rocm 6.x requires hpctoolkit 2024.01.1 or later"
>   )
> ```
> 
> Put it right after the conflict for `hip 5.3`. With that, then I'll approve.
> 
> Btw, for package PRs, we normally write the subject with the name of the package first followed by colon, as in `hpctoolkit: ...`.
> 
> Thanks for looking at this!

Hi @mwkrentel ,

Thank you for reviewing the changes.

Yes. With Spack built ROCM it depends on ROCM_HSA_IFLAGS. 
When ROCM_HSA_IFLAGS is set only as [hsa-rocr-dev-prefix]/include/hsa 2024.01.1 build was failing with 6.0 and 6.1.
I was able to build 2023.08.1 with 6.0 and 6.1 with these changes on Spack built ROCM.
However I can add the conflicts as suggested if it doesn't work with API in hip/rocm on6.0 or with /opt/rocm-6.0.0 .
Thanks

**Comment by mwkrentel** [comment]
@renjithravindrankannath It took some time to build, but yes, I can reproduce your results
with different results for spack-built rocm vs downloaded rocm in `/opt/rocm`.

It's complicated and we probably have the wrong include paths in our
code in some places and it's such a moving target.  Blech.

Ok, I approve your patch.  If you don't mind, I'd like to add the
conflict for 2023.08.1 and hip 6.x.  We normally do development with
the downloaded `/opt/rocm-x.y.z` and if you're using rocm 6.x, then
you should really be using 2024.01.1.

It's either that or else the `correcting-hsa` patch needs to be
extended to 2023.08, and it would need to be a different patch,
and then it would only work with spack-built rocm.

And I think the hpctoolkit version in the `when` clause for the patch needs
to be `@2024` or `@2024.01` in order to pick up the `2024.01.stable` branch.

**Comment by mwkrentel** [comment]
Yes, the `when` clause for `correcting-hsa-include-path.patch` needs to be:
```
when="@2024.01 ^hip@6.0:"
```
With `@2024.01.1`, the patch is not applied to `2024.01.stable` and
the build for toolkit `+rocm` with spack-built rocm fails with:
```
     1996    In file included from gpu/amd/rocprofiler-api.c:60:
  >> 1997    /scratch/krentel/spack/install/linux-rhel8-zen/gcc-8.5.0/rocprofiler-dev-6.1.0-3pxzac7g6hxn7q7gyl
             6ivega7kk2zoij/include/rocprofiler/rocprofiler.h:83:10: fatal error: hsa/amd_hsa_kernel_code.h: N
             o such file or directory
     1998     #include <hsa/amd_hsa_kernel_code.h>
     1999              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     2000    compilation terminated.
```

And yes, I would prefer to add the conflict for `"^hip@6:", when="@:2023"` as above.
The downloaded rocm case is more common and what we develop against
and that case does fail.

**Comment by renjithravindrankannath** [comment]
> Yes, the `when` clause for `correcting-hsa-include-path.patch` needs to be:
> 
> ```
> when="@2024.01 ^hip@6.0:"
> ```
> 
> With `@2024.01.1`, the patch is not applied to `2024.01.stable` and the build for toolkit `+rocm` with spack-built rocm fails with:
> 
> ```
>      1996    In file included from gpu/amd/rocprofiler-api.c:60:
>   >> 1997    /scratch/krentel/spack/install/linux-rhel8-zen/gcc-8.5.0/rocprofiler-dev-6.1.0-3pxzac7g6hxn7q7gyl
>              6ivega7kk2zoij/include/rocprofiler/rocprofiler.h:83:10: fatal error: hsa/amd_hsa_kernel_code.h: N
>              o such file or directory
>      1998     #include <hsa/amd_hsa_kernel_code.h>
>      1999              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>      2000    compilation terminated.
> ```
> 
> And yes, I would prefer to add the conflict for `"^hip@6:", when="@:2023"` as above. The downloaded rocm case is more common and what we develop against and that case does fail.

Understood. Added the conflict and updated the patch applicability as recommended.
Thanks

**Review by mwkrentel — APPROVED** [review]
I approve, ready to merge.
Thanks!

**Comment by renjithravindrankannath** [comment]
Hi @tldahlgren , Can you please review and merge.

**Review by tldahlgren — APPROVED** [review]
