### PR TITLE
Fix Qt4 build on Yosemite (10.11)

### LINKED ISSUE #2903: Qt fails to build with XCode 8 on Sierra
subj, with 
```
   Xcode not set up properly. You may need to confirm the license
   agreement by running /usr/bin/xcodebuild without arguments.
```
Perhaps while copying  Xcode to inject compiler wrappers, one should do
```
ln -s xcodebuild xcrun
```
(see http://stackoverflow.com/questions/39492617/xcode-8-error-project-error-xcode-not-set-up-properly-even-though-the-licens)

Similar issue on macPorts https://trac.macports.org/ticket/52200

@mathstuf did you see that error before?

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #2903.

@davydden: this worked for me on 10.11.  Can you verify for Sierra?

I am not sure whether this is a minimal set of changes (particularly the `dbus` pieces) but it builds.

### CODE REVIEW

**Comment by davydden** [comment]
unfortunately still fails on Sierra with compiler errors:
```
clang++ -c -pipe -std=gnu++98 -stdlib=libc++ -mmacosx-version-min=10.7 -isysroot /Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -O2 -Wall -W  -I../../../mkspecs/unsupported/macx-clang-libc++ -I. -o db2.o db2.cpp
db2.cpp:42:10: fatal error: 'sqlcli.h' file not found
#include <sqlcli.h>
..
clang++ -c -pipe -std=gnu++98 -stdlib=libc++ -mmacosx-version-min=10.7 -isysroot /Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -O2 -Wall -W  -I../../../mkspecs/unsupported/macx-clang-libc++ -I. -o ibase.o ibase.cpp
ibase.cpp:42:10: fatal error: 'ibase.h' file not found
#include <ibase.h>
...
clang++ -c -pipe -std=gnu++98 -stdlib=libc++ -mmacosx-version-min=10.7 -isysroot /Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -O2 -Wall -W  -I../../../mkspecs/unsupported/macx-clang-libc++ -I. -o mysql.o ../mysql/mysql.cpp
../mysql/mysql.cpp:42:10: fatal error: 'mysql.h' file not found
#include "mysql.h"
...
clang++ -c -pipe -std=gnu++98 -stdlib=libc++ -mmacosx-version-min=10.7 -isysroot /Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -arch x86_64 -O2 -Wall -W  -I../../../mkspecs/unsupported/macx-clang-libc++ -I. -o oci.o oci.cpp
oci.cpp:42:10: fatal error: 'oci.h' file not found
#include <oci.h>
```
and a few others

**Comment by tgamblin** [comment]
Ok, I will work on the sierra build separately.  This at least fixes Yosemite.
