### ISSUE TITLE
spack arch/spack spec hang on Edison

### ISSUE THREAD

**Issue by mamelara** [LLNL/spack#1929]
Tried to run spack spec and spack arch on Edison and it hangs. Not looping in concretize.

**Comment by mamelara** [comment]
Update from this post: Looks like the issue is coming from self._default_target_from_env in Cray.py.  It hangs on this statement:

            output = env('USER=%s' % os.environ['USER'],
                         'HOME=%s' % os.environ['HOME'],
                         '/bin/bash', '--noprofile', '--norc', '-c',
                         '. /etc/profile; module list -lt',
                         output=str, error=str)

**Comment by pramodk** [comment]
@mamelara : see this #1969. I saw this on two cray system (occasionally due to filesystem issue). I accidentally put some spack commands in .bashrc and had to ask admins to remove .bashrc  :)

**Comment by mamelara** [comment]
That did work for me. But now I'm getting an AttributeError: 'module' object has no attribute 'config'.
```
Traceback (most recent call last):
  File "./spack", line 98, in <module>
    import spack
  File "/global/u2/m/mamelara/myspack/lib/spack/spack/__init__.py", line 72, in <module>
    import spack.repository
  File "/global/u2/m/mamelara/myspack/lib/spack/spack/repository.py", line 45, in <module>
    import spack.config
  File "/global/u2/m/mamelara/myspack/lib/spack/spack/config.py", line 307, in <module>
    _platform = spack.architecture.platform().name
  File "/global/u2/m/mamelara/myspack/lib/spack/llnl/util/lang.py", line 187, in __call__
    self.cache[args] = self.func(*args)
  File "/global/u2/m/mamelara/myspack/lib/spack/spack/architecture.py", line 530, in platform
    return platform_cls()
  File "/global/u2/m/mamelara/myspack/lib/spack/spack/platforms/cray.py", line 49, in __init__
    conf = spack.config.get_config('targets')
AttributeError: 'module' object has no attribute 'config'
```
Probably a circular import?

**Comment by mpbelhorn** [comment]
If using the latest Spack develop branch, there is a cyclic dependency with the
spack configs. The Cray platform attempts to read `targets.yaml` from the
configs to instantiate and the configs need an instance of `platforms.Cray` to
be importable.

I have a hotfix that I've been using on our Crays (https://github.com/mpbelhorn/
spack/blob/cray_platform_hotfix/lib/spack/spack/platforms/cray.py) but haven't
had a chance to submit a proper PR for it yet. If someone wants to go ahead with
that before me, feel free.

Cheers,
Matt

**Comment by mpbelhorn** [comment]
Opened PR  #2121 for the cyclic dependency introduced by #2030

**Comment by mpbelhorn** [comment]
If using the latest Spack develop branch, there is a cyclic dependency with the
spack configs. The Cray platform attempts to read `targets.yaml` from the
configs to instantiate and the configs need an instance of `platforms.Cray` to
be importable.

I have a hotfix that I've been using on our Crays (https://github.com/mpbelhorn/
spack/blob/cray_platform_hotfix/lib/spack/spack/platforms/cray.py) but haven't
had a chance to submit a proper PR for it yet. If someone wants to go ahead with
that before me, feel free.

Cheers,
Matt


-- 
Matt Belhorn
OLCF Support Consultant
Oak Ridge National Laboratory

**Comment by tgamblin** [comment]
@mpbelhorn: is this fixed with #2121?

**Comment by mpbelhorn** [comment]
@tgamblin fixed is a strong word. It does make the platform usable, but also strips out support for a 'frontend' target which we at the OLCF don't use anyway. 

We had been running with only the changes to llib/spack/spack/platforms/cray.py since #2030 but I didn't want to make a PR until removing the now presumably unused `targets.yaml`. Our Crays are down for maintenance today and I have not checked that taking out 'targets.yaml' doesn't introduce any new issues.
