### PR TITLE
boost: Refactor header-only install and add missing compiled libraries

### PR DESCRIPTION
**Pull request by msimberg**
- In #46062 I added a somewhat clunky way of installing header-only boost while going through `b2` etc. I discovered there's a much simpler way: `--with-libraries=headers`. This changes the boost package to use that instead when no compiled libraries are requested and avoids the awkward dance of with/without-libraries.
- This also adds three compiled libraries that were added since 1.81.0: charconv, cobalt, and url.

### CODE REVIEW

File: var/spack/repos/builtin/packages/boost/package.py [hunk 1]
```diff
@@ -680,49 +683,43 @@ def install(self, spec, prefix):
             env["PATH"] = newdir + ":" + env["PATH"]
 
         with_libs = list()
```
Comment (haampie) [inline var/spack/repos/builtin/packages/boost/package.py]: Maybe smth like

```python
with_libs = {f"+{lib}" for lib in Boost.all_libs}

if ...:
    with_libs.discard(...)
```

instead of `remove_if_in_list`? discard doesn't thrown an exception

Only thing is that a set is unordered, so maybe use `sorted(with_libs)` later, or something.

Comment (msimberg) [reply var/spack/repos/builtin/packages/boost/package.py]: Thanks, that looks much nicer: https://github.com/spack/spack/pull/46281/commits/a5fe300a96323ccac2b6c7adc230015f50b18561.

**Review by haampie — DISMISSED** [review]

**Comment by msimberg** [comment]
The trilinos failure is again the same as in https://github.com/spack/spack/pull/45812, i.e. https://gitlab.spack.io/spack/spack/-/jobs/12472734#L2047:
```
  >> 27802    /tmp/gitlab-runner-1/spack-stage/spack-stage-trilinos-13.0.1-muas
              dhtnsspurrcp6b3efe5q7gmf5e63/spack-src/packages/amesos/src/Amesos
              _Superludist.cpp:514:9: error: use of undeclared identifier 'DOUB
              LE'
     27803            DOUBLE
     27804            ^
```
This seems unrelated to the changes here.

**Comment by haampie** [comment]
That's an issue with cray's libsci, so it's allowed to fail :)

**Review by haampie — APPROVED** [review]
