### PR TITLE
mypy: add more ignored modules to `pyproject.toml`

### LINKED ISSUE #38704: spack style: mypy checks installed environment packages
### Steps to reproduce

1. Create a managed environment with a view and some python sources, and install it
2. Run `spack style -t mypy`

### Error message

An example on my system:
```console
> spack style -t mypy                                                                                                                                                                                    17.5s
==> Running style checks on spack
  selected: mypy
==> Modified files
...
==> Running mypy checks
var/spack/environments/system/.spack-env/view/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2346: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
  mypy found errors
==> Error: spack style found errors
```

### Information on your system

* **Spack:** 0.21.0.dev0 (11bc27d984a1008f254abf6690c2d96c418b0c42)
* **Python:** 3.10.10
* **Platform:** darwin-ventura-m2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #38704.

`mypy` will check *all* imported packages, even optional dependencies outside your project, and this can cause issues if you are targeting python versions *older* than the one you're running in. `mypy` will report issues in the latest versions of dependencies as errors even if installing on some older python would have installed an older version of the dependency.

We saw this problem before with `numpy` in #34732. We've started seeing it with IPython in #38704. This fixes the issue by exempting `IPython` and a number of other imports of Spack's from `mypy` checking.

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -146,7 +146,23 @@ ignore_missing_imports = true
   # arguments, which don't work in 3.7, which causes mypy to bail out early if you have
   # numpy installed.
   [[tool.mypy.overrides]]
-  module = 'numpy'
+  module = [
```
Comment (alalazo) [inline pyproject.toml:150]: We need to update the comment above, otherwise LGTM

**Review by alalazo — CHANGES_REQUESTED** [review]

File: pyproject.toml [hunk 2]
```diff
@@ -146,7 +146,23 @@ ignore_missing_imports = true
...
+      'botocore',
+      'distro',
+      'jinja2',
+      'jsonschema',
+      'macholib',
+      'markupsafe',
+      'numpy',
+      'pyristent',
+      'pytest',
+      'ruamel',
```
Comment (adamjstewart) [inline pyproject.toml]: On this branch I'm seeing:
```console
> spack style -t mypy                                                                                                                                                                                           0.2s
==> Running style checks on spack
  selected: mypy
==> Modified files
==> Running mypy checks
lib/spack/spack/util/spack_yaml.py:26: error: Module "ruamel.yaml" has no attribute "comments"  [attr-defined]
lib/spack/spack/util/spack_yaml.py:26: error: Module "ruamel.yaml" has no attribute "constructor"  [attr-defined]
lib/spack/spack/util/spack_yaml.py:26: error: Module "ruamel.yaml" has no attribute "emitter"  [attr-defined]
lib/spack/spack/util/spack_yaml.py:26: error: Module "ruamel.yaml" has no attribute "error"  [attr-defined]
lib/spack/spack/util/spack_yaml.py:26: error: Module "ruamel.yaml" has no attribute "representer"  [attr-defined]
Found 5 errors in 1 file (checked 578 source files)
  mypy found errors
==> Error: spack style found errors
```
Not sure why I'm the only one seeing this. It's definitely using the vendored copy too, I don't have ruamel installed.

Comment (tgamblin) [reply pyproject.toml]: I've seen this as well -- what files are modified vs. develop for you right now?

Comment (adamjstewart) [reply pyproject.toml]: None, I'm on your branch with no modified files.

Comment (tgamblin) [reply pyproject.toml]: what commit is develop at

Comment (adamjstewart) [reply pyproject.toml]: 297891152077a018acb7dd2b656e9018e46a5d5c

**Review by adamjstewart — DISMISSED** [review]
Works now, thanks for the quick fix!

File: pyproject.toml (hunk 1 above)
Comment (adamjstewart) [reply pyproject.toml:150]: Ping @tgamblin

**Comment by tgamblin** [comment]
@alalazo should be good to go now.

**Review by adamjstewart — APPROVED** [review]

**Review by alalazo — APPROVED** [review]
