### ISSUE TITLE
Installation issue: libffi on power 8

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#16602]
Trying to build `libffi@3.3` on `power8` using `gcc@7.3.0` results in the error shown below. Using `spack@develop` checked out at commit `7813e4146459` from 12-May-2020. Even when target=ppc64le is specified:

```
$> spack install libffi target=ppc64le
...
==> Error: Failed to install libffi due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j16'
7 errors found in build log:
     260    ../src/java_raw_api.c:337:1: note: declared here
     261     ffi_prep_java_raw_closure_loc (ffi_java_raw_closure* cl,
     262     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     263    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -I. -I../include -Iinclude -I../
            src -MT src/powerpc/linux64.lo -MD -MP -MF src/powerpc/.deps/linux64.Tpo -c ../src/powerpc/linux64.S -o src/powerpc/linux64.o >/dev/null 2>&1
     264    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/types.lo -MD -MP -MF src/.deps/types.Tpo -c ../src/types.c -o src/types.o >/dev/nu
            ll 2>&1
     265    In file included from ../src/powerpc/ffi.c:33:0:
  >> 266    ../src/powerpc/ffi_powerpc.h:61:9: error: '_Float128' is not supported on this target
     267     typedef _Float128 float128;
     268             ^~~~~~~~~
     269    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/powerpc/ffi_sysv.lo -MD -MP -MF src/powerpc/.deps/ffi_sysv.Tpo -c ../src/powerpc/f
            fi_sysv.c -o src/powerpc/ffi_sysv.o >/dev/null 2>&1
     270    Makefile:1273: recipe for target 'src/powerpc/ffi.lo' failed
  >> 271    make[3]: *** [src/powerpc/ffi.lo] Error 1
     272    make[3]: *** Waiting for unfinished jobs....
     273    In file included from ../src/powerpc/ffi_linux64.c:35:0:
  >> 274    ../src/powerpc/ffi_powerpc.h:61:9: error: '_Float128' is not supported on this target
     275     typedef _Float128 float128;
     276             ^~~~~~~~~
     277    Makefile:1273: recipe for target 'src/powerpc/ffi_linux64.lo' failed
  >> 278    make[3]: *** [src/powerpc/ffi_linux64.lo] Error 1
     279    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c -o
             src/java_raw_api.o >/dev/null 2>&1
     280    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/raw_api.lo -MD -MP -MF src/.deps/raw_api.Tpo -c ../src/raw_api.c -o src/raw_api.o
            >/dev/null 2>&1
     281    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF src/.deps/prep_cif.Tpo -c ../src/prep_cif.c -o src/prep_ci
            f.o >/dev/null 2>&1
     282    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstric
            t-aliasing -ffast-math -mcpu=power8 -Wall -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c -o src/closure
            s.o >/dev/null 2>&1
     283    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-libffi-3.3-hjmp26qlv2hwyz7q4agyxsahgovsvzdt/spack-src/powerpc64le-unknown-linux-gnu
            '
     284    Makefile:1347: recipe for target 'all-recursive' failed
  >> 285    make[2]: *** [all-recursive] Error 1
     286    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-libffi-3.3-hjmp26qlv2hwyz7q4agyxsahgovsvzdt/spack-src/powerpc64le-unknown-linux-gnu
            '
     287    Makefile:622: recipe for target 'all' failed
  >> 288    make[1]: *** [all] Error 2
     289    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-libffi-3.3-hjmp26qlv2hwyz7q4agyxsahgovsvzdt/spack-src/powerpc64le-unknown-linux-gnu
            '
     290    Makefile:592: recipe for target 'all-all' failed
  >> 291    make: *** [all-all] Error 2
```

@michaelkuhn @ax3l @skosukhin

**Comment by eugeneswalker** [comment]
`libffi@3.2.1` builds fine on power8, just not version `3.3`... I will leave this issue up for now unless told to close it.

**Comment by ax3l** [comment]
cc @chuckatkins that should hit y'all with the default configuration of ADIOS2, too. `libffi` is pulled by SST which is default-on. What do you build with on Summit?

**Comment by ax3l** [comment]
cross-link: upstream but report https://github.com/libffi/libffi/issues/531

@eugeneswalker does this patch (https://github.com/libffi/libffi/pull/532) work for you? We could apply it to the 3.3 release in Spack.

**Comment by eugeneswalker** [comment]
Unfortunately, no, it does not work. It's interesting, because I get the exact same error, which indicates that `defined(__FLOAT128_TYPE__)` is evaluating true in the preprocessor conditional:

<b>ffi_powerpc.h</b>
```
#if defined(__FLOAT128_TYPE__)
typedef _Float128 float128;
#elif defined(__FLOAT128__)
typedef __float128 float128;
#else
//typedef __int128 float128;
typedef char float128[16] __attribute__((aligned(16)));
#endif
```

Even with this change, the same error is returned:
```
$> spack install libffi target=ppc64le
...
  >> 247    ../src/powerpc/ffi_powerpc.h:61:9: error: '_Float128' is not supported on this
            target
     248     typedef _Float128 float128;
```

Any ideas why it thinks float128 is available?

@ax3l

**Comment by ax3l** [comment]
let me cc @eisenhauer and @chuckatkins on this. This is pulled as a default dependency in ADIOS2 with the default variant `+sst` on. They probably have an idea about the problems with libffi and power.

As a solution that does not break the whole stack by default, one could change the default of ADIOS2 to the spec `adios2 ~sst`on power8 to disable pulling the libffi dependency. This disables SST altogether as I cannot see a more fine-grained control to disable code generation features in DILL yet: https://github.com/GTkorvo/dill/issues/15

**Comment by ax3l** [comment]
I just found a related patch in CMake: https://gitlab.kitware.com/paraview/common-superbuild/commit/a197c0ffda18fc7de48a98d41d753521787086fa

This looks to me like it has landed in libffi [master](https://github.com/libffi/libffi/blob/2e90bb5577ea1fe3bc1716954e790999bc3549f7/src/powerpc/ffi_powerpc.h#L60-L61) already but is not part of libffi [3.3](https://github.com/libffi/libffi/blob/v3.3/src/powerpc/ffi_powerpc.h#L60-L61).

Will open a PR to patch this into 3.3: https://github.com/libffi/libffi/pull/561
Please see: #17043
