### ISSUE TITLE
Installation issue: perl

### ISSUE THREAD

**Issue by tepperly** [LLNL/spack#21744]
### Steps to reproduce the issue

```console
$ spack install gcc@7.3.0+bootstrap+binutils^libc+iconv
$ spack compiler find
==> Added 1 new compiler to /home/epperly2/tmp/spack/var/spack/environments/ol6/spack.yaml
    gcc@7.3.0
==> Compilers are defined in the following files:
    /home/epperly2/.spack/linux/compilers.yaml
    /home/epperly2/tmp/spack/var/spack/environments/ol6/spack.yaml
$ spack install emacs%gcc@7.3.0
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/pkgconf-1.7.3-ridnfohoheeikphfhwncij64mpys4hsr
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/berkeley-db-18.1.40-zrmu5cu2veekhethshmrdrj36ltfovf3
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/zlib-1.2.11-xjsck64mrww72obm747mseqxurjuod4u
==> Installing nasm-2.15.05-nkob4xmk3mq6ip32gm2xutx6mcpclhib
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for nasm-2.15.05-nkob4xmk3mq6ip32gm2xutx6mcpclhib found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/3c/3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f.tar.xz
==> nasm: Executing phase: 'autoreconf'
==> nasm: Executing phase: 'configure'
==> nasm: Executing phase: 'build'
==> nasm: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/nasm-2.15.05-nkob4xmk3mq6ip32gm2xutx6mcpclhib
==> Installing libiconv-1.16-7roszuprcilqm4oqgdtvklcqpir7jyg4
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for libiconv-1.16-7roszuprcilqm4oqgdtvklcqpir7jyg4 found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
######################################################################## 100.0%
==> libiconv: Executing phase: 'autoreconf'
==> libiconv: Executing phase: 'configure'
==> libiconv: Executing phase: 'build'
==> libiconv: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/libiconv-1.16-7roszuprcilqm4oqgdtvklcqpir7jyg4
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/xz-5.2.5-uh5ydgzxgrojzjgq3s3kc5cvbfltfrvr
==> Installing pcre-8.44-kvvofx2lrzeqpdjoneqa5g6sji2p7bgl
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for pcre-8.44-kvvofx2lrzeqpdjoneqa5g6sji2p7bgl found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/19/19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d.tar.bz2
######################################################################## 100.0%
==> pcre: Executing phase: 'autoreconf'
==> pcre: Executing phase: 'configure'
==> pcre: Executing phase: 'build'
==> pcre: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/pcre-8.44-kvvofx2lrzeqpdjoneqa5g6sji2p7bgl
==> Installing pkgconf-1.7.3-nljqqwa3a3xfohjoaujp2ba6bwsezlvq
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for pkgconf-1.7.3-nljqqwa3a3xfohjoaujp2ba6bwsezlvq found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/b8/b846aea51cf696c3392a0ae58bef93e2e72f8e7073ca6ad1ed8b01c85871f9c0.tar.xz
==> pkgconf: Executing phase: 'autoreconf'
==> pkgconf: Executing phase: 'configure'
==> pkgconf: Executing phase: 'build'
==> pkgconf: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/pkgconf-1.7.3-nljqqwa3a3xfohjoaujp2ba6bwsezlvq
==> Installing berkeley-db-18.1.40-q2aqaotkg6r2zukbprney2cxab4qbt67
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for berkeley-db-18.1.40-q2aqaotkg6r2zukbprney2cxab4qbt67 found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/0c/0cecb2ef0c67b166de93732769abdeba0555086d51de1090df325e18ee8da9c8.tar.gz
==> berkeley-db: Executing phase: 'autoreconf'
==> berkeley-db: Executing phase: 'configure'
==> berkeley-db: Executing phase: 'build'
==> berkeley-db: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/berkeley-db-18.1.40-q2aqaotkg6r2zukbprney2cxab4qbt67
==> Installing zlib-1.2.11-swgyv4kosxiby2lbadc3k7ux5be6hu3b
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for zlib-1.2.11-swgyv4kosxiby2lbadc3k7ux5be6hu3b found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/c3/c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1.tar.gz
==> zlib: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/zlib-1.2.11-swgyv4kosxiby2lbadc3k7ux5be6hu3b
==> Installing nasm-2.15.05-kjlcejeeh5pvqjhjyi4i4bmfch4b3yjv
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for nasm-2.15.05-kjlcejeeh5pvqjhjyi4i4bmfch4b3yjv found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/3c/3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f.tar.xz
==> nasm: Executing phase: 'autoreconf'
==> nasm: Executing phase: 'configure'
==> nasm: Executing phase: 'build'
==> nasm: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/nasm-2.15.05-kjlcejeeh5pvqjhjyi4i4bmfch4b3yjv
==> Installing libiconv-1.16-l5htxxbmpr5bglve3aaxn4ambl2yh7gn
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for libiconv-1.16-l5htxxbmpr5bglve3aaxn4ambl2yh7gn found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
==> libiconv: Executing phase: 'autoreconf'
==> libiconv: Executing phase: 'configure'
==> libiconv: Executing phase: 'build'
==> libiconv: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/libiconv-1.16-l5htxxbmpr5bglve3aaxn4ambl2yh7gn
==> Installing xz-5.2.5-lbvg5ufmi52pkuhuxrtz2wwsjcretntt
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for xz-5.2.5-lbvg5ufmi52pkuhuxrtz2wwsjcretntt found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/51/5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df.tar.bz2
==> xz: Executing phase: 'autoreconf'
==> xz: Executing phase: 'configure'
==> xz: Executing phase: 'build'
==> xz: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/xz-5.2.5-lbvg5ufmi52pkuhuxrtz2wwsjcretntt
==> Installing pcre-8.44-7fffg4va7cfdd2vr3arhdow4fj77dhkb
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for pcre-8.44-7fffg4va7cfdd2vr3arhdow4fj77dhkb found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/19/19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d.tar.bz2
==> pcre: Executing phase: 'autoreconf'
==> pcre: Executing phase: 'configure'
==> pcre: Executing phase: 'build'
==> pcre: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/pcre-8.44-7fffg4va7cfdd2vr3arhdow4fj77dhkb
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/ncurses-6.2-k4p7vgo7yjzfme46oe3njyzt7o4ctnfj
==> Installing libxml2-2.9.10-ymucaw7hpltjo47h2a6ehkd6cslnxxxy
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for libxml2-2.9.10-ymucaw7hpltjo47h2a6ehkd6cslnxxxy found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/aa/aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f.tar.gz
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/96/96151685cec997e1f9f3387e3626d61e6284d4d6e66e0e440c209286c03e9cc7.tar.gz
==> Moving resource stage
	source : /tmp/epperly2/spack-stage/resource-xmlts-ymucaw7hpltjo47h2a6ehkd6cslnxxxy/spack-src/
	destination : /tmp/epperly2/spack-stage/spack-stage-libxml2-2.9.10-ymucaw7hpltjo47h2a6ehkd6cslnxxxy/spack-src/xmlconf
==> libxml2: Executing phase: 'autoreconf'
==> libxml2: Executing phase: 'configure'
==> libxml2: Executing phase: 'build'
==> libxml2: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/libxml2-2.9.10-ymucaw7hpltjo47h2a6ehkd6cslnxxxy
==> Installing ncurses-6.2-l2zenvns36qae6wg66sltr5bsouupxuq
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for ncurses-6.2-l2zenvns36qae6wg66sltr5bsouupxuq found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/30/30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d.tar.gz
==> ncurses: Executing phase: 'autoreconf'
==> ncurses: Executing phase: 'configure'
==> ncurses: Executing phase: 'build'
==> ncurses: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/ncurses-6.2-l2zenvns36qae6wg66sltr5bsouupxuq
==> Installing libxml2-2.9.10-uzjo6ou2m5rczcwje7zwwcrnnulwyshy
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for libxml2-2.9.10-uzjo6ou2m5rczcwje7zwwcrnnulwyshy found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/aa/aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f.tar.gz
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/96/96151685cec997e1f9f3387e3626d61e6284d4d6e66e0e440c209286c03e9cc7.tar.gz
==> Moving resource stage
	source : /tmp/epperly2/spack-stage/resource-xmlts-uzjo6ou2m5rczcwje7zwwcrnnulwyshy/spack-src/
	destination : /tmp/epperly2/spack-stage/spack-stage-libxml2-2.9.10-uzjo6ou2m5rczcwje7zwwcrnnulwyshy/spack-src/xmlconf
==> libxml2: Executing phase: 'autoreconf'
==> libxml2: Executing phase: 'configure'
==> libxml2: Executing phase: 'build'
==> libxml2: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/libxml2-2.9.10-uzjo6ou2m5rczcwje7zwwcrnnulwyshy
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/readline-8.0-6aichfnfi65mqpdhzu7e6mvoruu6sbdr
==> Installing readline-8.0-c6kecxdsabf2a4jnnqkrux5kyzus2bwq
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for readline-8.0-c6kecxdsabf2a4jnnqkrux5kyzus2bwq found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/e3/e339f51971478d369f8a053a330a190781acb9864cf4c541060f12078948e461.tar.gz
==> readline: Executing phase: 'autoreconf'
==> readline: Executing phase: 'configure'
==> readline: Executing phase: 'build'
==> readline: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/readline-8.0-c6kecxdsabf2a4jnnqkrux5kyzus2bwq
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/gdbm-1.18.1-4p3o6llqcnacq7dnyyfdmmillyvjocvm
==> Installing gdbm-1.18.1-7z2dmer2sedmbrydgv7wobfkfs3qdyvb
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for gdbm-1.18.1-7z2dmer2sedmbrydgv7wobfkfs3qdyvb found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/86/86e613527e5dba544e73208f42b78b7c022d4fa5a6d5498bf18c8d6f745b91dc.tar.gz
==> gdbm: Executing phase: 'autoreconf'
==> gdbm: Executing phase: 'configure'
==> gdbm: Executing phase: 'build'
==> gdbm: Executing phase: 'install'
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-haswell/gcc-7.3.0/gdbm-1.18.1-7z2dmer2sedmbrydgv7wobfkfs3qdyvb
[+] /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/perl-5.32.0-5vwnbefia2ehz2uxampg6npgead4j3an
==> Installing perl-5.32.0-7n2b6dpncpgw4oqey2a3gxa7lqnczio2
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for perl-5.32.0-7n2b6dpncpgw4oqey2a3gxa7lqnczio2 found: installing from source
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/ef/efeb1ce1f10824190ad1cadbcccf6fdb8a5d37007d0100d2d9ae5f2b5900c0b4.tar.gz
==> Using cached archive: /home/epperly2/tmp/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Moving resource stage
	source : /tmp/epperly2/spack-stage/resource-cpanm-7n2b6dpncpgw4oqey2a3gxa7lqnczio2/spack-src/
	destination : /tmp/epperly2/spack-stage/spack-stage-perl-5.32.0-7n2b6dpncpgw4oqey2a3gxa7lqnczio2/spack-src/cpanm/cpanm
==> perl: Executing phase: 'configure'
==> perl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

6 errors found in build log:
     939    time64.c:573:30: warning: 'orig_year' may be used uninitialized in 
            this function [-Wmaybe-uninitialized]
     940                 local_tm->tm_year++;
     941                 ~~~~~~~~~~~~~~~~~^~
     942    cc -fstack-protector-strong -L/home/epperly2/tmp/spack/opt/spack/li
            nux-ol6-haswell/gcc-7.3.0/gdbm-1.18.1-7z2dmer2sedmbrydgv7wobfkfs3qd
            yvb/lib -o miniperl \
     943    	    opmini.o perlmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.
            o util.o mg.o reentr.o mro_core.o keywords.o hv.o av.o run.o pp_hot
            .o sv.o pp.o scope.o pp_ctl.o pp_sys.o doop.o doio.o regexec.o utf8
            .o taint.o deb.o universal.o globals.o perlio.o perlapi.o numeric.o
             mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o 
             miniperlmain.o  -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
     944    /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/binuti
            ls-2.35.1-k2rambek72vpwaetsf2s4z7infhbyadm/bin/ld: locale.o: in fun
            ction `S_emulate_setlocale':
  >> 945    locale.c:(.text+0x438): undefined reference to `libintl_textdomain'
  >> 946    /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/binuti
            ls-2.35.1-k2rambek72vpwaetsf2s4z7infhbyadm/bin/ld: locale.c:(.text+
            0x440): undefined reference to `libintl_textdomain'
  >> 947    /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/binuti
            ls-2.35.1-k2rambek72vpwaetsf2s4z7infhbyadm/bin/ld: locale.c:(.text+
            0x674): undefined reference to `libintl_textdomain'
  >> 948    /home/epperly2/tmp/spack/opt/spack/linux-ol6-core2/gcc-4.4.7/binuti
            ls-2.35.1-k2rambek72vpwaetsf2s4z7infhbyadm/bin/ld: locale.c:(.text+
            0x67c): undefined reference to `libintl_textdomain'
  >> 949    collect2: error: ld returned 1 exit status
  >> 950    make: *** [lib/buildcustomize.pl] Error 1
     951    make: *** Waiting for unfinished jobs....

See build log for details:
  /tmp/epperly2/spack-stage/spack-stage-perl-5.32.0-7n2b6dpncpgw4oqey2a3gxa7lqnczio2/spack-build-out.txt
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tepperly** [comment]
```console
 spack debug report
* **Spack:** 0.16.0
* **Python:** 2.6.6
* **Platform:** linux-ol6-haswell
```

**Comment by haampie** [comment]
Does the problem go away when you add `depends_on('gettext')` to perl?

**Comment by tepperly** [comment]
How would I add a dependency to perl when requesting an emacs build?

**Comment by haampie** [comment]
spack edit perl

And then add that line

**Comment by cessenat** [comment]
No solution just my experience on 3 tests

First, relevant or not, when I run 
spack install gcc@7.3.0+bootstrap+binutils^libc+iconv
it compiles gettext:
==> Installing gettext-0.21-h3eef4tu42azkga2yhffkc4mkdocxxje

Then, to make spack find the new compiler, I had to do
spack load gcc@7.3.0+bootstrap+binutils^libc+iconv

+ With that sequence, I did reproduce the bug you are talking about on Cent OS 7.8
Adding the dependency to gettext from perl did NOT change:
==> Installing perl-5.32.1-wojq5ixwtuxz2ykxocdfmbytoaim6ldv
     941    /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld : lo
            cale.o : dans la fonction « S_emulate_setlocale » :
     942    locale.c:(.text+0x438) : référence indéfinie vers « libintl_textdomain »
  >> 946    collect2: error: ld returned 1 exit status
     947    make: *** [lib/buildcustomize.pl] Erreur 1
spack debug report
* **Spack:** 0.16.0-1080-0b58499
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** original

+ Nevertheless, I did not reproduce the bug with by my company pre-built gcc@7.3.0.

+ Neither did it, with your sequence, on an Ubuntu 18.04.

Just a thought, what about putting perl as "externals" ?

**Comment by haampie** [comment]
You're not using gcc 7.3.0 but 10.2.0 as you can see from the logs.

Try `spack compilers find` to register 7.3.0 and then use it with `spack install perl %gcc@7.3.0`

**Comment by cessenat** [comment]
You are right  ; maybe I had some dirty env ;
I restarted the process and now also get the same eroor for -lintl missing from gettext or glibc:
6 errors found in build log:
     935    time64.c:573:30: warning: 'orig_year' may be used uninitialized in this function [-Wmaybe-uninitialized]
     936                 local_tm->tm_year++;
     937                 ~~~~~~~~~~~~~~~~~^~
     938    cc -fstack-protector-strong -L/home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-7.3.0/gdbm-1.18.1-4uh7ve5vxgdbqxig5rl
            sesfdgvca3fuy/lib -o miniperl \
     939        opmini.o perlmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o hv.o av.o run
            .o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o doop.o doio.o regexec.o utf8.o taint.o deb.o universal.o globals.o perlio.o 
            perlapi.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o  -lpthread -lnsl -ldl 
            -lm -lcrypt -lutil -lc
     940    /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld: loc
            ale.o: in function `S_emulate_setlocale':
  >> 941    locale.c:(.text+0x438): undefined reference to `libintl_textdomain'
  >> 942    /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld: loc
            ale.c:(.text+0x440): undefined reference to `libintl_textdomain'
  >> 943    /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld: loc
            ale.c:(.text+0x674): undefined reference to `libintl_textdomain'
  >> 944    /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld: loc
            ale.c:(.text+0x67c): undefined reference to `libintl_textdomain'
  >> 945    collect2: error: ld returned 1 exit status
  >> 946    make: *** [lib/buildcustomize.pl] Error 1

**Comment by cessenat** [comment]
Maybe the good news @tepperly is that you are not alone ; this perl problem has a recent open issue
https://github.com/Perl/perl5/issues/18467
It seems not to be solved yet (how to make miniperl link add -lint)

**Comment by haampie** [comment]
Do older versions work? Does the compiler version matter at all?

spack install perl@x.y.z %gcc

**Comment by cessenat** [comment]
It fails with 5.16.3, 5.22.4, 5.30.3, all 5.32 and 5.33.3 so probably all release.
But, when I compile 5.16.3, 5.22.4, 5.30.3 with
spack install perl@5.30.3%gcc@7.3.0 ^binutils%gcc@7.3.0
while adding a dependency to binutils in perl, then it works, but still fails on 5.32 and 5.33.3 with :
/home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-10.2.0/binutils-2.35.1-nw2yophznz65aqjopzjrnboguaveqehm/bin/ld: locale.c:(.text+0x440)
            : undefined reference to `libintl_textdomain'
So, I thought probably there is an issue with mixing binutils from a compiler while using another compiler ; so instead of compiling with gcc@10.2.0, I restarted everything with gcc-8.4.0 that was already installed in my system.
I failed to make it work with 10.2.0, @tepperly failed with 4.4.7, so I tried with a not too far gcc release from your target 7.3.0.
So, from scratch, without modifying any package:
git clone https://github.com/spack/spack
. spack/share/spack/setup-env.sh
spack install gcc@7.3.0+bootstrap+binutils^libc+iconv   # uses my %gcc@8.4.0
spack load  gcc@7.3.0 ; spack compiler find
spack install emacs%gcc@7.3.0
=> it works at last.
So, maybe @tepperly you could install gcc@8.4.0 using the defaults, add it to your compilers and restart.

**Comment by tepperly** [comment]
Thanks, I'll try building gcc@8.4.0 before building 7.3.0.

**Comment by haampie** [comment]
Just to reiterate, you don't have to do `spack load gcc@x.y.z`, you only have to register the compiler with `spack compiler find`. Maybe spack load pollutes the environment in some way.

**Comment by ikitayama** [comment]
@haampie I experienced that `perl` is difficult to build if compiler is chosen other than GCC. Is this expected?
