### PR TITLE
ffmpeg: apply upstream fix for build with binutils 2.41

### PR DESCRIPTION
**Pull request by aumuell**
While spack does not yet provide binutils 2.41, they might still be installed. However, building ffmpeg on x86_64 fails with multiple errors like this:
./libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

also reported here: https://trac.ffmpeg.org/ticket/10405

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Thanks, binutils-2.41 was submitted to spack with #39483
