### PR TITLE
gxsview: add v2024.03.15

### PR DESCRIPTION
**Pull request by cessenat**
This is only a version update.

### CODE REVIEW

**Review by bernhardkaindl — COMMENTED** [review]
Summary:
```py
Project ERROR: Unknown module(s) in QT: multimedia
```
@cessenat, On a fresh clone of spack with this PR checked out,

I ran just `bin/spack install gsxview %gcc@13`, and got this result:
```py
==> Installing gxsview-2024.03.15-rizx4pilppf433kgjaufkakls5douz54 [147/147]
==> No binary for gxsview-2024.03.15-rizx4pilppf433kgjaufkakls5douz54 found: installing from source
==> Fetching https://www.nmri.go.jp/study/research_organization/risk/gxsview/download/gxsview-2024.03.15-src.zip
==> Applied patch /home/bkaindl/spack.4/var/spack/repos/builtin/packages/gxsview/vtk9.patch
==> gxsview: Executing phase: 'qmake'
==> [2024-10-12-16:51:58.888975] '/home/bkaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.3-pbp27u3xhdnvfuqzlbfvfxk3lubyio5i/bin/qmake' 'VTK_LIB_DIR=/home/bkaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/vtk-9.3.1-aoillyx5n4y6434uzfwul3sqlenyezqj/lib' 'VTK_INC_DIR=/home/bkaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/vtk-9.3.1-aoillyx5n4y6434uzfwul3sqlenyezqj/include/vtk-9.3' 'VTK_MAJOR_VER=9.3'
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
Info: creating stash file /home/bkaindl/spack.4/.stage/spack-stage-gxsview-2024.03.15-rizx4pilppf433kgjaufkakls5douz54/spack-src/gui/.qmake.stash
Project MESSAGE: REAL_TARGET:gxsview
Project MESSAGE: REAL_VERSION:2024.03.15
Project MESSAGE: VTK_LIB=/home/bkaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/vtk-9.3.1-aoillyx5n4y6434uzfwul3sqlenyezqj/lib
Project MESSAGE: VTK_INC=/home/bkaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/vtk-9.3.1-aoillyx5n4y6434uzfwul3sqlenyezqj/include/vtk-9.3
Project ERROR: Unknown module(s) in QT: multimedia
==> Error: ProcessError: Command exited with status 3:
```

I looked at the qt recipe briefly and AFAICS, the package.py automatically enables building qt-multimedia when OpenGL is enabled, but not sure.

Are you using an external QT to build gxsview?

PS: I'd like to ask if the minimum version of `vtk` can be raised to `"vtk@9:"` (e.g. for newer versions)
```py
depends_on("vtk@9:+qt+opengl2", when="@2024.03.15:") 
```
I had only failures so far when the build attempted to build vtk@8.2.1a in my environment.

In a fresh build, `Project ERROR: Unknown module(s) in QT: multimedia` did not occur (maybe because it built it from source where a binary cache might have been used before), but it looks like `vtk@9.3.1` might not yet be supported by `gxsview-2024.03.15` ?
```py
  >> 89    geometryviewer/trajectorypane/trajectorypane.cpp:38:10: fatal error: vtkQImageToImageSource.h: No such file or directory
     90       38 | #include <vtkQImageToImageSource.h>
     91          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cessenat** [comment]
> ```python
> depends_on("vtk@9:+qt+opengl2", when="@2024.03.15:") 
> ```

I did it too fast ; there are some issues with this latest release.
Thanks @bernhardkaindl for your remarks.
I compile both VTK and Qt using spack, as well as fontconfig and meson.
First concerning the 

> Project ERROR: Unknown module(s) in QT: multimedia

I add a 
`    conflicts("qt-base@6:", msg="Qt 6 support is not yet achieved")  # required for clingo
`
which seems to be required for clingo, not for the legacy concretizer.
See the developer's message at the end of this text.

Then, the other issues: 
* To get it work with VTK 9.0 one has to add 
in gui/geometryviewer/trajectorypane/trajectorycreatingworker.cpp
`#include <vtkUnsignedCharArray.h>
`right after
#include <vtkCellData.h>  // for coloring
* Then, on all of my tests, I had to remove the reference to
`#include <vtkQImageToImageSource.h>
`in gui/geometryviewer/trajectorypane/trajectorypane.cpp
* I have an issue with fontconfig include and lib not being positioned in the gui/Makefile correctly despite fontconfig is NOT an external package for my compilation ; this is solved installing  libfontconfig-dev on my Ubuntu 20.04 ; this is not clean, I'm working on it.
* Final issue, that is still on the cooker, is that a -lvtkRenderingQt-9.3 for VTK 9.3.1 is asked (lvtkRenderingQt-9.0 for VTK 9.0.3 and lvtkRenderingQt-9.2 for VTK 9.2.6) at link : this lib is not found and is not required.

For the two first issues, I add a patch. For the last issue, I'm not ready yet.
I'm in touch with the developer that indicates:
> I don't have tried Qt6 yet. Qt multimedia of Qt6 was drastically restructured, and
> so current sources may not be compiled with Qt6.
> 
> The errors you reported later are caused by insufficient header inclusion.
> (On my environment, Ubuntu 22 and 18, no error was reported)
> 
> Adding
> #include <vtkUnsignedCharArray.h> to
> geometryviewer/trajectorypane/trajectorycreatingworker.cpp
> might fix the problems.
> 
> However, updating VTK9.0 to VTK9.2 or VTK9.3 is the better solution.

**Comment by cessenat** [comment]
Finally, after some help, I succeeded to compile : just had to remove
`-lvtkRenderingQt$$VTK_VER_SUFFIX
`
in vtk9.pri
So, if libfontconfig-dev is installed, it is OK, for compiling.

Nevertheless, when running, I got a segv with versions compiled against VTK 9.2.6 and VTK 9.3.1. Is this related to fontconfig issue, I do not know, or if this is related to the fact I had to install libglvnd-dev on my Ubuntu 20.04:
`apt install libglvnd-dev
`I do not know either. It is probably not related to fontconfig since when using an external fontconfig I also get a segv with VTK 9.2.6 - with a recompiled VTK and qt 5.15.5.

With VTK 9.0.3 compilation and execution is fine ; here is my recipe:
`spack install gxsview@2024.03.15 %gcc ^vtk@9.0.3~mpi ^hdf5~mpi ^qt@5.15.5+dbus+opengl+gui~framework ^mesa+opengl ^zstd+programs
`
Maybe let us wait a few days so that I fix that.

**Comment by bernhardkaindl** [comment]
> With VTK 9.0.3 compilation and execution is fine ; here is my recipe:
`spack install gxsview@2024.03.15 %gcc ^vtk@9.0.3~mpi ^hdf5~mpi ^qt@5.15.5+dbus+opengl+gui~framework ^mesa+opengl ^zstd+programs`
Maybe let us wait a few days so that I fix that.

Great information, agreed!

**Comment by cessenat** [comment]
Now paths to fontconfig headers and lib is patched into the gui/gui.pro file.
So, this PR is OK for me, despite segvs with spack built VTK 9.3.1 or 9.2.6 - and I fail to build VTK 9.1 where I know gxsview functions properly on a RedHat system.  The segv issue may be due to the fact I had to
`apt install libglvnd-dev
`to compile VTK 9.2.6 and 9.3.1, so it may not be a gxsview issue.
Indeed I also have a VTK 9.0.3 with which gxsview makes a coredump.
One last point is that on Ubuntu lib path to fontconfig is /usr/lib/x86_64-linux-gnu while fontconfig.prefix.lib provides /usr/lib ; I'm not sure of the best way to manage that : as system libs are always found, is it a good idea to set the path to the lib/include when looking for an external ?

**Comment by cessenat** [comment]
Well, the gxsview developer confirmed to me that gxsview is OK with 9.2

> I'm developing Gxsview mainly on Debian 11 (x86_64) with Qt 5.15.1 and VTK 9.2.5 or 9.1.0. 

So I think this PR is OK now.

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS: These changed specs were found `gh pr diff`:
- `gxsview@2024.03.15`

The following specs were built (or installed) to check this PR:
### Using linux-ubuntu22.04-skylake / gcc@13.1.0:
<details><summary>Click on this line to unfold and refold the dependencies of this build


```py
gxsview@2024.03.15 build_system=qmake patches=99b8635,9e84b65
```
</summary>

Dependency tree (disabled variants are removed for the make the list the dependencies brief):
```py
gxsview@2024.03.15 build_system=qmake patches=99b8635,9e84b65
    fontconfig@2.15.0
        font-util@1.4.1 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1
            autoconf@2.72
            automake@1.16.5
            bdftopcf@1.1.1
                fontsproto@2.1.3
                libxfont@1.5.4
            mkfontdir@1.0.7
            mkfontscale@1.2.3
                libfontenc@1.1.8
            util-macros@1.20.1
        freetype@2.13.3+pic+shared
            bzip2@1.0.8+shared build_system=generic
                diffutils@3.10
        gmake@4.4.1 build_system=generic
        gperf@3.1 patches=3dd36db
        libxml2@2.10.3+pic+shared
            libiconv@1.17 libs=shared,static
        pkgconf@2.2.0
        python@3.11.9+bz2+crypt+ctypes+dbm+libxml2+lzma+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060
            gdbm@1.23
            gettext@0.22.5+bzip2+curses+git+libxml2+pic+shared+tar+xz
                tar@1.34 zip=pigz
                    pigz@2.8 build_system=makefile
            libffi@3.4.6
            libxcrypt@4.4.35_api patches=4885da3
            ncurses@6.5+termlib abi=none patches=7a351bc
            readline@8.2 patches=bbf97f1
        util-linux-uuid@2.40.2
    gcc-runtime@13.1.0 build_system=generic
    glibc@2.35
    qt@5.15.15+gui+opengl+shared+sql+ssl+tools build_system=generic patches=2081e9c,51aeba5,75bcb42,78c70fb,7f34d48,84b0991,8cd4be9,9378afd
        assimp@5.4.3+shared build_system=cmake
            cmake@3.22.1+ncurses+ownlibs build_system=generic patches=dbc3892
        double-conversion@3.3.0 build_system=cmake
        glib@2.78.3 build_system=meson buildtype=release default_library=shared tracing=none
            elfutils@0.191+exeprefix+nls
            meson@1.5.1 build_system=python_pip patches=0f0b1bd
                py-pip@23.1.2 build_system=generic
                py-setuptools@69.2.0 build_system=generic
                py-wheel@0.41.2 build_system=generic
                python-venv@1.0 build_system=generic
            ninja@1.12.1+re2c build_system=generic
                re2c@3.1
            perl@5.40.0+cpanm+opcode+open+shared+threads build_system=generic
                berkeley-db@18.1.40+cxx+stl patches=26090f4,b231fcc
        glx@1.4 build_system=bundle
            mesa@23.3.6+glx+llvm+opengl+osmesa build_system=meson buildtype=release default_library=shared
                flex@2.6.4+lex patches=f8b85a0
                glproto@1.4.17
                libunwind@1.6.2_signals_checks_exceptions_frame+docs+tests+weak_backtrace components=none libs=shared,static
                llvm@14.0.0+clang+gold+libomptarget_debug_llvm_dylib+llvm_dylib+lua+polly_dwarf build_system=cmake compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime patches=1f42874,25bc503,6379168,8248141,b216cff,cb8e645 shlib_symbol_version=none targets=all version_suffix=none
                py-mako@1.2.4 build_system=python_pip
                    py-markupsafe@2.1.3 build_system=python_pip
                xrandr@1.5.2
                    libxrandr@1.5.4
                    randrproto@1.5.0
        harfbuzz@10.0.1 build_system=meson buildtype=release default_library=shared
            cairo@1.16.0~X+ft+gobject+pdf+pic+shared patches=7097196,7c4da77
                pixman@0.42.2+shared
                which@2.21
            gobject-introspection@1.78.1 build_system=meson buildtype=release default_library=shared
        icu4c@74.2 cxxstd=11
            libtool@2.4.7
                findutils@4.9.0 patches=440b954
        libjpeg-turbo@3.0.3_decoder+pic build_system=cmake libs=shared,static
            nasm@2.16.03
        libmng@2.0.3 build_system=cmake
            lcms@2.16
        libpng@1.6.39 build_system=cmake libs=shared,static
        libsm@1.2.4
            libice@1.1.1
            xproto@7.0.31
            xtrans@1.5.0
        libtiff@4.6.0+ccitt+jpeg+logluv+lzw+next-jpeg+packbits+shared+thunder+zlib build_system=cmake
        libx11@1.8.10
            inputproto@2.3.2
            kbproto@1.0.7
            xextproto@7.3.0
        libxcb@1.17.0
            libpthread-stubs@0.5
            libxau@1.0.11
            libxdmcp@1.1.5
            xcb-proto@1.17.0
        libxext@1.3.6
        libxkbcommon@1.7.0 build_system=meson buildtype=release default_library=shared
            bison@3.8.2
            xkbdata@1.0.1
                xkbcomp@1.4.7
                    libxkbfile@1.1.3
        libxrender@0.9.11
            renderproto@0.11.1
        openssl@3.3.1+shared build_system=generic certs=mozilla
            ca-certificates-mozilla@2023-05-30 build_system=generic
        pcre2@10.44+multibyte
        sqlite@3.46.0+column_metadata+dynamic_extensions+fts+rtree
        xcb-util-image@0.4.1
            xcb-util@0.4.1
        xcb-util-keysyms@0.4.1
        xcb-util-renderutil@0.3.10
        xcb-util-wm@0.4.2
            m4@1.4.19+sigsegv patches=9dc5fbd,bfdffa7
                libsigsegv@2.14
        zlib-ng@2.2.1+compat_strategies+opt+pic+shared
        zstd@1.5.6+programs build_system=makefile compression=none libs=shared,static
    vtk@9.3.1+mpi+opengl2+qt build_system=cmake patches=2d38712,ff9dce4
        cgns@4.4.0_scope+hdf5_debug+mpi+scoping+shared build_system=cmake
        cmake@3.30.2+ncurses+ownlibs build_system=generic patches=dbc3892
            curl@8.8.0+nghttp2 libs=shared,static tls=openssl
                nghttp2@1.63.0
        eigen@3.4.0 build_system=cmake build_type=RelWithDebInfo
        expat@2.6.3+libbsd
            libbsd@0.12.2
                libmd@1.0.4
        gl2ps@1.4.2+png+zlib build_system=cmake
        glew@2.2.0 build_system=cmake patches=7992e52
        hdf5@1.14.3+hl+mpi+shared+tools api=default build_system=cmake patches=82088c8,f42732a
        jsoncpp@1.9.5 build_system=cmake
        libogg@1.3.5
        libtheora@1.1.1 patches=d9bb5a9,e01511a,e01ef71,ff8478d
        libxt@1.3.0
        lz4@1.9.4+pic build_system=makefile libs=shared,static
        netcdf-c@4.9.2+blosc+mpi_zip+optimize+parallel-netcdf+pic+shared+szip+zstd patches=0161eb8
            c-blosc@1.21.5+avx2 build_system=cmake
                snappy@1.2.1+pic+shared build_system=cmake
            libaec@1.0.6+shared build_system=cmake
            parallel-netcdf@1.12.3+cxx+fortran+pic+shared
        nlohmann-json@3.11.3+multiple_headers build_system=cmake
        openmpi@5.0.5+atomics-hwloc-libevent-pmix+rsh+vt+wrapper-rpath fabrics=none romio-filesystem=none schedulers=none
            hwloc@2.11.1+libxml2-level-zero+pci libs=shared,static
                libpciaccess@0.17
            libevent@2.1.12+openssl
            numactl@2.0.18
            openssh@9.8p1+gssapi
                krb5@1.21.2+shared
                libedit@3.1-20240808
            pmix@5.0.3
        proj@9.4.1+curl+shared+tiff build_system=cmake
        pugixml@1.14+pic+shared build_system=cmake
        seacas@2022-10-14+applications+cgns+fortran+legacy+matio+mpi+shared+tests_safe+x11 build_system=cmake patches=d088208
            fmt@9.1.0+pic build_system=cmake cxxstd=11 patches=08fb707
            matio@1.5.26+hdf5+shared+zlib
            parallel@20240822
        utf8cpp@2.3.4 build_system=generic
        xz@5.4.6 libs=shared,static
```
</details>

Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py -ma

**Comment by cessenat** [comment]
Thanks @bernhardkaindl
