### PR TITLE
cuda: Add v12.9 and new Blackwell targets

### PR DESCRIPTION
**Pull request by pauleonix**
Adds support for `cuda_arch=`
- `103`
- `121`
- new [family-specific architecture features](https://developer.nvidia.com/blog/nvidia-blackwell-and-nvidia-cuda-12-9-introduce-family-specific-architecture-features/) like `100f` etc.

### CODE REVIEW

**Comment by alalazo** [comment]
Can you look at pipeline failures?

**Comment by pauleonix** [comment]
- `tau` and `caliper` build failures clearly are caused by depending on `nvToolsExt`, which [was dropped in favor of the newer `nvtx3` in CUDA 12.9](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id4). So I will add conflicts to their recipes.  (EDIT: I reported the issues: https://github.com/UO-OACISS/tau2/issues/21 https://github.com/LLNL/Caliper/issues/668)
- For `petsc` I will try to expand the version range of the workaround for CUDA 12.8 and hope that is all. (EDIT: It wasn't, it also had a `nvToolsExt` issue.)
- ~~`legion` looks like it has nothing to do with my changes, so I hope it will just work next time.~~ See https://github.com/spack/spack/pull/50284#issuecomment-2855329787

**Comment by pauleonix** [comment]
Sorry, must have miss-clicked the close button.

**Comment by pauleonix** [comment]
From [#49379](https://github.com/spack/spack/pull/49379#issuecomment-2847686301):
> https://gitlab.spack.io/spack/spack/-/pipelines/1018136
> 
> Hm - I see the failure was with petsc@3.22.4
> 
> petsc@3.23 should work without this change [but will cause no harm with it.]

@balay Seems like petsc@3.23.1 still has the issue (or a new one?): https://gitlab.spack.io/spack/spack/-/jobs/16454189

**Comment by balay** [comment]
>@balay Seems like petsc@3.23.1 still has the issue (or a new one?): https://gitlab.spack.io/spack/spack/-/jobs/16454189

```
/usr/bin/ld: cannot find -lnvToolsExt: No such file or directory
```
looks like cuda-12.9 changed from providing `nvToolsExt` library to `nvtx3interop`

A hack to get this working with 12.9 is:
```patch
diff --git a/config/BuildSystem/config/packages/cuda.py b/config/BuildSystem/config/packages/cuda.py
index 8509bb89b91..b73f62b7ec7 100644
--- a/config/BuildSystem/config/packages/cuda.py
+++ b/config/BuildSystem/config/packages/cuda.py
@@ -10,7 +10,7 @@ class Configure(config.package.Package):
     self.requiresversion   = 1
     self.functions         = ['cublasInit','cufftDestroy']
     self.includes          = ['cublas.h','cufft.h','cusparse.h','cusolverDn.h','curand.h','thrust/version.h']
-    self.basicliblist      = [['libcudart.a','libnvToolsExt.a'],
+    self.basicliblist      = [['libcudart.a','libnvtx3interop.a'],
                               ['cudart.lib','nvToolsExt.lib']]
     self.mathliblist       = [['libcufft.a', 'libcublas.a','libcusparse.a','libcusolver.a','libcurand.a'],
                               ['cufft.lib','cublas.lib','cusparse.lib','cusolver.lib','curand.lib']]
```
For now - perhaps we can selectively use this patch for cuda@12.9: or limit petsc to using cuda 12.8 or lower [in spack]

cc: @jczhang07

**Review by eugeneswalker — DISMISSED** [review]

**Comment by pauleonix** [comment]
```
/tmp/root/spack-stage/spack-stage-legion-25.03.0-4szgrdg4jc4nf7e2lsv4y4zqnew6j2dx/spack-src/runtime/realm/cuda/cuda_module.cc: In function 'bool Realm::Cuda::resolve_cuda_api_fnptrs()':
/tmp/root/spack-stage/spack-stage-legion-25.03.0-4szgrdg4jc4nf7e2lsv4y4zqnew6j2dx/spack-src/runtime/realm/cuda/cuda_module.cc:2701:50: error: invalid conversion from 'CUresult (*)(CUdeviceptr, size_t, CUmem_advise, CUdevice)' {aka 'cudaError_enum (*)(long long unsigned int, long unsigned int, CUmem_advise_enum, int)'} to 'PFN_cuMemAdvise_v12020' {aka 'cudaError_enum (*)(long long unsigned int, long unsigned int, CUmem_advise_enum, CUmemLocation_st)'} [-fpermissive]
 2701 |   if(CUDA_SUCCESS != (nullptr != (name##_fnptr = reinterpret_cast<decltype(&name)>(      \
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  CUresult (*)(CUdeviceptr, size_t, CUmem_advise, CUdevice) {aka cudaError_enum (*)(long long unsigned int, long unsigned int, CUmem_advise_enum, int)}
 2702 |                                       dlsym(libcuda, STRINGIFY(name)))))) {              \
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
```
This looks like there is a fundamental incompatibility at the CUDA driver API level, so I guess legion also needs a conflict with CUDA 12.9. Created https://github.com/StanfordLegion/realm/issues/12

**Review by eugeneswalker — DISMISSED** [review]

File: var/spack/repos/spack_repo/builtin/packages/legion/package.py [hunk 1]
```diff
@@ -121,10 +121,10 @@ class Legion(CMakePackage, ROCmPackage):
     depends_on("mpi", when="conduit=mpi")
     depends_on("cuda@10.0:11.9", when="+cuda_unsupported_compiler @21.03.0:23.03.0")
     depends_on("cuda@10.0:11.9", when="+cuda @21.03.0:23.03.0")
-    depends_on("cuda@11.7:", when="+cuda_unsupported_compiler @23.06.0:")
-    depends_on("cuda@11.7:", when="+cuda @23.06.0:")
-    depends_on("cuda@11.7:", when="+cuda_unsupported_compiler @stable")
-    depends_on("cuda@11.7:", when="+cuda @stable")
+    depends_on("cuda@11.7:12.8", when="+cuda_unsupported_compiler @23.06.0:25.03.0")
+    depends_on("cuda@11.7:12.8", when="+cuda @23.06.0:25.03.0")
```
Comment (elliottslaughter) [inline var/spack/repos/spack_repo/builtin/packages/legion/package.py]: Please don't add the Legion upper version bounds, because this excludes `master`. We can add the version bound once we make the next Legion release.

**Comment by elliottslaughter** [comment]
Legion looks good now.

File: var/spack/repos/spack_repo/builtin/packages/petsc/package.py [hunk 2]
```diff
@@ -580,7 +580,7 @@ def configure_options(self):
         else:
             options.append("--with-sycl=0")
 
-        if spec.satisfies("^cuda@12.8.0"):
+        if spec.satisfies("@:3.22^cuda@12.8:"):
```
Comment (balay) [inline var/spack/repos/spack_repo/builtin/packages/petsc/package.py]: Note: this change is not needed by this PR [for CI to succeed] - however its good to add it in for petsc - either via this PR - or via https://github.com/spack/spack/pull/49379 [or separately]

Comment (pauleonix) [reply var/spack/repos/spack_repo/builtin/packages/petsc/package.py]: I added it here because I had to modify the line either way to expand it to CUDA 12.9.

**Review by eugeneswalker — APPROVED** [review]

**Comment by balay** [comment]
Hm - I don't understand the CI failures
- https://github.com/spack/spack/actions/runs/14970773363/job/42051602214?pr=50284
```
==> Error: Invalid environment configuration detected: error parsing YAML: near C:\Users\runneradmin\.spack\bootstrap\environments\python3.9-x86_64-3d3ce\spack.yaml, 28, 18: found unknown escape character 'h'
```
- https://github.com/spack/spack/actions/runs/14970773363/job/42051602196?pr=50284

For now rebasing the branch to cleanup the commits/messages - in case they are preserved when the PR is merged.

**Comment by pauleonix** [comment]
Yeah, I was confused as well, but I saw some other PRs/pipelines with similar looking errors (#50430 by @haampie specifically), so I assumed it is a problem on develop.

**Comment by pauleonix** [comment]
@adamjstewart Any idea about this py-torch failure? https://gitlab.spack.io/spack/spack/-/jobs/16623974
There is lots of warnings about deprecated APIs (should be fine) but also
```
[3520/7067] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/RowwiseScaledMM.cu.o
FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/RowwiseScaledMM.cu.o
```
without any further information and then later
```
  ninja: build stopped: subcommand failed.
  cmake --build . --target install --config Release -j 12
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/software/spack/[padded-to-256-chars]/linux-x86_64_v3/python-venv-1.0-egfdhkm6teke5tqsysapk7rfkfbx5qcl/bin/python3 /home/software/spack/[padded-to-256-chars]/linux-x86_64_v3/py-pip-25.0.1-zzpaxtgzmn4clpxewymakk3sqcdn3hhs/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3n7oy74x
  cwd: /tmp/root/spack-stage/spack-stage-py-torch-2.7.0-7sbppymhoxpzpapi7l22f6wpxp7tsxmn/spack-src
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Does this look like an incompatibility? I.e. should I just add a conflict or similar?

**Comment by adamjstewart** [comment]
I've never seen this before, and couldn't find anything on PyTorch's issue tracker. It's weird that it would only fail on the e4s pipeline and not any of the ml pipelines, all use the same cuda_arch setting. Maybe rerun it again. I'm hesitant to add a conflict without at least first opening an issue to get to the bottom of this.

**Comment by eugeneswalker** [comment]
> I've never seen this before, and couldn't find anything on PyTorch's issue tracker. It's weird that it would only fail on the e4s pipeline and not any of the ml pipelines, all use the same cuda_arch setting. Maybe rerun it again. I'm hesitant to add a conflict without at least first opening an issue to get to the bottom of this.

`py-torch +cuda` is only built in E4S stack. The `+cuda` build of py-torch is the one that is failing.

Here is another relevant part of failed job log not excerpted above:
* https://gitlab.spack.io/spack/spack/-/jobs/16623974
```
...
     868       [61/7067] Generating src/x86_64-fma/2d-fourier-8x8.py.o
  >> 869     /tmp/root/spack-stage/spack-stage-py-torch-2.7.0-7sbppymhoxpzpapi7
             l22f6wpxp7tsxmn/spack-src/third_party/python-peachpy/peachpy/parse
             .py:41: SyntaxWarning: invalid escape sequence '\('
     870         with_regexp = r"with\s+(?:\w+\.)*" + re.escape(constructor_nam
             e) + "\(.*\)\s+as\s+([_a-zA-Z]\w*)\s*:"
...
```

**Comment by adamjstewart** [comment]
`py-torch+cuda` is also built in the `ml-linux-*-cuda` stacks and seems to be building fine.

**Comment by eugeneswalker** [comment]
> `py-torch+cuda` is also built in the `ml-linux-*-cuda` stacks and seems to be building fine.

You're right. Sorry. I missed that. I was grepping the stacks and didn't realize you imposed the `+cuda` via `packages:`! In that case, I have no idea.

We could disable `py-torch +cuda` in E4S stack if you want to get this in. Maybe that's best. Let's not hold this contribution up.

**Comment by pauleonix** [comment]
@spackbot re-run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by pauleonix** [comment]
@adamjstewart @eugeneswalker Seems like it was just a weird glitch... :man_shrugging:
