### PR TITLE
adios2: mark conflict with newer Python

### PR DESCRIPTION
**Pull request by adamjstewart**
Extracted out of #46913

### CODE REVIEW

**Review by vicentebolea — APPROVED** [review]
This is due to the old pybind11 that adios 2.7 ships with its source code

**Review by bernhardkaindl — APPROVED** [review]
Approving as GitLab CI pipeline has successfully finished and this is a step into the right direction.

However, when testing more Python versions, not just 3.11, not even Python 3.8 works with adios@:2.7 (tried also 3.9 and 3.11):

The build errors may vary, and likewise stem from the `thirdparty/pybind11`, vendored in adios2.

Examples:
```py
const struct pybind11::detail::function_record' has no member named 'nargs_kw_only'
const struct pybind11::detail::function_record' has no member named 'nargs_pos_only'
const struct pybind11::detail::function_record' has no member named 'nargs'; did you mean 'args'?
error: 'uint16_t' is not a member of 'std'; did you mean 'wint_t'?
```

I did not test Python 3.7 and older as Spack cannot build those EOL versions and also Spack is now in the progress of removing even Python 3.8 as 3.8 is now also EOL.

Therefore, I'd like to propose to limit `+python` to `adios@2.8:`:
```py
-    variant("python", default=False, description="Enable the Python bindings")
+    variant("python", default=False, when="@2.8:", description="Enable the Python bindings")
```

In https://github.com/ornladios/ADIOS2/discussions/4171, I've seen that 2.8  is now unmaintained and unsupported, so I think choosing to support `+python` only starting 2.8 does not seem restrictive.

Of course, the conflict could be expanded as well to cover more Python versions, as far as I tested at least:
```py
conflicts("^python@3.8:", when="@:2.7", msg="+python needs ^adios@2.8:")
```

I guess both ways to say to need `@2.8:` for `+python` have their pros and cons. In the variant, it becomes visible in `spack info adios2`, and in the conflict, the concretizer could issue a message when "msg=" is added.

However, as this helps already, is approved by @vicentebolea and has passed CI, I approve and merge.
