### PR TITLE
fix: `spack compilers` lacks `--remote` argument

### PR DESCRIPTION
**Pull request by paulgessinger**
This is expected by the common `compiler_list` function that is also called from `spack compiler list`.
I think `--remote` was introduced in https://github.com/spack/spack/pull/50682

Without this you get an error like

```console
$ spack compilers
==> Error: 'Namespace' object has no attribute 'remote'
```

### CODE REVIEW

**Review by tgamblin — DISMISSED** [review]

**Comment by tgamblin** [comment]
Thanks!

**Review by tgamblin — APPROVED** [review]
