### PR TITLE
OpenMPI 5 w/ PRRTE 3 series PMIX version check fix

### PR DESCRIPTION
**Pull request by nyetsche**
OpenMPI fails to compile otherwise when targeting external PMIX 4.2.6 and likely others.

```
  >> 3369    base/ess_base_bootstrap.c:72:14: error: static declaration of 'pmix_getline' follows non-static declaration
     3370       72 | static char *pmix_getline(FILE *fp)
     3371          |              ^
     3372    /opt/pmix/include/pmix/src/util/pmix_string_copy.h:83:19: note: previous declaration is here
     3373       83 | PMIX_EXPORT char *pmix_getline(FILE *fp);
     3374          |                   ^
     3375    1 error generated.
  >> 3376    make[4]: *** [Makefile:820: base/ess_base_bootstrap.lo] Error 1
```

Upstream PRRTE fix (not released yet): https://github.com/openpmix/prrte/pull/1957
Upstream OpenMPI issue: https://github.com/open-mpi/ompi/issues/12537 ("fixed in next release")

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
I also added PR to get pmix versions so we should get these merged too https://github.com/spack/spack/pull/44927

**Comment by nyetsche** [comment]
My apologies, I realized after this PR that my patch only works on 5.0.3. I've updated the PR but I believe the patch is required for the others in the 5.0.x series.

**Review by hppritcha — APPROVED** [review]
I thought the preference was to pull patches from PRs, etc. rather than adding patches directly to spack source tree.  But otherwise i'm okay with this PR.  

Yes I know we haven't been following that rule in this spack package...

**Comment by nyetsche** [comment]
> I thought the preference was to pull patches from PRs
@hppritcha 

I'm still relatively new to opening PRs with spack - can you explain or give an example of what you'd prefer? The section at https://github.com/spack/spack#contributing doesn't mention anything special about `patch` patches.

**Comment by hppritcha** [comment]
oh as an example see https://github.com/spack/spack/pull/44595/files

**Comment by hppritcha** [comment]
but i'm fine with this as is.  the ci failure needs to be fixed though.  i'm assuming the rest of ci will pass...

**Comment by nyetsche** [comment]
@hppritcha  the CI was easy, only whitespace formatting, but I split the patch so it applies to both `5.0.3` and `5.0.0:5.0.3`. Is that the most elegant way to do so?

**Comment by hppritcha** [comment]
that looks elegant enough for me.  I vote for merging if CI passes.

**Comment by shahzebsiddiqui** [comment]
@nyetsche i just updated the branch since it was out of date.

**Comment by nyetsche** [comment]
@shahzebsiddiqui I had to update the branch too, but I finally had it pass all CI checks. Are you able to merge?

**Review by alalazo — APPROVED** [review]
