### PR TITLE
Charliecloud with SquashFUSE support

### PR DESCRIPTION
**Pull request by benkirk**
Replaces #34847

This PR makes Charliecloud's internal SquashFUSE support functional, which requires very specific SquashFUSE versioning.  

This updated PR keeps the Squashfuse package continuing to use the manually created tarball artifacts, as requested.

### CODE REVIEW

File: var/spack/repos/builtin/packages/charliecloud/package.py [hunk 1]
```diff
@@ -128,8 +128,8 @@ class Charliecloud(AutotoolsPackage):
     # See https://github.com/spack/spack/pull/16049.
     conflicts("platform=darwin", msg="This package does not build on macOS")
 
-    # Squashfuse support
-    depends_on("squashfuse@0.1.105:", when="+squashfuse")
+    # Squashfuse support - only a narrow range at least through v0.35
+    depends_on("squashfuse@0.1.105:0.2.0", when="+squashfuse")
     depends_on("squashfs", type="run", when="+squashfuse")
```
Comment (reidpr) [inline var/spack/repos/builtin/packages/charliecloud/package.py:133]: Interestingly, it’s *only* SquashFUSE 0.3.0 that is incompatible (hpc/charliecloud#1696). 0.1.105 as well as 0.4.0 and up are fine.

How to represent this in Spack I wouldn’t know, though IMO requiring SquashFUSE ≥0.4.0 would be fine. I do think requiring 0.1.105 ≤ *x* ≤ 0.2.0 would be a mistake.

**Review by reidpr — CHANGES_REQUESTED** [review]
Thanks for your continued work on this!

File: var/spack/repos/builtin/packages/charliecloud/package.py (hunk 1 above)
Comment (benkirk) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: Interesting, I think this failed for me even with v0.5.0.  Let me confirm.

Comment (benkirk) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: @reidpr, sure enough...

SquashFUSE success matrix:

- v0.5.0 fails: 
    ```pre
       77    checking if mksquashfs version >= 4.2... ok (4.6.1)
       78    checking for squashfuse... squashfuse
       79    checking if squashfuse version >= 0.1.100... ok (0.5.0)
       80    checking for fuse_set_signal_handlers in -lfuse3... yes
       81    checking for sqfs_ll_mount in -lsquashfuse_ll... yes
       82    checking for squashfuse/ll.h... no
  >> 83    configure: error: libsquashfuse requested but not found

    ```
- **v0.4.0 builds**,
- v0.3.0 fails:
   ```pre
   >> 300    ch_fuse.c:229:12: error: too few arguments to function 'sqfs_ll_open'
      301        sq.ll = sqfs_ll_open(img_path, 0);
      302                ^~~~~~~~~~~~
      303    In file included from ch_fuse.c:31:0:
      304    /glade/work/benkirk/bugreports/spack/container_runtimes/spack/opt/spack/linux-opensuse15-x86_64/gcc-7.5.0/squashfuse-0.3.0-hwoegcmua6exkhcs6d5qxnfybvshnowi/include/squashfuse/ll.h:147:10: note: declared here
      305     sqfs_ll *sqfs_ll_open(const char *path, size_t offset, const char *subdir);
      306                ^~~~~~~~~~~~
   ```
- **v0.2.0, v0.1.105 build**.


So, I don't know... I'm not quite spack package savvy enough, but is there a way to go >= 0.1.105 but != 0.5.0?

Comment (reidpr) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: Thank you. I thought we were testing against whatever is latest, but that’s pretty convincing. I will investigate on our end.

Odds are high 0.36 will build against 0.5.0 but that doesn't help you much with a 0.35 package.

Comment (benkirk) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: Thanks for that, and honestly I'm reassured quite a bit knowing that others are tracking this feature set too.  It's pretty enabling for us to recommend `charliecloud` at our site!

Comment (reidpr) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: My guess is that 0.35 will also not build with anything greater than 0.5.0, so the ideal constraint is likely { 0.1.105, 0.2.0, 0.4.0 }.

Comment (reidpr) [reply var/spack/repos/builtin/packages/charliecloud/package.py:133]: See hpc/charliecloud#1784 for the upstream fix to build with SquashFUSE 0.5.0.

**Comment by j-ogas** [comment]
@benkirk thank you, so much, for your work here that lead to  #42590. Closing as this is now resolved.
