### PR TITLE
pango: harfbuzz+coretext required on macOS

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 10.15.7 (x86_64) with Apple Clang 12.0.0.

Without this change, the pango build was failing with:
```
../spack-src/pango/pangocoretext.c:27:10: fatal error: 'hb-coretext.h' file not found
```

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.  Rest LGTM.

**Comment by tldahlgren** [comment]
@spackbot fix style

File: var/spack/repos/builtin/packages/harfbuzz/package.py [hunk 1]
```diff
@@ -109,6 +116,11 @@ def meson_args(self):
             "-Dgraphite2=" + ("enabled" if self.spec.satisfies("+graphite2") else "disabled")
         )
 
+        if "+coretext" in self.spec:
+            args.append("-Dcoretext=enabled")
+        elif "~coretet" in self.spec:
```
Comment (becker33) [inline var/spack/repos/builtin/packages/harfbuzz/package.py]:
```suggestion
        elif "~coretext" in self.spec:
```

File: var/spack/repos/builtin/packages/harfbuzz/package.py [hunk 2]
```diff
@@ -124,6 +136,11 @@ def configure_args(self):
         args.append("GTKDOC_REBASE={0}".format(true))
         args.extend(self.with_or_without("graphite2"))
 
+        if "+coretext" in self.spec:
+            args.append("--with-coretext")
+        elif "~coretet" in self.spec:
```
Comment (becker33) [inline var/spack/repos/builtin/packages/harfbuzz/package.py]:
```suggestion
        elif "~coretext" in self.spec:
```

**Review by becker33 — CHANGES_REQUESTED** [review]

**Review by becker33 — APPROVED** [review]
