### ISSUE TITLE
spack external find openmpi does not work in v0.17.0.

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [LLNL/spack#27762]
We would like to standardize on a version number for our development environments. The 0.17.0 has a bug finding external openmpi installs. **This issue is fixed in develop branch.** I wasn't able to find the particular commit though. 

@becker33 

Thank you.

### Steps to reproduce

❯ source spack/share/spack/setup-env.sh
❯ spack external find openmpi
==> Error: 'tuple' object has no attribute 'values'

### Error message

==> Error: 'tuple' object has no attribute 'values'

### Information on your system

Confirmed on two installs

❯ spack debug report
* **Spack:** 0.17.0
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo
* 
[quenneg@beluga1 workspace]$ spack debug report
* **Spack:** 0.17.0
* **Python:** 3.6.10
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
